### ISSUE TITLE
Native resolution texrects in Android

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1013]
I just tried native resolution texrects in Android and they don't make a big difference. Here is screenshots with them on:

![mariokart64-001](https://cloud.githubusercontent.com/assets/11581687/15801353/122c6a6c-2a60-11e6-840c-8559444d7e9b.png)
![mariokart64-002](https://cloud.githubusercontent.com/assets/11581687/15801354/191d01d8-2a60-11e6-8d1a-8d182e363cef.png)

**Comment by fzurita** [comment]
Actually it looks identical with it on or off.

**Comment by oddMLan** [comment]
Does it work if you turn off the texture enhancements?

**Comment by fzurita** [comment]
Yep, indeed it does. Big slow down on Android.

**Comment by wareya** [comment]
The problem is the individual parts are being enhanced but the enhancement doesn't know what to do when it hits the edges so there will still be seams. Ideally enhancement would not run on texrects until after they're rendered but this could be very slow, hence presentation of native resolution texrects using normal interpolation like linear/cubic.

**Comment by gonetz** [comment]
> Edit: I guess it must be getting disabled when texture enhancements are on.

Yes. Native resolution texrect drawing works only when textures have original size.

**Comment by fzurita** [comment]
I'll go ahead and close this issue, user error then. I'll have to disable texture enhancements in Android that increase texture size when this option is enabled.
