### ISSUE TITLE
GLES incorrect check for GL_NV_fragdepth

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1072]
For GLES 3.0/3.1 shader programs we are checking for GL_NV_fragdepth before using gl_FragDepth. I don't think this check is needed.

I disabled the check and checked the pilotwings shadows and they displayed correctly in all my devices. Unfortunately, in one of my devices, when writing to gl_FragDepth, it causes the device to crash when the shader is run. But the shader still compiles, links, and starts ok.

Here is a reference page that says that gl_FragDepth is supported for GL ES 3.0 and 3.1: https://www.khronos.org/opengles/sdk/docs/man31/html/gl_FragDepth.xhtml

**Comment by fzurita** [comment]
Due to some devices crashing when writing to gl_FragDepth, I think this should be an optional feature set in configuration that is enabled by default on desktop. I can make it not default in Android.

**Comment by gonetz** [comment]
Are you sure that devices crashing when writing to gl_FragDepth? Such devices should crash with every game because gl_FragDepth every shader writes to gl_FragDepth when GL_NV_fragdepth is enabled?

Also, if I remember correctly, I added GL_NV_fragdepth check because some users complained that shaders do not compile on their devices. I could be wrong there though.

**Comment by fzurita** [comment]
Yes, it's crashing in all games when writing to gl_FragDepth on one of my devices,

I believe the check is not needed because it's part of the standard in GLES 3.0+.

It should still be optional though because it can crash the driver on some devices.

**Comment by gonetz** [comment]
Ok.

**Comment by loganmc10** [comment]
The other problem with this is that it makes an assert fail with GLES3

```
GLideN64/src/OpenGL.cpp:403: void OGLRender::TexrectDrawer::init(): Assertion `m_depthScaleLoc >= 0' failed.
```

Because of this code:
https://github.com/gonetz/GLideN64/blob/4bcf330759f71a9879dd2888e349238bd6e9c39c/src/OGL3X/Shaders_ogl3x.h#L320-L323

If GLES3 is in use, and GL_NV_fragdepth is not set, that line of code is never executed, and I believe uDpethScale is then "optimized" out of the shader because it is never used, and thus the assertion is thrown.

**Comment by fzurita** [comment]
Yep, I did run into that as well.

**Comment by gonetz** [comment]
Can it be closed now?

**Comment by fzurita** [comment]
Yep
