### ISSUE TITLE
Link's portrait is missing in the pause screen

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1134]
![screenshot from 2016-09-24 16-33-43](https://cloud.githubusercontent.com/assets/848146/18811667/298fcc68-8275-11e6-97d3-920f8cec9d0e.png)

One of the users of GLupeN64 said that it happens because of the changes made on Sept 18/19

8dad84cc39571c295d10a3b3c9326fa942478fcd
b5163ca04881d372a924056fe41a753ca14c39dc
6f3f21667eab3c0e0154cf4885731205a957a261

Somewhere around there, I haven't had the time to figure out exactly what caused it yet.

**Comment by Jj0YzL5nvJ** [comment]
I be seeing this too =P

**Comment by orbea** [comment]
Its a little bit different here with Slackware64-current and nouveau. 

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-09-24-065846_1680x1050_scrot.png)

**Comment by Jj0YzL5nvJ** [comment]
In aadd94ccc4c7d0ae9cd55dfb0e599b3ca2f9d410 for me looks more like @loganmc10, case, but if I change the shield for fist time looks like this:
![the_legend_of_zelda-000](https://cloud.githubusercontent.com/assets/12230570/18812490/7d6f1c62-8293-11e6-9834-1dc1f8423903.png)

If I change the shield again it turn black completely.

**Comment by orbea** [comment]
I get the same, if I change the shield it will go partially black, changing it again it goes completely black.

**Comment by Jj0YzL5nvJ** [comment]
The culprit is 8dad84cc39571c295d10a3b3c9326fa942478fcd.
Well, I will continue reading manga ^^

**Comment by orbea** [comment]
Thanks your solution works fine for both Orcarina of Time and Toy Story 2 here.

**Comment by loganmc10** [comment]
fixed, thanks

**Comment by gonetz** [comment]
BTW, I can't get pause screen working on Ubuntu - background is white. I guess that cheat code for pause screen delay is enabled somewhere, but can't find how to disable it.

**Comment by retrobenny** [comment]
If you can figure out how to disable it try using this code in its place to see if it still goes white.

Subscreen Fix
D01C7021 0002
801DA5CB 0002
D01C7021 0002
801C7021 0003
A different code that fixes the delay without the usual glitch that the other code has from breaking the resolution value.

This one is my port of the MQ Debug version's code,and it also works for preventing crashes when CountPerOp/Counter Factor is 1 and/or when the lagfix code is used for the extra performance needed for my more extreme glitch-codes like "Handy Link" where Link's body is made entirely out of hands.
Hope this one doesn't result in a white screen,it shouldn't.

The breakdown is that it forces a value to change sooner than it normally does so that the game doesn't freak out from its own delay (drawing the background image?) in a lagless situation such as CPO/CF=1 and/or the lagfix code,it also fixes the delay in normal situations too.
