### ISSUE TITLE
NBA Courtside 2 - Featuring Kobe Bryant wrong intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1138]
the game needs  render buffer as texture to display the correct gfx in intro

yet a screen is not correct as it gets mixed with the previous one which does not clear up

![sdfsd](https://cloud.githubusercontent.com/assets/8987490/18851974/a65b69f8-843e-11e6-841a-d94e9f1872c3.jpg)

**Comment by gonetz** [comment]
Current code makes black texels invisible.
I can fix it. However, the game will require color buffer copy to RDRAM in sync mode.
Otherwise title screen will be incorrect.
Background picture on title screen rendered by RDP.
"Press start" message on title screen rendered by CPU. Only that message. 
The buffer in RDRAM must contain background image, or we will get black background and "press start" message only.

FBInfo should help to emulate everything correctly, but NBA logo is skipped in Mupen64 when FBInfo enabled.

**Comment by gonetz** [comment]
I pushed fix for this issue to master. It is included into my latest public build.

**Comment by olivieryuyu** [comment]
fixed
