### ISSUE TITLE
Ok so in the mario 64 star road hack i have this issue with the water any ideas how to fix it?

### ISSUE THREAD

**Issue by Ryan7251** [gonetz/GLideN64#1151]
Ok so my issue is this is the best plugin i could find for this hack however water seems to "Overflow" off edges namely at the stat of the game the water is not really there and it vanishes if i get close to it but still it gets on my nerves.
So does anyone know a way to fix it or a good plugin for the hack?

**Comment by retrobenny** [comment]
Hmm,what emulator and platform? The water issue on Android would be fixed by changing the polygon offset hack option until you get the desired result.

GLideN64 is not recommended for SM64 hacks because custom textures are pitch black and sounds are displaced when the frame buffer is enabled.
Accurate plugins seem to hate SM64 hacks since Angrylion also can't display the custom textures.
Any non-custom ones display just fine,then again actual systems freeze/crash via Everdrive.

**Comment by Craftyawesome** [comment]
A way was found to boot it so it is accurate. https://youtu.be/M-iZ33fROGk

**Comment by olivieryuyu** [comment]
@ gonetz

can it be closed?
