### ISSUE TITLE
Mortal Kombat 4 Missing 2D elements

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1155]
This is in reference to the issue created in the Mupen64Plus-AE github page. See these issues:
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/587
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/588

Mortal Kombat 4 is missing 2D elements during fights. It works fine if using LLE.

I'm not sure yet if it's an Android specific issue but it does seem to happen with GLES2.0 and GLES 3.0. Here is the relevant screenshot:

![5xee8iw](https://cloud.githubusercontent.com/assets/11581687/19100082/b632896e-8a89-11e6-9136-7b700ead4236.png)

**Comment by gonetz** [comment]
Desktop build for mupen64plus shows 2D with HLE as well.

**Comment by fzurita** [comment]
Ok, I wonder if this is going to be an Android specific issue. I'll do more testing.

**Comment by fzurita** [comment]
Ok, I have tried every setting I can think of as well as disabling NEON optimizations and I can't get those health bars to show up. I also tried the full OpenGL mode in the shield TV without much success.

@gonetz do you happen to know how those health bars are drawn? Do I need to have a specific configuration?

**Comment by gonetz** [comment]
2D here are usual triangles, not texrects. The problem is that Z value for these triangles is less than -1 and thus triangles rejected by Z clipping. It works on N64 because z-compare is disabled for these polygons. It works in LLE mode because polygons clipping already done by RSP. It works on desktop with HLE because plugins disables Z-clipping with 
```
	// Disable near and far plane clipping
	glEnable(GL_DEPTH_CLAMP);

```
```
GL_DEPTH_CLAMP
If enabled, the -wc ≤ zc ≤ wc plane equation is ignored by view volume clipping (effectively, there is no near or far plane clipping). See glDepthRange.
```
It does not work with GLESX because GLES does not support GL_DEPTH_CLAMP.

glEnable(GL_DEPTH_CLAMP) also helps with ucodes, which does not use near plane clipping (GBI.isNoN())
There is a hack for GLESX in OGLRender::addTriangle to deal with NoN ucodes. This hack does not work for MK4 because its ucode is not detected as NoN one. It is "F3DLX.Rej  1.23" I read description of that microcode. It also does not have near plane clipping, so it should have NoN flag.

**Comment by gonetz** [comment]
Should be fixed now.

**Comment by fzurita** [comment]
Cool, thanks!

**Comment by fzurita** [comment]
Interesting, for some reason this wasn't working with the Full OpenGL implementation in Android Shield TV. I will have to investigate why.

**Comment by fzurita** [comment]
Ok, I think I know why. I have a bug in the code that is replacing the EGL version of the plugin with one of the GL versions when it shouldn't be. I'll have to fix that.

**Comment by fzurita** [comment]
It works, closing.
