### ISSUE TITLE
"Render at constant factor of native resolution": Is 1x always 320x240?

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#1189]
Some games, particularly later in the N64's life could render at 640x480 but it appears setting this setting to 1x continues to render at 320x240. Is this intended behaviour?

If you can, tag this issue as "Question"

**Comment by mudlord** [comment]
good question, ive been wanting to know this for ages, so then I can simply rescale the image from the internal res to a common pc res, like 640x480,800x600, etc

**Comment by AmbientMalice** [comment]
The N64 renders in a wide range of internal resolutions. It is completely arbitrary. The Video Interface then scales the image to either 320x240p or 640x480i for output.

320x240 is a very common resolution. But the actual internal buffer can be 320x237, for example.

"High Resolution" is typically 480x360.

You'd really have to specify what games you're talking about.

GLideN64 IMO shouldn't support internal resolutions that aren't a multiple of native because doing so breaks things. But currently, 2x native should result in, for example, Perfect Dark in High Resolution mode running at 1024x444 since the native internal resolution is 640x222, at least in the American version. But of course there is a mild problem with Perfect Dark because a real N64 outputs the 640x222 framebuffer as 320x240, as a crude form of downsampling. So GLideN64's behavior isn't 100% accurate because it doesn't bother doing the 320x240/640x480 conversion pass that a real N64 does. it just scales the output once.

**Comment by Aquatakat** [comment]
There were a couple games I played with where I was checking if high resolution mode made a difference, Perfect Dark being one of them, and I couldn't really tell the difference in-game. But when I take screenshots there is a clear difference.

I suppose this matches my experience with the actual console, now that I think about it. The high resolution mode very rarely was different enough to warrant the bad framerates.

([my screenshots, if anyone is interested](http://imgur.com/a/CbOfS))
