### ISSUE TITLE
Pokemon Stadium 2 corrupt graphics until save state is loaded

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1197]
At startup, graphics look incorrect 100% of the time. They look like this:

![pokemon_stadium_2-000](https://cloud.githubusercontent.com/assets/11581687/19838877/876e9e54-9eae-11e6-8df1-e83cda6dd625.png)

If a save state is created and loaded from this exact same location, graphics will look normal again.

Here is my GLideN64 configuration:

[mupen64plus.zip](https://github.com/gonetz/GLideN64/files/560658/mupen64plus.zip)

Also, no GL errors are detected at this time.

**Comment by loganmc10** [comment]
I am experiencing this in GLupeN64 as well, but a build from Oct 25 doesn't have this issue, I'll track down the commit that broke it

**Comment by loganmc10** [comment]
@fzurita It seems that this is because of the frameBufferEmulation.copyDepthToRDRAM setting.

From my testing, both cdCopyFromVRam and cdSoftwareRender cause this problem, it only works when it is disabled.

If that is confirmed then an entry should be added to GLideN64.custom.ini disabling the setting for this game.

**Comment by loganmc10** [comment]
Although given the fact that cdSoftwareRender was recently made the default on all games it might be worth looking into why this doesn't work, that is a little over my head though.

**Comment by fzurita** [comment]
hmm... interesting, sounds like there is a bug there somewhere. It almost sounds like we are copying the depth buffer when it has not yet been initialized.

**Comment by loganmc10** [comment]
Ya its probably something related to that, I actually caused this exact same bug in GLupeN64 a while ago when I was messing around with glInvalidateFramebuffer:

https://github.com/loganmc10/GLupeN64/issues/68
https://github.com/loganmc10/GLupeN64/issues/68#issuecomment-252100920

So it is probably the result of it expecting some info to be in the depth buffer that isn't there (since glInvalidateFramebuffer was wiping the depth buffer when it shouldn't be)

**Comment by loganmc10** [comment]
Actually maybe that first report was just because someone had this option enabled. I could never reproduce the Pokemon Stadium 2 issues and someone said:

> It appears to be related to depth buffer copy to RDRAM. Disabling fixes the issue.
> I just tried out the other two. They're still valid even with depth buffer copy turned off.

So it was probably unrelated to the glInvalidateFramebuffer stuff

**Comment by fzurita** [comment]
Yeah, that's interesting. That's a pretty good hint though I think.

**Comment by fzurita** [comment]
Does anything get broken with depth buffer emulation turned off with this game?

**Comment by loganmc10** [comment]
Not that I'm aware of, it was off by default for a long time, software depth emulation just recently became the default
