### ISSUE TITLE
Banjo Tooie (U) missing graphics with framebuffer off

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#1291]
![gliden64_banjo_tooie_007](https://cloud.githubusercontent.com/assets/11056843/20876074/4b237558-bab7-11e6-8e89-c38cf686fa58.jpg)

But every now and again, they will appear briefly.
![gliden64_banjo_tooie_008](https://cloud.githubusercontent.com/assets/11056843/20876087/61caceb4-bab7-11e6-8b89-e03e5c2e035d.jpg)

Intel HD Graphics, supports upto OpenGL 4.0.  No problem with Kazooie.
Using latest WIP build 7d4c5fc.

**Comment by AmbientMalice** [comment]
Is this actually a bug or simply a quirk in the game's rendering?

**Comment by gonetz** [comment]
Why run it without fb emulation?

**Comment by retrobenny** [comment]
The issue can happen on Glide64 as well but doesn't happen on Rice,which instead has a solid black dynamic shadow if you tweak the settings (VI Origin) and no shadow appears on Rice's default settings.
I would presume that it is a quirk caused by the dynamic shadow of the player characters,if you make it to the JiggyWiggy temple,your shadow is a circle in there.

I have a code buried in one of my PJ64 topics that makes you always have the basic circle shadow,fixing the quirk on those plugins.
I managed to find it rather quickly in my topic Pg.24 here it is to enjoy.

Basic Shadows
800A6EC3 0001
05=Default
Disables the dynamic shadow for Banjo and other forms.

**Comment by gonetz** [comment]
> Is this actually a bug or simply a quirk in the game's rendering?

It is not a bug. Graphics hidden by aux buffer for dynamic shadow.  You can't get rid of it without a hack or fb emulation.

**Comment by Frank-74** [comment]
Ok, thanks for info.  Not an issue so closing.
