### ISSUE TITLE
Winback - Various minor graphical issues

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1322]
OS: `Slackware64-current`
`mupen64plus-2016.11.27_3ca2c4a-x86_64-1_git`
`GLideN64-2016.12.28_485f230_master-x86_64-1_git`

I am noticing several minor issues with the game Winback, the reason I am grouping these together is because none of them occur with GLupeN64. Maybe @loganmc10 might have an idea where the differences exist? They do occur in @loganmc10 's GLideN64-vbo branch though.

1. There is a white border around the screen during cutscenes and gameplay.
2. Aiming your weapon causes a red trail to follow.
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/2017-01-09-093110_1680x1050_scrot.png)
3. Laser trip wires render at the incorrect location and will move as the player does.
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/2017-01-09-093622_1680x1050_scrot.png)

Here is an apitrace showing all 3 issues.

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/mupen64plus/mupen64plus_gliden64_winback.trace.xz
Apitrace log - http://pastebin.com/j2bEVt5Y

**Comment by loganmc10** [comment]
The border might be because auto-crop is on my default with GLupeN64.

You can try setting ```CropMode = 1``` in mupen64plus.cfg

Those other 2 seem like some kind of noise emulation bug.

You could try GLupeN64 from commit d96cee6206e65d802ca01044722c931973f484f6 and see if it acts the same as upstream GLideN64.  That commit is before the auto-cropping change and some changes to noise emulation.

**Comment by orbea** [comment]
The white border is indeed resolved with `CropMode = 1`. I also tried commit d96cee6206e65d802ca01044722c931973f484f6 from GLupeN64 and still found none of these issues...

**Comment by loganmc10** [comment]
huh, maybe it's because of the whole compatibility OpenGL profile business.

GLideN64 uses a PBO (GL_PIXEL_UNPACK_BUFFER) to upload the texture for noise emulation. I've seen some issues with that, and I believe it's probably why this issue occurs: https://github.com/gonetz/GLideN64/issues/1117. Some devices seem to have an issue with PBO texture uploads. @fzurita could verify if that issue (#1117) exists with GLupeN64 on Android.

In GLupeN64, it generates 30 random noise textures at startup, and then randomly cycles through them, instead of randomly generating a new texture each frame. This also fixes some performance issues like this: https://github.com/gonetz/GLideN64/issues/710

**Comment by fzurita** [comment]
I can't verify https://github.com/gonetz/GLideN64/issues/1117 is fixed with GLupeN64 because it wasn't my device that had the issue. 

Although, I agree, I like your method of uploading noise textures better.

**Comment by orbea** [comment]
Neither the 2nd or 3rd issue occur with the llvmpipe, so their seems to be a driver component involved

**Comment by loganmc10** [comment]
I'm guessing it has to do with that compatibility profile override stuff you have to do to get GLideN64 working with mesa, but that's just a wild guess

**Comment by orbea** [comment]
It also occurs with your GLideN64-vbo branch which does not require that unless there is some details I'm failing to understand.

Could the difference be mupen64plus vs. RetroArch?

**Comment by loganmc10** [comment]
The only difference there is some of the audio and input code to get it to work with RetroArch, it's pretty minor stuff.

The only real difference I could think of might be the way they are compiled? Like the -O flags and whatnot. For instance I use -O2 in glupen64 because I ran into some graphical bugs on some platforms using O3, so you could try playing with that stuff or compiling a debug build

**Comment by orbea** [comment]
Doesn't seem to be optimizations either, I already compile GLideN64 with -O2 and a debug build with -O0 still does it.

I guess it could be configuration.

**Comment by orbea** [comment]
One more detail is that in issue 3 the laser trip wire will look correct from a distance and only breaks when approached.

**Comment by orbea** [comment]
I can no longer reproduce this issue so I am going to consider it fixed until it can be reproduced again.
