### ISSUE TITLE
Legend of Zelda - Ocarina of Time : "Render N64 frame buffer to output" problem

### ISSUE THREAD

**Issue by CharlesCorrin** [gonetz/GLideN64#1329]
Game: The Legend of Zelda - Ocarina of Time

Problem: When "Render N64 frame buffer to output" is enabled, the game displays only a gray screen.

My system: Windows 10 64-bit.

GlideN64: Using latest WIP build (December 22nd) from the WIP builds page on this Github.

**Comment by Fanatic-64** [comment]
It's probably due to the Subscreen Delay Fix hack.

**Comment by retrobenny** [comment]
That hack should be replaced by the Debug ROM's port of it {I made for v1.0 (U) } as it takes another route at fixing it and stops the crashes on lagless tweaks.
It just needs the fix for all other versions of the game as well,there's a lot of variants,too much for me to handle in a decent time.

Subscreen Fix
D01C7021 0002
801DA5CB 0002
D01C7021 0002
801C7021 0003

Lagfix
80007CE2 000D
Game crashes when pausing if above delay fix code is not used.

**Comment by Fanatic-64** [comment]
No no, it's not because of the GameShark fix, it's because of a hack built into the plugin which writes the framebuffer with a blank image to eliminate the delay. The only way to disable it is to reprogram the plugin's framebuffer emulation for Zelda, which requires some OpenGL and C programming skills, if you can't convince Gonetz to do it.

**Comment by gonetz** [comment]
Do not use "Render N64 frame buffer to output" for Legend of Zelda - Ocarina of Time.
The game uses a hack to fix subscreen delay. That hack fills color buffer in RDRAM with solid white. No point to render it to output buffer.
