### ISSUE TITLE
Too many vertex attributes for the Raspberry Pi

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1399]
@gonetz the refactoring has left things broken on the Raspberry Pi.

Unfortunately GL_MAX_VERTEX_ATTRIBS on the Rasbperry Pi is 8. This means that ```rectAttrib::texcoord0``` and ```rectAttrib::texcoord1``` are out of bounds on the Raspberry Pi.

I haven't spent too much time looking into possible solutions since it's getting late here, just posting my findings for now.

**Comment by gonetz** [comment]
Number of attributes was increased to optimize VAO/VBO usage.
I guess, RPI does not use buffered drawer.

**Comment by loganmc10** [comment]
No it's GLES2 only and doesn't support VAO's

**Comment by loganmc10** [comment]
So I believe this can be fixed by changing rectAttrib to:

```
namespace rectAttrib {
    const GLuint position = 1U;
    const GLuint color = 6U;
    const GLuint texcoord0 = 3U;
    const GLuint texcoord1 = 7U;
}
```
This way, position and texcoord0 are shared with triangleAttrib.

The patch looks like this:
https://github.com/loganmc10/GLideN64/commit/db906f07dbea7f26d23d6176f37d5079b8cc08d5

Does that seem like an acceptable solution?

**Comment by fzurita** [comment]
We should get away from using ifdefs. A runtime check if probably better, also would it make more sense to do or for all GLES 2.0 devices?

**Comment by loganmc10** [comment]
I'll make it a run-time check (in GLinfo) that checks if GL_MAX_VERTEX_ATTRIBS is 8 or less, which is probably the most correct way to solve this problem.

**Comment by loganmc10** [comment]
@gonetz the final problem with the Raspberry Pi is DepthBufferToRDRAM. In the old code, DepthBufferToRDRAM::init() was wrapped inside ```#ifndef GLES2```. In the refactoring it is always enabled.

It doesn't work because it tries to attach a texture to the depth buffer (https://github.com/loganmc10/GLideN64/blob/pi/src/BufferCopy/DepthBufferToRDRAM.cpp#L90-L112), which is the reason renderbuffers had to be used on the Raspberry Pi (it doesn't support OES_depth_texture).

So it should either be disabled for GLES2, or if the depth texture is the only issue, then it should check for ```Utils::isExtensionSupported(m_glinfo, "GL_OES_depth_texture")```, or somehow be converted to a renderbuffer instead of a texture.

**Comment by gonetz** [comment]
@loganmc10 You are too fast. I did not have a chance to think the problem out, and you already suggest a solution :)

I see another way to solve the problem. GL_MAX_VERTEX_ATTRIBS on the Rasbperry Pi is 8.
GLideN64 currently uses 9 vertex attributes. Actually, only 7 are actually necessary:
* rectAttrib::color can be replaced by uniform, because  color is not vertex attribute in case of rects. Color is property of whole rect.
* triangleAttrib::numlights also can be replaced by uniform. It is less obvious case. Num of lights is property of SPVertex, which is set on vertex load. I made it as vertex property because number of lights theoretically can change after vertex load. However, that number must be the same for all vertices passed to draw command.

So, I can do quick fix by replacing rectAttrib::color with an uniform. This should fix the problem with attributes, right?

**Comment by loganmc10** [comment]
Yes that would fix it, but would both need to be replaced, the max index must be less than 8

> GL_INVALID_VALUE is generated if index is greater than or equal to GL_MAX_VERTEX_ATTRIBS.

**Comment by gonetz** [comment]
@loganmc10 
>  the final problem with the Raspberry Pi is DepthBufferToRDRAM

It is easy to fix.
gfxContext.createPixelReadBuffer returns nullptr in case of GLES2.
It can be checked at the begining of DepthBufferToRDRAM::init().
I'll do it.

> Yes that would fix it, but would both need to be replaced, the max index must be less than 8

Is attribute index 0 allowed?

**Comment by loganmc10** [comment]
> Is attribute index 0 allowed?

Yes everything I read says it can be used, so starting from 0 and getting rid of 1 should solve the problem.

**Comment by gonetz** [comment]
Ok. I'll do it

**Comment by gonetz** [comment]
@loganmc10 Done. Please test on Rasbperry Pi.

**Comment by loganmc10** [comment]
Yep no more GL errors, thanks! There are still depth issues with Framebuffer Emulation, but that same issue existed before the refactoring.
