### ISSUE TITLE
Native resolution factor seems broken

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1404]
Native resolution factor seems broken, at least in Android. This used to work fine before the refactor. My screen resolution is 640x480.

**1x**
![super_mario_64-002](https://cloud.githubusercontent.com/assets/11581687/23493842/d09c430e-fedc-11e6-8ef2-987bfbcf7934.png)

**2x**
![super_mario_64-000](https://cloud.githubusercontent.com/assets/11581687/23493846/d95852bc-fedc-11e6-9257-5d4c4a18cb71.png)

**3x**
![super_mario_64-001](https://cloud.githubusercontent.com/assets/11581687/23493851/e4d076ec-fedc-11e6-9b37-76cff265db13.png)

**Comment by loganmc10** [comment]
I can confirm the same thing on mupen64plus in Windows. Interestingly, having "Show VI/s" enabled seems to fix the problem for me.

**Comment by fzurita** [comment]
Hmm... I haven't done a bisect yet to see if it ever worked after the refactor, but I wonder if it's related to this commit: 873a830d88205c4444b031b36c99dc3c1aff9d6d

**Comment by loganmc10** [comment]
No the problem is much older than that, I tried c1bba2afe662d71ca274fd4453042f98ba6a5397 (Feb 5) and the problem existed then. But even back then, turning on "Show VI/s" fixes the problem, even though the VI/s isn't shown on the screen (I don't think it was refactored yet)

**Comment by retrobenny** [comment]
I always keep fps showing on Android,but still ending up with this issue.
Tried the latest FZ edition update and resolution is indeed a little borked on my end.
With scaling set to off or 4X,the screen on Banjo-Tooie jumps closer and cuts off the screen at random points (quite jarring) and resolution can get more rastery looking even though I have it at 1080P always and off/4x are the most crisp options.

This was with a fresh profile made disabling legacy mode to test it,knowing it was likely still sluggish from CPU bottlenecking.
Also not sure if Shield TV is still utilizing Full GL functions or not and I have yet to test the slingshot depth to see whether it is or not.
I remember non-FullGL options had texture issues when using enhancements or something else causing that,with the Rare logo getting a black outline instead of keeping the gold color.
This is why I assumed FullGL may be failing to work,its not shaders because I disabled storage to avoid that kind of circumstance.

**Comment by retrobenny** [comment]
Can't find a working setup no matter what I tried. :(

Resolution changes with scale factor off,resolution matching scale factor like 320x240 for 1x factor (less intense but still stretches to distort the view in a glitchy fashion),and a few other things or not,I forgot which due to frustration.
So I think this issue needs a name change and higher priority,or it may need some reverts until it can be fixed.

This makes me wish the long standing polygon chunks issue for regular Glide64 on Android would get fixed so it could be a more viable substitute when things get too messy with GLideN64,that missing sliver of the transport silos and other bits in Banjo-Tooie on Glide64 drives me crazy among other much worse parts missing in other games.

**Comment by fzurita** [comment]
Yeah, it's pretty bad right now. Best is to leave native resolution factor to off until fixed.

**Comment by retrobenny** [comment]
You missed the full implications,even if native resolution factor is off,it still has funky resolution issues,at least on my end much to my dismay.
That's why I made such a 💯 percent big deal out of it,not a single setup worked for making GLideN64's resolution stable on FZ Edition,the only thing I haven't tried is returning to Legacy Blending which I doubt would help,or using another render method like "Color From RDRAM" to entirely circumvent it altogether with loss of visual clarity and color count at a lower resolution.

I am avoiding the briefly released extra 5.x update,so its not new OTA-related for me.
Could part of this actually be related to Clang for some peculiar reason,what are the results on the Google device it was intended for with increased performance?

Maybe there has been a flaw in that factor setting this whole time,when its off,things are slower than they are when using 4x while 1x factor is the fastest and the lowest quality.
It would seem that it requires an option to completely disable resolution factor calculations so that it has less of a chance for screen size glitching,if that is the leading cause of these issues,guess its different on your other device/s than how its acting on my old-gen SATV.

**Comment by fzurita** [comment]
Can you elaborate on what issues you are seeing with "native resolution factor" set to off? You just say "funky resolution issues", I'm not sure what that means. Can you post a screenshot?

**Comment by retrobenny** [comment]
This is one of those instances where a screenshot may not do it justice,but I will give it a "shot" ;)

**Comment by retrobenny** [comment]
The N Logo looks a bit stretched vertically as you can see.

**Comment by loganmc10** [comment]
> I always keep fps showing on Android,but still ending up with this issue.

There is a difference between the mupen64plus-ae FPS counter and the GLideN64 FPS counter, the GLideN64 FPS counter is what fixes this.

This should be a relatively simple problem to fix, the fact that enabling the FPS counter fixes the issue tells me that glViewport needs to be called somewhere. I'm not not sure where to put that exactly, perhaps @gonetz has some idea.

**Comment by gonetz** [comment]
Fixed

**Comment by retrobenny** [comment]
Awaiting next FZ Edition update with fix to confirm on Android. :)

**Comment by fzurita** [comment]
It's fixed.
