### ISSUE TITLE
Mischief Makers: missing rock in level 4-1 & incorrect textures in 2-2, 2-8 and 2-10

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#141]
Missing rock in 4-1

![mies2](https://cloud.githubusercontent.com/assets/8987490/5056536/045bff3c-6c8a-11e4-881f-e5b1e878d145.jpg)

Incorrect textures in levels 2. glide64 has a hack here for that I think but it would be better to have a real support

![mies1](https://cloud.githubusercontent.com/assets/8987490/5056540/17096034-6c8a-11e4-85af-66daff6f5b5d.jpg)

**Comment by thecoreyburton** [comment]
I thought I'd check up and both these issues still remain - but one you unintentionally captured has been fixed it looks like! If you look at the screenshot of world 4, the lighting colors are sorta inverted (it should be dark on the outside, and light on the inside). This is not present on the release candidate, but the missing rock in world 4 and the missing rocks in the intro, along with the stretched textures are still an issue.

**Comment by felixthecat1970** [comment]
hello, also  japanese version have this bugs, and intro is missing 3d graphics like this
![yytm](https://cloud.githubusercontent.com/assets/12580269/7786658/5a473fb2-01a2-11e5-85d5-664e1a2c3b51.jpg)

but i test with RetroArch-v1.0.0.2-64-bit / Cores-v1.0.0.2-64-bit (mupen64plus 2.0-rc2 - default settings) not have this bugs run almost perfect here my log maybe help fix this bugs on glide64 2015 release. 
![print](https://cloud.githubusercontent.com/assets/12580269/7786660/5efba228-01a2-11e5-8865-199fa64a4601.jpg)

**Comment by thecoreyburton** [comment]
I think the missing 3d graphics / rocks in the intro are the same bug as the missing rock in world 4-1.

**Comment by thecoreyburton** [comment]
The missing intro graphics (like the rocks) are the same bug that results in no rock being present in 4-1. The incorrect textures in world 2 are an entirely different problem, as is the darkness in world 4.

Taken from TASVideos, I found this: "Nitsuja's modified plugin emulates world 2 perfectly (and makes the boulder in 4-01 visible), but seems to throw world 4 out of whack (unless something's wrong with my settings; the circle in the middle should be a ray of light, not a ray of dark.)"

Luckily the darkness issue was fixed in the GLideN64 release candidate, that leaves the original missing rocks and world 2 textures as the only problems and it seems Nitsuja had a fix for glN64 (whether it was a quick game hack or a bug fix I don't know). Is it possible it could be applied to GLideN64?

Here's the plugin, no source at the moment: http://www.mediafire.com/download.php?qm3imarkm85

Absolutely none of the credit goes to me here, I just found the information and compiled it. It may be possible to contact Nitsuja or get the source to his modified plugin.

**Comment by olivieryuyu** [comment]
rocks appears with alpha compare should happen after the 1st cycle of a two-cycle combiner " is very easy to implement. Solution looks strange though, so I put it to separate branch to test for possible regressions and fixed with 6faff6c

**Comment by olivieryuyu** [comment]
texture bugs in level 2-10 are still there :(

**Comment by olivieryuyu** [comment]
fixed :)

**Comment by gonetz** [comment]
Finally!
