### ISSUE TITLE
Regression Android: Enhancements cause buggy texture elements.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1412]
I wiped both the game config and my emulation profile and set it up anew with the usual 6xBRZ+deposterization but still get the issue again.

The simplest example is Banjo-Tooie where the Rareware logo looks odd when fading in and has a black border around it once visible.
Also the text is now becoming garbled even though 6x never had that before.
This even happened on accurate settings earlier,quite obviously a result of the rewriting,but what is causing it and what would the fix be?

Would rather not have to grab a screenshot or two,but I can go do that anyway to save the trouble of doing so later...

**Comment by retrobenny** [comment]
Some screens here,the black lining on the logo was harder to get one of.
![banjo_tooie-006](https://cloud.githubusercontent.com/assets/16418716/23812955/3993a200-05a2-11e7-93af-da2d2e6fe4e9.png)
![banjo_tooie-007](https://cloud.githubusercontent.com/assets/16418716/23812962/410494c2-05a2-11e7-8667-33289b2e42df.png)
![banjo_tooie-008](https://cloud.githubusercontent.com/assets/16418716/23812969/47b4bffe-05a2-11e7-89b4-a022f50c4a31.png)

**Comment by retrobenny** [comment]
This issue with 6xBRZ enhancements is still present in the latest update test build but without legacy blending.

" would really l"ke to see th"s "ssue f"xed. Decrypted: I would really like to see this issue fixed.

**Comment by oddMLan** [comment]
Have you tried changing the texture cache size?

**Comment by retrobenny** [comment]
Maybe 6x BRZ is a bit too extreme for a mere 128MB default,knowing that using less than 100MB causes a huge performance degradation due to cache overflowing on some spots like file select in Tooie.

**Comment by retrobenny** [comment]
Update,latest Mupen64Plus FZ Edition from Play Store still has this regression.

**Comment by GranvilleR** [comment]
At one point I remember this issue also appearing on the standalone plugin running via Project64, but that was quite a few years ago. I can't remember when it was broken or which build/commit fixed the problem. Though the same issue is also still present on the Mupen/Gliden core via Retroarch. They're still running a VERY old version of Gliden at the moment.

In the Libretro core, the glitch also occurs with other filters such as Smooth Filtering 1-4, Sharp Filtering, xBR 1-6, and the HQ and LQ filters. And if you attempt to load a high res texture pack, all other textures seem to load properly, but the textures for the i's, periods and colons do not. So that's interesting.
