### ISSUE TITLE
Super Smash Bros texture alignment issue

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1440]
The flowers have white lines under them. This seems to affect all the other plugins except Angrylion's.

![smash_brothers-001](https://cloud.githubusercontent.com/assets/10704701/24181773/fdf262d4-0f08-11e7-8c05-1e1093c45acf.png)

edit: was wrong about branch.

**Comment by theboy181** [comment]
reported this ages ago.. when can we see in master?

**Comment by gonetz** [comment]
Surely not soon. new_texrect_coords branch requires lots of polishing.

**Comment by AmbientMalice** [comment]
What happened to @standard-two-simplex anyhow? Doesn't look as though he's been on github since last year. It's a pity that branch is half-finished because it fixes a LOT of issues.

**Comment by AmbientMalice** [comment]
@theboy181@gonetz Sorry, guys, I just noticed that mupen64plus was running in LLE video mode. The new_texrect_coords branch doesn't fix this particular issue.

**Comment by standard-two-simplex** [comment]
> What happened to @standard-two-simplex anyhow? 
@AmbientMalice Nothing really. Just busy with life. I still come to check progress and discussion, but I'm not working on this atm.

Unfortunately, that branch has a big problem. It is ignoring computations done by OpenGL and doing them in Shaders in a per pixel and primitive basis, which makes it quite slow. It is noticeable in places with many texrects, like the menus in ISS 64.

I don't have the time nor the appropriate skills to write a proper implementation, so I decided to leave the task. If anyone is willing to try to write a proper implementation, I think I know the cause of most misalignments so they could contact me.

In the case of Super Smash Bros, those are triangles (if I recall correctly) and the issue is not related. At a first sight, I would say that the Z value of the triangles are incorrect, specially at the far side (near the edge of the screen). I wonder however, why the white garbage is shown instead of whatever is behind the triangles with flowers.

**Comment by theboy181** [comment]
![image](https://cloud.githubusercontent.com/assets/9299743/26065570/44abaef0-3949-11e7-9d8a-1b5440d93017.png)
I think this issue in SSB64 is related to texture cords. I dumped the texture then placed that texture into the texture folder. the texture shrank, and didn't fill the space correctly. Can someone else have a look at this ?

**Comment by theboy181** [comment]
![untitled](https://user-images.githubusercontent.com/9299743/29369681-2833efb4-8258-11e7-8d60-7a3b46db916b.png)

Can anyone think of a HLE plugin that doesnt display this bug? I'm starting to wonder if the issue is RSP related myself, but I am wondering if anyone else has had any ideas as to what is going on. At first I was thinking how it was related to texture alpha, but after using GLideN64's HD texture MOD and altering the Alpha to red on on of the flower textures, I noticed that the issue only happens with the foreground flower groups.

**Comment by loganmc10** [comment]
The white line is still there after https://github.com/gonetz/GLideN64/commit/21e7cae6aa4fe0834681e0fd8ff367b8674ad915
