### ISSUE TITLE
Running OpenGL API calls on a separate thread?

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1441]
@gonetz I was thinking of a possible optimization. We could have a separate thread running all the OpenGL API calls. This way, for devices that can't run the plugin at the full rate, they device can just queue up all the API calls and then move on back to the core more quickly. The separate thread would handle the API calls, while the primary thread will be able to get back to the core more quickly.

The only downside I see is where we need some return value from the API call, for example, if we were to perform a glReadPixesl calls for copying the framebuffer from the GPU to the N64 RDRAM, the plugin has to wait for the result before being able to proceed with follow up API calls. If we use the software depth buffer for this, then it shouldn't be an issue. For the color buffer, it could get more complicated though.

Another downside is that if the API calls fall too far behind to the point that we can't keep the full rate, input lag will be introduced, maybe we can drop frames?

**Comment by gonetz** [comment]
CommonAPIImpl_common.cpp already implements running plugin's API calls in separate thread. It does not speedup emulator's work: when ProcessDList or ProcessRDPList called, emulator waits for gDPFullSync(), which set MI_INTR_DP flag and calls CheckInterrupts() callback.
May be I miss something, but I don't understand how that idea can improve performance.

**Comment by fzurita** [comment]
Hmmm... I see that now. I think I understand why your thread has to wait. You are doing the whole ProcessDList or ProcessRDPList in a thread.

I was thinking something different, like having a queue of raw OpenGL API commands that are performed by the separate thread.

**Comment by loganmc10** [comment]
Most of the OpenGL API calls return immediately. The commands get queued up by the GPU to be executed. The only time a GL API call will wait/take some time is if data needs to be transferred (glTexSubImage) or it causes some kind of synchronization (glFinish, glMapBufferRange in certain circumstances, glReadPixels without a PBO, etc).

I'm not sure if I understand how this would work though. The graphics plugin needs to get a "todo list" from the emulator core (I assume this happens via Process*List), it then renders the graphics, but the emulator core can't send the graphics plugin the next "todo list" until the first one is finished, so I don't understand how a thread would allow execution to happen any faster.

**Comment by fzurita** [comment]
Based on the profiling I have done, we are spending a very significant amount of time on API calls even for those that should return immediately. The driver seems to be blocking in instances where it has to transfer data to the GPU, even though it could copy the data and run it in the background to allow the caller to continue.

The thread would allow the plugin to say he is done more quickly even though all he did was queue up a bunch of commands for the GPU. I'm going to try it out just for the challenge, even though it may not necessarily result in a performance benefit.

**Comment by loganmc10** [comment]
> I'm going to try it out just for the challenge, even though it may not necessarily result in a performance benefit.

That's always the best reason to do it :)

I played around with PBO's for texture uploads when I was working on glupen64, because I also noticed that calls like glTexSubImage2D would block. If a PBO is bound when glTexSubImage2D is called it's not supposed to block at all, since it is just pointing to a buffer that should already have the data loaded. I never got ant better performance out of it. But perhaps there is an opportunity to load the texture into the PBO in a thread and then just call glTexSubImage2D and point to it, something like that.

**Comment by gonetz** [comment]
Keep in mind, that all calls to OpenGL API must be done from the the thread, where GL context was created. I made that rspthread only because older PJ64 versions call plugin init from one thread and plugin close from other thread. Attempt to call GL API from another thread to free GL resources caused application crash.

**Comment by loganmc10** [comment]
Well you can have a GL context for each thread and share data between contexts, but it probably gets complex, I've never done anything like that. But I think fzurita was thinking of doing all the GL calls in a dedicated thread.

**Comment by fzurita** [comment]
For EGL context at least, I can move the context to another thread, see here:

http://stackoverflow.com/questions/11726650/egl-can-context-be-shared-between-threads

I'm not sure how this can be done in windows or raspberry pi, but any Linux OS with EGL should allow it.

**Comment by fzurita** [comment]
Also, I can just call ```CoreVideo_SetVideoMode``` from the thread that is handling the OpenGL API instead of ```DisplayWindowMupen64plus::_start()```

**Comment by dankcushions** [comment]
@fzurita
re: pi. looks like it should be possible: https://www.raspberrypi.org/forums/viewtopic.php?&t=14750
(if i understand correctly!)

**Comment by loganmc10** [comment]
Yes you can move the context that way but you'll want to do some research into the performance impacts of *glMakeCurrent

**Comment by mudlord** [comment]
Sounds like this is a chance for thread local variables for storing the current OpenGL context.

**Comment by fzurita** [comment]
Maybe I'm just being dense here. What would it achieve to use thread local storage for storing the current OpenGL context information? As far as I know, it would just prevent other threads from accessing information related to the context in the current thread.

**Comment by mudlord** [comment]
https://en.wikipedia.org/wiki/Thread-local_storage
Yes, you are being dense as fuck. However it is far from ideal.

**Comment by fzurita** [comment]
Thanks, I know what thread local storage is, I was just wondering how it would help...

**Comment by fzurita** [comment]
Here is the on-going implementation if anyone is curious of my approach:

https://github.com/fzurita/mupen64plus-ae/commits/gliden64_threaded_rsp

Also, as I'm doing this, I'm finding a few OpenGL API calls that we are making that require the OpenGL driver implementation to sync the command queue back to the client. For example glError and glCheckFramebufferStatus.

Also, there a few commands that require a return value like glGen* commands, but I should be able to move those to the front of my command queue since order is not important there.

**Comment by i30817** [comment]
This might be misleading for C++, because it's a Java comparasion based purely on naming, but i'm still going to put in my 2cents.

ThreadLocals in java wouldn't solve synchronization problems of the same objects, because they are meant to *create* new variables per thread, not a shared resource. So each thread has its own instance, and therefore declaring any object threadlocal means the first time it is accessed on a thread, lazy initialization happens.

Therefore you'd have two opengl context if you tried to use it to dodge actual offloading and they both would probably be somewhat misconfigured if you mistakenly partly-configured the variable on both threads.
As well as probably having 'interesting' performance issues, no doubt. I dunno, i'm speaking as the lowest of the low who hasn't ever done C++ or Opengl programming here.

**Comment by fzurita** [comment]
@i30817 Right, potentially, I don't think I'm going to need this in my implementation.

@gonetz In here: https://github.com/gonetz/GLideN64/blob/master/src/BufferCopy/RDRAMtoColorBuffer.cpp#L279

Should this be happening of RDRAM to color buffer is disabled?

**Comment by gonetz** [comment]
@fzurita Not sure that I understand the question. RDRAM buffer still can be copied when RDRAM to color buffer option is disabled. It is necessary when game switches to CPU rendering to color buffer (CFB mode).

**Comment by fzurita** [comment]
Thanks, that answered it.

**Comment by i30817** [comment]
One approach to remove the need for mutual exclusion in GUIs is 'post' commands from other threads into a queue in order to be 'eventually consistent'. It's a pain to make sure to get results back, if any (ie: the swingworker pattern in java) and it's annoying to not be certain when the command will actually activate (this can be super annoying because you might have to 'queue' more events on the GUI thread if your subsequent code depends on something happening to the GUI) but not it's not impossible.

Another approach is to make a state machine where the parts where thread contention can happen use a synchronized interface (say a synchronized wrapper object) and you 'prove' that contention can't happen on the next state, but that sounds super complicated and inflexible.

**Comment by fzurita** [comment]
I have a working implemention using a thread and a blocking queue of GL commands, see my pull request. Right now, I have to empty my queue for GL commands that must return something. 

Luckily,  a lot of the commands that must return can be executed out of order, so they can be sent to the front of the queue. I haven't done this yet.

For commands that do return and are order dependent, I have to block until the command is executed. I believe I can replace these commands though.

**Comment by i30817** [comment]
You're well underway then. The only thing i can think to suggest is a debug check on the opengl wrapper you're using to check out that the current thread is actually the 'opengl worker thread' to make sure there are no threading errors. 
That sort of stuff preventive prevented hundreds of thousands of errors over time on java.

**Comment by fzurita** [comment]
I'm going to go ahead and close this since there is a working implementation in https://github.com/gonetz/GLideN64/pull/1452.
