### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1443]
I haven't had time to determine what is leaking, but something is. Here is a save state for conker's bad Fur day:
[starting area.zip](https://github.com/gonetz/GLideN64/files/869334/starting.area.zip)

Jump in the water that Conker is facing above the water fall. Keep on jumping there for like a minute. Frame rate of the game should go down significantly. If you exit the game and come back, frame rate all go back to normal.

**Comment by loganmc10** [comment]
Have you tried increasing the size of the texture cache? It's possible that that area in the game is generating a ton of textures (some games seem to generate non-stop unique textures somehow). It's possible that the texture cache is getting full, and so it has to delete a texture every time to add the new one.

I've ran into stuff like this a number of times in the past:
https://github.com/gonetz/GLideN64/issues/1015
https://github.com/gonetz/GLideN64/pull/1126
https://github.com/gonetz/GLideN64/issues/795
https://github.com/gonetz/GLideN64/issues/997

I suspect it might have something to do with that.

**Comment by loganmc10** [comment]
Increasing the size of the texture cache obviously isn't a permanent solution, but if you double the size of the texture cache, and the problem takes twice as long to manifest itself, then you've got a pretty good indicator where the problem is.

**Comment by fzurita** [comment]
Good idea, I'll give that a shot.

**Comment by fzurita** [comment]
I gave it 800Mbytes of cache, it didn't seem to help.

**Comment by gonetz** [comment]
> starting area.zip

I can't load that state, emulator crashes. Could you post a screen shot from where the problem happens?

**Comment by fzurita** [comment]
Ok, right here:

![conker_bfd-001](https://cloud.githubusercontent.com/assets/11581687/24401842/013a765a-1384-11e7-9194-078a2324fa82.png)

**Comment by loganmc10** [comment]
I've got to assume it has something to do with the texture cache, there aren't really many other things that get generated. I know that Mario Tennis seems to generate endless FBO's though, but I checked Conkers and that doesn't seem to be the case.

Conkers does (like many other games) generate a seemingly endless number of textures though. There are probably ways to optimize the texture cache, for instance, maybe we don't cache small textures at all? Maybe the overhead isn't worth it. Or if there was some way to identify these "one time use" textures that get generated in these games, and don't add them to the cache, that would probably also help.

**Comment by loganmc10** [comment]
By the way, this would be an instance where some kind of threaded system could probably help. If you don't add small textures to the cache, or you don't add "one time use" textures, you still need to upload them to GPU memory and then delete them after use.

The deleting could happen any time, so you could delete the textures in a separate thread (whether it's one by one or whether you batch them, at least it's in its own thread)

**Comment by rcaridade145** [comment]
Would something like this be solved with the a better fbinfo implementation from the main emulator?
If a write is detected to a certain memory region we could invalidate all the textures with data from that region no? @fzurita @loganmc10

**Comment by fzurita** [comment]
FB info only applies to letting the video plugin know of reads from RDRAM.

**Comment by rcaridade145** [comment]
On issue #808 there is reference to writing endpoints to the API. 

/******************************************************************
Function: FrameBufferWriteList
Purpose: This function is called to notify the dll that the
frame buffer has been modified by CPU at the given address.
input: FrameBufferModifyEntry plist
size = size of the plist, max = 1024
output: none
******************************************************************/
EXPORT void CALL FBWList(FrameBufferModifyEntry *plist, wxUint32 size)

/******************************************************************
Function: FrameBufferWrite
Purpose: This function is called to notify the dll that the
frame buffer has been modified by CPU at the given address.
input: addr rdram address
val val
size 1 = wxUint8, 2 = wxUint16, 4 = wxUint32
output: none
*******************************************************************/
EXPORT void CALL FBWrite(wxUint32 addr, wxUint32 size)

This was what got me that idea.

**Comment by fzurita** [comment]
Hmm, I was unaware of those. I guess I hadn't looked closely enough at the API. I guess it could be possible if we could determine when texture are no longer being used by those calls. In think it would still be hard though. I don't see how the emulator would know when a texture is no longer being used by a game.

**Comment by rcaridade145** [comment]
> I don't see how the emulator would know when a texture is no longer being used by a game.

The idea is not no longer being used, but being updated. If you create a new texture every time an area is updated and therefore has a different CRC you are going to have huge memory comsumption. If you can reduce that to something like 

- Create texture 
- Memory is updated
- Check if we have a texture mapped with that region , and if so delete it
- Create texture based on new data.

**Comment by loganmc10** [comment]
Cached Textures have an attribute called "address", which is set like this:

```
pCurrent->address = gDP.loadInfo[pTile->tmem].texAddress;
```

is what you mean by "region"/"area"?

The texture cache works like this:
GLideN64 calculates the CRC of the "incoming" texture. Then it scans through the texture cache list looking for a matching CRC. If it finds one it uses that of course, it also then moves that CRC to the beginning of the texture cache list.

If it doesn't find one, it adds the new texture to the beginning of the CRC list, if it needs to, it will delete the texture at the end of the list to make room.

So the most recently used texture will be at the beginning of the list, the least recently used texture will be at the end.

It might be worthwhile to play around with this line:
https://github.com/gonetz/GLideN64/blob/master/src/Textures.cpp#L557 (maxCacheSize)

I suspect that even 16384 is too large. I doubt many games will actually have 16000 textures that get repeated, but I will check in Conkers how many textures actually get used more than once. I'm guessing a number around 4000 might be more reasonable, and would allow GLideN64 to scan the texture cache faster.

**Comment by rcaridade145** [comment]
> is what you mean by "region"/"area"?

Yes. 
On this line https://github.com/gonetz/GLideN64/blob/master/src/Textures.cpp#L1381 we know the extent of the area occupied by the texture. If by framebuffer info we knew that area had been written to it would save us the CRC and we could invalidate the texture.  Don't know if a hash based structure with address as input would serve the same purpose (in this case we would still need the CRC). Coupling this with #1441 would be nice :)

**Comment by loganmc10** [comment]
So, after using @fzurita's save state and jumping around for a minute or two, here are my results:

- 169360 CRC's calculated
- 7396 unique CRC's

That's actually not bad, I thought the unique CRC's would be much higher.

Of those 7396 unique CRC's:

- 5171 of them were used only once.
- 1354 of them were used twice
- 224 of them were used 3 times
- 282 of them were used 4 times
- 102 of them were used 5 times
- 30 of them were used 6 times
- 20 of them were used 7 times
- 10 of them were used 8 times

The remaining 200 or so were used quite frequently, with the highest number being textures that are re-used around 5000 times.

So as you can see, even though 7396 textures made it into the cache, only about 2200 really benefited from being in a cache, with the remainder being used only once.

If the texture cache was smaller (right now it holds 16384 textures maximum), let's say it held 4000 textures, then those 2200 frequently used textures would be at the front of the cache, and the less frequently used textures would be at the back, getting popped off once the cache hit 4000.

**Comment by fzurita** [comment]
Were you jumping in the water? Maybe it's not a texture cache issue.

**Comment by loganmc10** [comment]
Yeah I was jumping around in the water, it may not be a texture cache thing, but I don't know what other OpenGL resources would be causing a problem. If the problem is unrelated to OpenGL then someone would have to run it through some kind of code analysis program like valgrind to see if there is a memory leak of some kind.

**Comment by fzurita** [comment]
Did you experience the slow down as well while jumping in the water?

**Comment by loganmc10** [comment]
@rcaridade145 how exactly do you want me to correlate the data? The addresses are repeated much more frequently, with one address being re-used over 20,000 times, only 38 addresses were used only once (I didn't run it quite as long this time, so we are dealing with around 127000 textures this time, not 169000).

@fzurita No I don't experience any slowdown, but this is on a desktop with lots of RAM and a dedicated GPU, etc.. so it might take much longer to trigger a problem than a mobile device.

**Comment by rcaridade145** [comment]
@loganmc10 I believe it would be useful to see the overlap 
 address ; address + size for each texture ; CRC val

So that would give us how many textures are being created  with the same base address but with a different CRC.

**Comment by fzurita** [comment]
That's a good point, you wouldn't even need the FB info API to do this. Just look for overlap in memory when new textures are generated. Then any textures that overlap could be deleted.

Is this ok though, what if game continuously overwrites the same spot in memory, but it's using the same textures, just at slightly different spots in memory?

**Comment by rcaridade145** [comment]
> Is this ok though, what if game continuously overwrites the same spot in memory, but it's using the same textures, just at slightly different spots in memory?

Well you would still have the CRC value.

**Comment by fzurita** [comment]
We should probably try to figure out the cut off point. At how many items does it take longer to search a list of CRCs versus just uploading the texture to the GPU. I suspect this number will be different depending on how fast a CPU one has.

Maybe the right answer would be to make this number configurable.

**Comment by loganmc10** [comment]
@rcaridade145 So in a sample size of 75000 CRC'c calculated, 3665 unique CRC's:

There are 53 addresses that contain more than 1 unique CRC, with 185 unique addresses.

**Comment by loganmc10** [comment]
@fzurita You could also do it based on the textures size, like if the texture is less than 1KB, don't bother trying to cache it, something like that.

Also, right now the CRC is calculated based on the entire contents of the texture. I know that Dolphin just does something like: take a CRC of the first KB, then a CRC of a KB in the middle of the texture, then a CRC of a KB from the end, and combine them, in order to reduce the time spent calculating the CRC's. Of course that would need extensive testing, since it could lead to inaccuracies. Also, their textures are probably much larger, but there are probably all kinds of optimizations like that that might be possible.

**Comment by AmbientMalice** [comment]
The N64 has a 4KB texture limit, so that's probably not going to yield massive gains.

**Comment by loganmc10** [comment]
Well the texture that actually gets uploaded to the GPU can be larger than that, the majority of the textures I see in Conkers are 4KB, but there are 8KB and 16KB textures, but I agree that since they are so small, chopping up the CRC calculation probably won't lead to huge performance gains

**Comment by rcaridade145** [comment]
> @rcaridade145 So in a sample size of 75000 CRC'c calculated, 3665 unique CRC's:

There are 53 addresses that contain more than 1 unique CRC, with 185 unique addresses.

So there are 3665 unique CRC (textures) being generated having 185 unique indexes on ram?

**Comment by loganmc10** [comment]
Right, because those textures are reusing those 53 addresses

**Comment by rcaridade145** [comment]
> Right, because those textures are reusing those 53 addresses
So the cache should have 185 textures and not 3665 right?

**Comment by loganmc10** [comment]
So here is the important thing to note: Right now, if I jump around in the water in Conkers for exactly a minute, I get 4169 texture cache misses, (tracked by ```m_misses``` in Textures.cpp). So that's how many times it scanned through the whole list of textures and found nothing useful.

If I change ```maxCacheSize``` to 4000, I get the same number of misses, since there are only roughly 3600 useful CRC's in there (textures that get used more than once).

**Comment by loganmc10** [comment]
> So the cache should have 185 textures and not 3665 right?

No, there are 3665 textures that have unique CRC's, but they are only 185 unique addresses, it just means that different textures are using the same address space one after another

**Comment by rcaridade145** [comment]
> No, there are 3665 textures that have unique CRC's, but they are only 185 unique addresses, it just means that different textures are using the same address space one after another

If they reuse the same address space they are invalidating the one's that were created on that location before right?

**Comment by loganmc10** [comment]
> If they reuse the same address space they are invalidating the one's that were created on that location before right?

Yes I would assume so.

Here is another test: Beetle Adventure Racing also generates a ton of one-off use textures. If I do a full lap with the default texture cache size (16384), I get 13581 misses.

With a texture cache size of 4000, I get.... 13568 misses (which for the purpose of the test is identical since there is some variations in my driving...)

My point is, I don't think there is any use of having a texture cache that large, it will just increase the time spent comparing CRC's. I think a size of 4000 (which I believe is what Glide64 uses, but I could be mistaken) would be much more practical. I don't know if it would solve this problem, but I believe it would improve performance.

**Comment by fzurita** [comment]
So I think the problem in CBFD is related to texture cache size. I reduced my texture cache to 50MB and it actually increased performance in the game rather than reducing it.

**Comment by loganmc10** [comment]
@fzurita then that kind of validates my point. I think the texture cache is too large, and it is spending useless time comparing CRC's.

I think reducing the cache size to 4000 textures would help. If there was some way of identifying textures that probably won't be used in the cache before the CRC is calculated (using the address or some other method), that would improve performance even more, since we wouldn't have to calculate CRC or scan the CRC list

**Comment by fzurita** [comment]
A lot of the time, background textures seem to be used only once. Maybe we shouldn't cache those at all.

**Comment by fzurita** [comment]
@gizmo98 I just stumbled upon this:

https://lists.linaro.org/pipermail/linaro-toolchain/2013-April/003282.html

It's a CRC calculation using neon. Do you think you could implement it for the CRC calculation for textures?

It would be another implementation of this:

**Comment by gizmo98** [comment]
This neon implementation looks complicated. It would be easier to add SSE4.2 crc32**c** intrinsics in the first place. The syntax of armv8 crc intrinsics and sse4.2 crc32**c** intrinsics look almost identical.

unsigned int _mm_crc32_u8 (unsigned int crc, unsigned char v)
unsigned int _mm_crc32_u16 (unsigned int crc, unsigned short v)
unsigned int _mm_crc32_u32 (unsigned int crc, unsigned int v)
unsigned __int64 _mm_crc32_u64 (unsigned __int64 crc, unsigned __int64 v)

**Comment by fzurita** [comment]
Right, it does look complicated. Unfortunately, we can't use SSE4.2 intrinsics in older ARM CPUs. I was hoping you would be interested since you had been doing a lot of NEON optimizations lately.

**Comment by loganmc10** [comment]
Just keep in mind that if you switch from crc32 to crc32c, someone will have to recalculate the CRC's for the microcodes (https://github.com/gonetz/GLideN64/blob/master/src/GBI.cpp#L40-L61), since those were calculated from CRC32.

Or you could use crc32c for the textures and use CRC32 inside ```CRC_Calculate_Strict()```, which is used for the microcodes

**Comment by gizmo98** [comment]
I can take a look. But it will not have the highest prio. I have not seen any neon implementation in the past which was really faster. Normal implementations use a lookup table. This neon example does something else.

**Comment by fzurita** [comment]
I could probably port that implementation over as well to see if it does provide any improvements. I was just busy with the threading API implementation which is taking me a lot longer than I thought it would take.

**Comment by gizmo98** [comment]
How hard is it to use linux kernel crypto API? There is neon optimized code:
https://patchwork.kernel.org/patch/9448535/

http://www.chronox.de/libkcapi.html
http://stackoverflow.com/questions/6111882/how-to-use-kernel-libcrc32cor-same-functions-in-userspace-programmes

**Comment by gonetz** [comment]
> I think reducing the cache size to 4000 textures would help.

It is quite likely. Some statistics wont hurt though. We can estimate how many unique textures are used on level of some texture intensive game as Zelda MM or Conker BFD. For example, start some dungeon in Zelda with clear texture cache, complete it and check cache size.

> If there was some way of identifying textures that probably won't be used in the cache before the CRC is calculated (using the address or some other method)

I don't know such method.

It would be great to emulate N64 texturing on GPU level. That is load 4kb of TMEM to GPU memory and write fetching shaders to load texels right from TMEM. No need of texture cache, most of texture errors would gone. However, this is real challenge.

> A lot of the time, background textures seem to be used only once (Yoshi's story). Maybe we shouldn't cache those at all.

No hurt to have them in cache. If texture is not used, it will be eventually pushed out of cache.

**Comment by fzurita** [comment]
How about making the maximum number of cached textures configurable?

**Comment by loganmc10** [comment]
> How about making the maximum number of cached textures configurable?

I'm personally not a big fan of options like that where the user won't really know what the outcome of their choice will be.

I think with some testing we would be able to find an optimal number. There is no difference user to user in this case, the optimal number will be the same for each user, although it could be different for different games, so you'd have to pick a number that was reasonably suited to the majority of games.

**Comment by AmbientMalice** [comment]
>I'm personally not a big fan of options like that where the user won't really know what the outcome of their choice will be.

Yea, I would be wary of users raising the max cached textures number and then complaining because it does the opposite of what they think it will do.

**Comment by fzurita** [comment]
I think it will be hard to find the right number. It's going to depend on how fast the CPU is versus memory speed. So it's going to vary based on platform.

So with a fast Intel CPU, it may be faster to search 30000 textures in cache rather than uploading to GPU. While in an ARM CPU, it may be slower to search 4000 textures in cache rather than to upload to the GPU.

**Comment by loganmc10** [comment]
I'm not so concerned about how long it takes to search the list, but whether the list has useful data at all.

If the game only has 2000 the textures that are used multiple times, those are the only textures that benefit from being in the cache, and if the cache is any bigger than that, then it's just wasted effort, no matter how fast or slow the CPU is. All the other one-time-use textures will just get pushed out the back of the cache, the sooner the better

**Comment by Gillou68310** [comment]
@fzurita one usual solution in order to speed up searching one element in a list is to use a hash table, so instead of having one big list you can split the list in multiple smaller lists. For example if you want to find a matching CRC in a list you can split the list in 256 lists and use the 1st byte of the CRC to insert and find one element in the list.

**Comment by rcaridade145** [comment]
@loganmc10 I don't see any way of  identifying the textures without the framebuffer info telling us what/where has changed.
A speed up solution would be to keep the list of addresses in a list/hash and count the number of different crc's being generated from that address, after a certain value you wouldn't care anymore and just don't cache it or CRC it.  Its like asking for a kid asking for a cookie to his/her mum after the 1000 time you just say here take the whole box.

**Comment by fzurita** [comment]
@Gillou68310  I just realized we are using a regular map for sorting or CRCs which itself contains a list. A faster chivvying to use would need a "unordered_map" (hash_map) which itself would contain a vector. I don't think lists are known for their iteration speed.

**Comment by Gillou68310** [comment]
Well I don't understand how iterator works so I can't say which solution will be faster :-(

**Comment by gonetz** [comment]
> A faster container to use would need a "unordered_map" (hash_map) which itself would contain a vector iterator. I don't think lists are known for their iteration speed.

Unordered map can be faster (find element for constant time VS log(n)). As for iterator, access time to element by iterator should be the same for vector and for list. Iteration speed is not relevant there, because no iteration happens. List is used as container because adding new element and removing any element from list is fast, which is important for textures container.

**Comment by Teklad** [comment]
Yea, vectors are really good at appending/popping off the back end.  This is mainly because they're typically stored in a linear block of memory which makes this type of access really fast.  Other types of operations cause the contents to "shift", which can be devastating for performance if the list is very large.

The only way to really get better performance at this point would be to roll your own, which could either turn out great or terrible (tldr, the STL containers are fairly well implemented for what they do).  The unordered_map might not be a bad idea to poke at though.

I came to pull the latest commits and figured I'd pop in for a moment to say hello. :)

**Comment by loganmc10** [comment]
Just another quick test:

Playing through the intro to CBFD:

Number of unique CRC's:
14200

Number that show up more than once:
3067

Number that show up more than twice:
1013

Of course some more tests could be done. I still think 4000 would be a pretty good number.

By the way, this is a fairly easy test to run, I just do a "printf" of the CRC before the ```.find(crc)``` lines in Textures.cpp (I print out the CRC value right before we search through the cache for it)

Then I just output that to a text file and use a python script to search the data:

```
d = {}

with open('out.txt') as f:
    for line in f:
        if line not in d:
            d[line] = 1
        else:
            d[line] += 1

total = 0
twoormore = 0
for key,value in d.items():
    total += 1
    if value > 1:
        twoormore += 1
print(total)
print(twoormore)
```

**Comment by gonetz** [comment]
Could you do another test: replace map by unordered_map and measure average cache item search time? That time should be constant for unordered_map. I wonder, what the constant is. If unordered_map performance does not depend on number of items in cache and it is better than ordered map performance,  we can leave cache limit as it is. unordered_map performance may depend on STL implementation. I interested in g++ results.

**Comment by loganmc10** [comment]
> Could you do another test: replace map by unordered_map and measure average cache item search time? 

Ok so I measured the time before and after ```.find(crc)``` in CBFD

With std::map:
At the beginning of my test, it was taking around 100-200 nanoseconds. By the end of my test it was taking around 2000 nanoseconds, and this wasn't a very long test.

With std::unordered_map:
At the beginning it took around 150-200 nanoseconds, by the end of my test, around 600-900 nanoseconds.

So yes, I would say that unordered_map seems much faster. Performance is still going to depend on how many items are in the cache, no matter the method used, since there are more items to search through. But it does seem that unordered_map scales better. I would still reduce the number of items in the cache, even if it was to something like 8000, I haven't seen any evidence that a larger number provides better performance.

**Comment by gonetz** [comment]
Thanks a lot! Ok, I'll switch to unordered_map and reduce cache limit.

**Comment by loganmc10** [comment]
In terms of a faster way to calculate CRC's. I've looked at xxHash in the past, I believe it is what Dolphin uses.

You can see an implementation here:
https://github.com/loganmc10/GLideN64/commit/095600192fa35846b17da311f65caf6ec90ccdb4

I averaged out the CRC calculation times for the intro to CBFD, and the current method averaged around 5000 nanoseconds per calculation, and xxHash averaged 600 nanoseconds.

The main repo is here:
https://github.com/Cyan4973/xxHash

I tested it quite a bit when working on glupen64, and I don't see any regressions, I never got it to work right with CRC_CalculatePalette, so that still uses the current method, and CRC_Calculate_Strict still uses the current method so that GBI.cpp can properly compare the ucode CRC's.

**Comment by fzurita** [comment]
Wow, that's impressive. We should give that a shot.

**Comment by loganmc10** [comment]
Intel laptop, I haven't tested arm, but I can test my Raspberry Pi sometime soon.

**Comment by Gillou68310** [comment]
> Well I don't understand how iterator works so I can't say which solution will be faster :-(

Ok I did some debugging in order to understand how this works (sorry I'm not familiar with c++). I think the idea of using a hash table is still valid but it should be applied to the map table. 

The map table could be split into 256 elements: 
```Texture_Locations m_lruTextureLocations[256];```

New elements will be inserted using the first byte of the CRC:
```m_lruTextureLocations[_crc32&0xFF].insert(std::pair<u32, Textures::iterator>(_crc32, new_iter));```

Finding textures will also be done using the first byte of the CRC:
```Texture_Locations::iterator locations_iter = m_lruTextureLocations[crc&0xFF].find(crc);```

**Comment by rcaridade145** [comment]
Why just the first byte? Usually using a 32 bit index is faster.

`m_lruTextureLocations[crc&0xFF].find(crc);`

What would Texture_Locations hold? @Gillou68310

**Comment by Gillou68310** [comment]
> Why just the first byte? Usually using a 32 bit index is faster.

Well a tab of 4294967296 elements is not really a good idea don't you think? ;-)

> What would Texture_Locations hold?

It will hold the same infos as previously.

**Comment by rcaridade145** [comment]
> Well a tab of 4294967296 elements is not really a good idea don't you think? ;-)

Lol. Really it is not,i was thinking of using the crc as the hash for the hash table and misunderstood your point.

Is this relevant https://github.com/sparsehash/sparsehash ? @Gillou68310 @loganmc10

**Comment by loganmc10** [comment]
I believe our recent swtich to ```unordered_map``` pretty much provides these exact optimizations does it not?

> Internally, the elements are not sorted in any particular order, but organized into buckets. Which bucket an element is placed into depends entirely on the hash of its key. This allows fast access to individual elements, since once the hash is computed, it refers to the exact bucket the element is placed into.

**Comment by Gillou68310** [comment]
Well I'm not sure it does, I'm not sure what they mean by "buckets". I guess the only way to be sure is to measure the time before and after .find(crc) for both solutions, like you did for map and unordered_map.

**Comment by mudlord** [comment]
Why not a standard C based hashtable, like uthash?

**Comment by jamalf** [comment]
> Well I'm not sure it does, I'm not sure what they mean by "buckets". I guess the only way to be sure is to measure the time before and after .find(crc) for both solutions, like you did for map and unordered_map.

By default std::unordered_map has a max_load_factor=1 , which means (except for key hash collisions) each bucket will have on average only 1 element. That is a good default, as it keeps us close to O(1) lookup. Depending on the system load and implementation max_load_factor may not always be honoured, but it *should* be as far as possible.

By default there will be only a handfull of buckets, and the map will be rehashed frequently as the texture cache grows, so its probably a good idea to do something like this...
// Prevent rehashing std::unordered_map during game execution, allocate all potentially used buckets upfront.
m_lruTextureLocations.reserve( MAX_TEXTURES );

> It would be great to emulate N64 texturing on GPU level. That is load 4kb of TMEM to GPU memory and write fetching shaders to load texels right from TMEM. No need of texture cache, most of texture errors would gone. However, this is real challenge.

Can you elaborate on the difficulties of this? Slight improvements in the type of hash table or the crc algorithm used for the texture cache sound insignificant by comparison.

**Comment by gonetz** [comment]
> Can you elaborate on the difficulties of this?

You may learn texture loading code in Textures.cpp and imagine all of it moved to fragment shaders. It is not impossible, just hard and very likely will be slow.

**Comment by fzurita** [comment]
I'm closing this for now since the issue has improved.
