### ISSUE TITLE
Widescreen issues with Goldeneye

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1475]
I'm getting a report of issues with Goldeneye when widescreen is enabled. Here are the provided screenshots:
![20170411_151330](https://cloud.githubusercontent.com/assets/11581687/25722513/84c53cf0-30e2-11e7-82ea-d917a88537e1.jpeg)

![20170411_151447](https://cloud.githubusercontent.com/assets/11581687/25722532/8db47646-30e2-11e7-811d-557ee103a3ca.jpeg)

**Comment by oddMLan** [comment]
The widescreen hack is just that: a hack. And it might not cover all scenarios were stuff doesnt look proper when stretching beyond what the game usually puts on screen. Goldeneye already pushed the N64 to its limits so stuff like this is usally due to optimizations (not rendering parts of what is not supposed to be on screen) and hacks like widescreen hack just expose the nature of such optimization tricks.

**Comment by fzurita** [comment]
Yep, I agree. The stuff not bring rendered is within the normal field of view though. Looks more like a depth buffer issue.

**Comment by AmbientMalice** [comment]
Additionally, there's no point using a widescreen hack for a game with native widescreen support like GE.

**Comment by fzurita** [comment]
That is true...

**Comment by olivieryuyu** [comment]
Can it be closed?

**Comment by fzurita** [comment]
Sure
