### ISSUE TITLE
FPS counter not reporting correctly

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1510]
In games like Killer instinct, Snowboard Kids 2, and Jet Force Gemini the FPS counter doesn't work. Using Glide64 Final the counter works fine. 

@gonetz you able to fix this soon ?

**Comment by Frank-74** [comment]
FPS counter is working fine with Jet Force Gemini and Killer Instinct Gold here.

![gliden64_jet_force_gemini_010](https://user-images.githubusercontent.com/11056843/27264895-a5e63cc8-5481-11e7-940f-39285c53d861.jpg)

**Comment by theboy181** [comment]
The counter works but it reports the wrong FPS. I guess I should of explained that.

**Comment by retrobenny** [comment]
It has to be in the right moments and outright happens with some games.
For JFG you have to go in-game and it shows 60 on both instead of 30fps since the DL/s (Dlists) are higher than fps and varied.
The cutscenes upon starting a new save file are done in really high Dlist rates. Other games use this heightened amount to potentially make games look smoother,especially games like V8 when on Counter Factor 1 and in a match.

One of the easiest examples is opening the map in Turok 2 where the DL/s are double the fps rate.

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
@theboy181 the fix is in master and available to test. Does FPS counter work properly now?

**Comment by theboy181** [comment]
In Killer Instinct using Glide64 Final the logo is 30fps, GLideN64 says 60 - I Think its still broken.

**Comment by AmbientMalice** [comment]
>In Killer Instinct using Glide64 Final the logo is 30fps in Glide64 Final, GLideN64 says 60 - I Think its still broken
Considering Killer Instinct is a 60fps game, what makes you think it's broken?

**Comment by gonetz** [comment]
@AmbientMalice good question. FPS counter in GLideN64 displays number of switches between color buffers, which VI shows on screen. Glide64 FPS counter shows something else, I don't remember what.

**Comment by theboy181** [comment]
I have learned to trust Glide64 fps OSD, and when you boot Killer Instinct it says 30fps - using hatcat's rdp and checking frame by frame it looks like Glide64 final reports the wrong FPS, so it looks like Gliden64 is working correctly. 

I will close this issue, thanks gonetz!
