### ISSUE TITLE
Killer Instinct Gold: Improper Projectile Effects. 

### ISSUE THREAD

**Issue by Yui12** [gonetz/GLideN64#1513]
I'm surprised that no one has yet to report this one. 

Proper Effects with Glide64 Final

![glide64_killer_instinct_gold_01](https://user-images.githubusercontent.com/13986398/27505350-7d44140a-5852-11e7-8fc1-82c5232db84f.png)

![glide64_killer_instinct_gold_02](https://user-images.githubusercontent.com/13986398/27505351-7f517788-5852-11e7-9b25-96f04d0ea006.png)

Incorrect Effects with the Latest GlideN64 master

![gliden64_killer_instinct_gold_001](https://user-images.githubusercontent.com/13986398/27505362-b104ebb6-5852-11e7-9bd9-384d11982a77.png)

![gliden64_killer_instinct_gold_000](https://user-images.githubusercontent.com/13986398/27505365-b45741ec-5852-11e7-87c9-3cf17263822b.png)

Smoke and flame effects have the same issues as well.

**Comment by oddMLan** [comment]
Tip: Alt+Prnt Scrn to capture just the emu window or just press F3 to make a screenshot in the emulator dir. All the other clutter makes your screenshots look confusing.

**Comment by Yui12** [comment]
Oh that is helpful. I was being lazy when I made those screenshots. I also forgot that project 64 can make screenshots. My mistake. I screwed up there. I already made new screenshots above.  The F3 is so much quicker.

**Comment by gonetz** [comment]
Very bad issue. Looks like programmers errors. Projectile Effects rendered with texrect command. Color of polygon defined as (PRIM _ ENV) * T1 + ENV
T1 corresponds to tile 4. Tile or tile size for tile 4 never defined. It is used once in loadblock command, thus it has non-zero tmem address and non-zero lrs coordinate. It is not loaded specially by loadtile or loadblock. Plugin loads as 163x1 texture from data, which are in TMEM. It can be some garbage. How texture mapping works in this case is also unclear. May be progress with #1603 will help to fix this issue too.

**Comment by angrylion7** [comment]
SetTile commands that write to tile 4 are called every frame (tested after the beginning of an attract mode battle), they're near the end of a DL, see the attached screenshot from z64gl debugger. And since LoadBlock commands initialize everything that SetTileSize's would normally do, it means that everything about tile 4 is deterministic. 
![kidl](https://user-images.githubusercontent.com/16341594/31460688-e6009b66-aecf-11e7-88f0-cf04cb64072d.jpg)

**Comment by gonetz** [comment]
Agreed,
`settile: tile: 4, format: RGBA, size: 16bit, line: 0, t_mem: 000000b4, palette: 0, clamp_t/mirror_t: WRAP/CLAMP, mask_t: 0, shift_t: 0, clamp_s/mirror_s: WRAP/CLAMP, mask_s: 0, shift_s: 0`
It either loaded incorrect (line==0) or incorrectly mapped.

**Comment by angrylion7** [comment]
In my plugin the same bug was fixed in October 2010 by making texel1 depend on bi_lerp_1 bit, if texel1 is used in the 1st cycle of two-cycle combiner. Here in Killer Instinct bi_lerp_1 is clear, so yuv2rgb conversion is performed on texel1 instead of triangular interpolation. As for the 2nd cycle of two-cycle combiner, texel0 is actually texel1 from the 1st cycle, so it also depends on bi_lerp_1, while texel1 is actually texel0 for the next pixel (Monster Truck Madness 64 text), so it depends on bi_lerp_0. I don't think I've tested this on hardware, but it makes sense, because the triangular filtering unit (TF) can only emit one resulting texel per cycle.

**Comment by olivieryuyu** [comment]
vigilante 8 has white texture now with patreon5

**Comment by olivieryuyu** [comment]
same for Major League Baseball Featuring Ken Griffey Jr.: white textures

**Comment by gonetz** [comment]
Interesting, thanks!

**Comment by gonetz** [comment]
N64 uses YUV format for textures. YUV-to-RGB color space conversion required when texel fetched from such texture. This conversion enabled by special bits in othermode. That is RDP either fetch texel and use it as is, or does the conversion. This mechanism is not implemented in master, texels always used as is, YUV texture converted to OpenGL RGBA texture on CPU level and loaded to video memory. Everything worked fine, but these crafty RARE programmers decided to apply YUV-to-RGB conversion to non-yuv texture. Moreover, they use this texture as is for alpha combiner, but apply the conversion for use in color combiner. I implemented the conversion in shaders, and now the conversion applied twice for true YUV textures: first time during conversion to RGBA texture and second time in shaderes:
![vigilante_8-000](https://user-images.githubusercontent.com/8983092/31875009-5833f10e-b7f6-11e7-964e-263ab17fac5e.png)

**Comment by gonetz** [comment]
Fixed: adc2b547e881
