### ISSUE TITLE
Vsync issues with FBE turned off

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1520]
When you play a game with FBE turned off, Frame Limit off, and vsync turned on, the plugin it will allow the game to run up to 120 VI's. This doesn't happen when you have FBE on it will stay locked @ 60 VI's.

I have been using GLideN64 with Frame limit off, and Vsync on with my monitor set to 59hz to achieve the best possible smoothness in games. The games will run @ 59.94hz which is closer to the actual HW.  This also seems to resolved the skipped frames Windows 10 seems to have with N64 emulators but is broken when FBE is turned off.

**Comment by gonetz** [comment]
Starnge. vsync  does not depend on other plugin settings. It is just enabled or disabled when GL context created. FBE also does not limit frame count by itself. If emulator will call VI_UpdateScreen more than 60 times per second, plugin will update frame on each call, with or without FBE.

**Comment by loganmc10** [comment]
This isn't a bug at all. Try this with Smash Bros, it will run at the correct speed.

If you have FBE turned off, then the plugin will only swap buffers at the frame rate of the game. For Mario 64, this is 30FPS, so if you have FBE turned off, speed limited turned off, and vsync turned on, it will allow 60 buffer swaps per second, so the game will run at twice the speed it should.

The same thing would happen if you enabled FBE but changed the Buffer Swap Mode to "2/On Buffer Update" instead of "On VI Update Call".

So there is no bug here, you are asking GLideN64 to swap buffers at 30FPS, then capping the speed (via vsync) at 60FPS (or 59.94), so yes it will run twice the speed, unless the game is a 60FPS game

**Comment by theboy181** [comment]
Closed from unknown knowledge of correct output form FBE settings.
