### ISSUE TITLE
Severe performance impact at higher resolutions.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1534]
This is a general issue, but I've noticed that the plugin performance falls apart the higher you push the resolution (over 10x multiplier, for example), and I'm wondering if there's a bottleneck somewhere that needs addressing.

**Comment by fzurita** [comment]
@retrobenny has brought this up a few times.
https://github.com/gonetz/GLideN64/issues/1036
https://github.com/gonetz/GLideN64/issues/1052
https://github.com/gonetz/GLideN64/issues/1120

It seems to be related to the new blending method introduced a while back. Mupen64Plus has an option to use the legacy method which improves performance by a good amount. The option seems to be missing in GLIdeNUI.

**Comment by fzurita** [comment]
It almost looks like we are applying the new blending shader to something that we should not be upscaling with resolution.

**Comment by gonetz** [comment]
> The option seems to be missing in GLIdeNUI.

Desktop GPU must not have performance issues with blending shader, so this option disabled for zilmar specs. It is easy to check, is the blender shader a bottleneck on high resolutions with mupen64plus build, because it has "legacy blending" option.

**Comment by olivieryuyu** [comment]
@AmbientMalice 

with the new blending shader, is the performance ok now?

**Comment by AmbientMalice** [comment]
Although I haven't done extensive testing, performance does seem to be better. The problem isn't entirely fixed because performance collapses around/above 10x native on some games with default settings, resulting in single digit framerates. MSAA makes it worse.

![perfect_dark-012](https://user-images.githubusercontent.com/10704701/31017449-d490981c-a56b-11e7-9985-f983b3ed5321.png)

One factor is the cache setting, which by default is 500MB. This is insufficient for higher resolutions, and should probably be automated.

**Comment by olivieryuyu** [comment]
10x native? it is a huge resolution! Why would need this?

**Comment by AmbientMalice** [comment]
>10x native? it is a huge resolution! Why would need this?

I wouldn't personally recommend running games above 4x native, but some people want to run at very high resolutions.

320x240 times 10 is 3200x2400.

Some people are running 4K monitors, which natively render at 3840x2160.

Games like Perfect Dark are problematic because their high resolution mode is 640x222, which translates to 6400x2220 at 10 times native.

**Comment by olivieryuyu** [comment]
well then honestly no wonder why it is getting slow. Is there any program won't be slow at this resolution? I cannot believe we have a performance issue.

**Comment by AmbientMalice** [comment]
>Is there any program won't be slow at this resolution?

Most emulators are fine at 4K, and even 8K and beyond. PCSX2, Demul, Dolphin, etc. The problem with GLideN64 is that the cache size is a fixed value instead of just being as much memory as is available. It's rather inelegant.

Logan mentioned that:

>The only real solution would be to get rid of the CacheSize parameter, let it use as much memory as it can, and gracefully deal with GL_OUT_OF_MEMORY errors if/when they happen.

**Comment by gonetz** [comment]
> The problem with GLideN64 is that the cache size is a fixed value instead of just being as much memory as is available. 

It is easy to remove.

**Comment by gonetz** [comment]
> gracefully deal with GL_OUT_OF_MEMORY errors

This is a bit harder.

**Comment by loganmc10** [comment]
At high resolutions there are already GFX glitches because the cache size isn't big enough. It might be better to just get rid of the cache size limit, there is already an item limit that should prevent it from growing indefinitely. People will still run into GFX glitches if they run out of GPU memory, but then they just need to lower their resolution

**Comment by gonetz** [comment]
Ok, lets remove that config option.

**Comment by retrobenny** [comment]
Is there maybe a string that the plugin could read from your GPU in order to determine its memory size and then apply that to the cache/s appropriately?

I would think removing the limit outright could flood the GPU and potentially break it.
Someone should test cache sizes at larger scales until reaching a stable cache at a really high scale so nobody ends up with a trashed GPU and an effectively bricked PC.

Would a simple theory work for adding the size of cache via the multiplier dynamically such as finding a small stable x2 cache size and adding on to each increase from there to maintain the stability?

I just don't want anyone to have their GPU destroyed along with mine as a result of cache overload either from high scale size or from an unexpected leak that goes horribly wrong due to uncapped memory usage.

I think a good solution would be to set a size caps depending on the scale range.
First with 1x using 100MB,then anything between 2x-4x could use 200MB,any between 5x-8x uses 500MB,and anything 9x-12x uses 1GB then 13x-before_max would have 2GB and max would be a different story. (alternatively,each could have incremented cache usage on every scale)
Honestly,you could probably make it increase by 100MB on each scale,which would be convenient because then 8x would use 800MB and 10x would use 1GB instead of that 500MB size which would prevent the issues if its actually enough.
Also,the cache values could be indicated on GLideN64's settings for the scale so anyone that sets a scale would get to know the cache usage ahead of time if they want to be extra safe with their GPU's cache limits.

**Comment by dankcushions** [comment]
you can't brick a graphics card by using up its memory...

**Comment by Jj0YzL5nvJ** [comment]
> you can't brick a graphics card by using up its memory...

[Yeah...](http://www.eurogamer.net/articles/starcraft-ii-is-melting-graphics-cards)

**Comment by AmbientMalice** [comment]
That article is talking about GPUs running without Vsync potentially running into problems if they have crappy cooling solutions. You could get the same results by running literally any old PC game with vsync disabled.

**Comment by loganmc10** [comment]
Is this still a problem? I tested Perfect Dark at 1x native and 10x native. With 1x I got around 150 VI/s and with 10x I got around 110. That's pretty good I would say.

There is still the issue of crippling framerate with using MSAA + a really high resolution, but I don't know if that is a bug, or just asking too much of the plugin. If that is the only remaining issue I would maybe rename this issue.
