### ISSUE TITLE
Star Wars Rouge Squadron gfx bug

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1546]
![capture](https://user-images.githubusercontent.com/9299743/29237985-b451a8ce-7ede-11e7-8092-61e65c590a6c.PNG)

**Comment by AmbientMalice** [comment]
LLE mode for reference:
![gliden64_rogue_squadron_007](https://user-images.githubusercontent.com/10704701/29238026-bc8df778-7f6e-11e7-92f9-c7111aa77b10.jpg)

**Comment by olivieryuyu** [comment]
good eyes :)

**Comment by theboy181** [comment]
@AmbientMalice how did you get it working in LLE? when I tested it was messed up for me.. Latest build?

**Comment by AmbientMalice** [comment]
The game has always worked in LLE. What do you mean "messed up"?

**Comment by oddMLan** [comment]
Disable Antialasing for LLE. It doesnt play well with it

**Comment by theboy181** [comment]
@oddMLan that seems to work with LLE, but not HLE.. also I like AA..

**Comment by AmbientMalice** [comment]
>also I like AA.

Personally, GLideN64 should never have implemented MSAA. It breaks things, and SMAA/FXAA would have gotten just as good results.

**Comment by theboy181** [comment]
If I understand correctly MSAA has the best visual quality?  I think he made the correct choice, but options are always nice. 

I think it would be very cool if he implemented VI shaders, so the games could render as the developers had planned, and the ability to force different filters on/off would be a bonus too.

**Comment by AmbientMalice** [comment]
>If I understand correctly MSAA has the best visual quality?

No, and it's a fundamentally wrongheaded method of AA in emulators. PCSX2 hides in it a hack menu, and it causes a lot of side effects in Dolphin.

**Comment by oddMLan** [comment]
You sure postprocessing AA had NO side effects? How about the smears created with complex objects + fast camera movement on screen. Plus unless you use a expensive version of temporal antialiasing the image just doesn't look as crisp, MSAA which is arguably one of the oldest methods still objectively provides the best visual quality. Only thing it doesn't do is smooth out 2d objects. You might prefer one method better than the other but, please, don't recur to hyperbole making x thing seem way worse than it actually while championing y thing because you of your personal preference. I've seen you do this many times already, but don't see this as a personal attack, just a constructive criticism.

**Comment by theboy181** [comment]
I think ambient just likes to keeps things entertaining. I usually take his opininions extremely lightly. However I have seen others waste a lot of time tryin to convince him they are opinions. ;)

**Comment by AmbientMalice** [comment]
>You sure postprocessing AA had NO side effects?

Yes.

>How about the smears created with complex objects + fast camera movement on screen.

Only temporal anti-aliasing causes smearing. And temporal anti-aliasing is not, strictly speaking, a post-processing AA solution.

>Plus unless you use a expensive version of temporal antialiasing the image just doesn't look as crisp, MSAA which is arguably one of the oldest methods still objectively provides the best visual quality.

It is not objectively the best visual quality because it break things. Broken graphics are not "objectively the best visual quality". You may as well use supersampling, which in GLideN64's case would also break things because once you go past around 2x native resolution all the 2D alignment starts to fall apart.

>You might prefer one method better than the other but, please, don't recur to hyperbole making x thing seem way worse than it actually while championing y thing because you of your personal preference.

MSAA in emulators causes a massive hit to accurate and causes an endless array of bugs. Alignment problems are a very common one. Post-processing methods don't. That's not hyperbole. Nobody should be using MSAA in GLideN64. It should never have been added.

**Comment by oddMLan** [comment]
"It breaks everything." Wow. THAT'S hyperbole right there. MSAA only doesn't play well, but do no expect end users playing games in LLE anyways. For all purposes, MSAA works just fine in HLE while yes, breaking some stuff in games like Extreme-G. Due to the way N64-depth works, which is an option required for that game. It is warned that shouldn't use MSAA with it for that reason.  But 5 games it breaks isn't "everything" by definition, buddy.

**Comment by AmbientMalice** [comment]
>"It breaks everything." Wow. THAT'S hyperbole right there.

No, it causes 2D alignment issues in pretty much every single game.

**Comment by oddMLan** [comment]
But running a game in any other resolution other than native achieves the same defects. I must not notice much of the breakage anyways, because I only run games in multiples of native resolution, to avoid bilinear artifacts. I also don't notice any issues with AA playing on Dolphin, but they don't automatically scale the internal resolution to the window resolution _unless_ you choose the option for it, which if you do, you'll inmediately notice similar misalignment issues. Instead they make multiples of internal resolution the default. So I don't think this is a problem inherently from MSAA, but games weren't designed to run in other resolutions. Post-processing AA would just be a workaround to that, but with reduced visual quality as result (unless you supersample it).

**Comment by AmbientMalice** [comment]
>But running a game in any other resolution other than native achieves the same defects.

Yes and no. MSAA's side effects tend to be more subtle.

Native resolution:
![gliden64_mariokart64_000](https://user-images.githubusercontent.com/10704701/29245096-b42683ea-8011-11e7-8235-e197efd811f8.jpg)

Native resolution with MSAA:
![gliden64_mariokart64_001](https://user-images.githubusercontent.com/10704701/29245098-b9ec7aa0-8011-11e7-986f-28a171379b39.jpg)

2x native resolution. No MSAA:
![gliden64_mariokart64_003](https://user-images.githubusercontent.com/10704701/29245122-a762d3d8-8012-11e7-9cf5-e20c29bf6097.jpg)

>I must not notice much of the breakage anyways, because I only run games in multiples of native resolution, to avoid bilinear artifacts.

That doesn't really solve the problem of misalignment. The black line hack, and the option to render 2D elements at native resolution greatly helps, but the latter is expensive. I'm of the opinion that GLIdeN64 should default to N64 native resolution, with a warning that raising it will cause issues, but Gonetz was concerned about people complaining because the N64's native resolution is significantly lower than PS2/GC/Wii, which is a fair point but there is a long list of issues where the solution is "run at native resolution". Running above native resolution is an enhancement. It shouldn't be something that people use by default, IMO.

**Comment by AmbientMalice** [comment]
For the record, I'm sorry if I came across as smug and condescending. Essentially, the problem is that MSAA hurts accuracy quite a bit. I think it needs stronger warnings. Also, it should really be disabled at 1x native resolution because it undermines the accuracy benefits of running at 1x native resolution.

**Comment by mudlord** [comment]
Blame me. Problem solved.

**Comment by theboy181** [comment]
Then fix it @mudlord ;)

**Comment by theboy181** [comment]
Campaign state only one bug. It I also opened an issue explaining how the swipe effect is broken when swiping from right to left too

**Comment by gonetz** [comment]
Swipe effect is not HLE related issue and thus not directly covered by the Campaign.
Texture bug you reported here reveals an issue in ucode implementation.
Of course, both issues need to be fixed, but only this one is introduced with new code.

**Comment by theboy181** [comment]
@gonetz anyway I can get around patreon for the builds?

**Comment by gonetz** [comment]
This bugfix, as well as other bugfixes are not related to Patreon early access. The code is already in git. I'll make new WIP build this weekend.

**Comment by olivieryuyu** [comment]
Fixed!

**Comment by theboy181** [comment]
:)

**Comment by olivieryuyu** [comment]
Closed?
