### ISSUE TITLE
Pokemon Snap/Kirby 64/Super Smash Bros. unimplemented command

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1562]
I have just noticed that Pokemon snap uses at least one custom command which seems to be matrix related.

Interestingly the first time this command is used is at the very beginning of the game, meaning here:

![sans titre](https://user-images.githubusercontent.com/8987490/30020059-dcd9c3bc-9162-11e7-9ee4-3eb17c443f5a.jpg)

Potentially this would fix some issues :)

**Comment by olivieryuyu** [comment]
Same for Kirby64.

**Comment by loganmc10** [comment]
This might be unrelated, but one thing these 2 games (Pokemon Snap and Kirby) share on the emulator side is the need for "delay DP interrupt". Basically when the RSP task is finished the emulator delays triggering the DP interrupt, instead of triggering it right away.

Without that, the camera won't recognize the Pokemon in Snap, and the HUD doesn't display in Kirby

**Comment by retrobenny** [comment]
Facts: Both Kirby 64 and Pokemon Snap have the same developers,HAL (Kirby being obvious) which you'd know also is the main company that was responsible for Super Smash Bros. existing instead of what its original incarnation without HAL would've been which was...* searches * Dragon King: The Fighting Game where the fighters looked like what Captain Falcon's model was based on.

**Comment by olivieryuyu** [comment]
correct, Super Smash Bros. has the same command.

**Comment by AmbientMalice** [comment]
I wonder if there's any chance this HLE-only issue is related, then? https://github.com/gonetz/GLideN64/issues/1440

**Comment by olivieryuyu** [comment]
Not sure. The command is matrix related. if the wrong matrix is used, I would assume that various bug may occur.

For Super Smash Bros. the first time the new command appears, it is when this effect is displayed:

![sans titre](https://user-images.githubusercontent.com/8987490/30060334-3b6cf56c-9243-11e7-8deb-6ffc97e27a2f.jpg)

and for Kirby when a capacity is used.

**Comment by theboy181** [comment]
Interesting. So it was the addition of this command that fixed this missing effect?  I seem to recall that no hle plugin did this effect then randomly I reported it was working during one of the updates to GLideN64.

**Comment by olivieryuyu** [comment]
@theboy181 this screenshot is from Angrylion plugin.

I understand more or less what is going with this new command and the difference with the other ucode.

I don't know if it will have an influence on the various bugs which occurs in Kirby, Pokemon Snap and Super Smash Bros but I would guess so.

**Comment by AmbientMalice** [comment]
>Interesting. So it was the addition of this command that fixed this missing effect?

This was fixed in GLideN64 through better depth write behavior, IIRC.

**Comment by olivieryuyu** [comment]
@loganmc10 

Nothing seems to be fixed with this command but emulation is more accurate. It does not seem to help on the delay DP interrupt issue you mentioned.
