### ISSUE TITLE
Dr. Mario 64 (USA) - graphics corruption when loading a save state on launch

### ISSUE THREAD

**Issue by clobber** [gonetz/GLideN64#1568]
macOS 10.12.6
AMD Radeon R9 M370X
Mupen64Plus @ 138625a
GLideN64 @ bbc7131
rsp-cxd4 @ 664759f

When loading a save state on launch of the game, graphics become corrupted.

Steps to replicate:
* Boot Dr. Mario 64
* Start a 1-player classic game
* Create a save state
* Quit Dr. Mario 64 or close emulator
* Boot Dr. Mario 64 again
* Immediately load save state

<img width="752" alt="screen shot 2017-09-07 at 1 35 52 am" src="https://user-images.githubusercontent.com/1303132/30149566-b266b786-936d-11e7-931e-272c62338ab6.png">

Note: If you load your save state while you are already in a 1-player classic game, graphics will look fine:
<img width="752" alt="screen shot 2017-09-07 at 1 34 26 am" src="https://user-images.githubusercontent.com/1303132/30149597-da09cfb2-936d-11e7-9487-0197a800dcdf.png">

**Comment by gonetz** [comment]
This can't be fixed for existing saves because the game programmed that way. It renders the background only once before level start and keeps the result in auxiliary color buffer. Aux buffers not saved by default. You may enable "Copy auxiliary color buffers to N64 memory" option. That way background will be saved, but you will see it in N64 original low resolution.

**Comment by gonetz** [comment]
"Copy auxiliary color buffers to N64 memory" option is named EnableCopyAuxiliaryToRDRAM for mupen64plus.

**Comment by clobber** [comment]
Thanks for the info. I suppose I'll add that line to the custom config file for my own purposes. Do you know of other games that have this same behavior?

**Comment by gonetz** [comment]
Can't remember anything else.
