### ISSUE TITLE
Revision.h: No such file or directory

### ISSUE THREAD

**Issue by Danfun64** [gonetz/GLideN64#1625]
I know that MSYS2/MinGW-W64 isn't really mentioned at all, but I tried compiling on it anyways... However, I got an error regarding a missing file. http://paste.debian.net/989548/

Can this issue be fixed?

**Comment by loganmc10** [comment]
Inside the src folder is a script called getRevision.sh , you just need to execute that

Here is how I build in MSYS2:

```
cd GLideN64/src
./getRevision.sh
cd ../projects/cmake
cmake -G "MSYS Makefiles" -DVEC4_OPT=On -DCRC_OPT=On -DMUPENPLUSAPI=On -DCMAKE_AR=/$mingw_prefix/bin/gcc-ar ../../src/
```

**Comment by Danfun64** [comment]
Thanks for the help. BTW, what do vec4_opt and CRC_opt do?

**Comment by loganmc10** [comment]
They are both just code optimizations, they are made optional since they might introduce bugs over the regular non-optimized code. The CRC optimization has proven quite reliable, and could probably be made the default code. The vec4 optimizations have broken things from time to time, but more-so on ARM devices. Today the vec4 optimizations on the desktop should be relatively stable/bug free

**Comment by loganmc10** [comment]
Just FYI, I maintain a buildbot that builds mupen64plus + GLideN64 for Linux and Windows (the Windows build uses MSYS2), if you want to take a look at how I do it:

https://github.com/m64p/mupen64plus-GLideN64

The Windows builds are built using AppVeyor: https://github.com/m64p/mupen64plus-GLideN64/blob/master/appveyor.yml

And can be downloaded at: https://m64p.github.io

**Comment by Danfun64** [comment]
I didn't know about that. Nice!

**Comment by loganmc10** [comment]
I've heard that from a couple people but I've never been able to track down the issue. I've tested it on 2 different laptops and I don't have that issue

**Comment by gonetz** [comment]
@loganmc10 I also use AppVeyor for windows builds. Unfortunately, I haven't time for fine tuning of building process. Currently I have setup only mupen64plus build. Do you know, is it possible to setup the build with QT static libs? QT plugin for Visual Studio must be installed and static libs provided. I did not learn how to do it.

**Comment by loganmc10** [comment]
I use MinGW to compile everything, using QT static is easy there because there is a ```mingw-w64-x86_64-qt5-static``` that installs everything you need. So I don't have a lot of experience with Visual Studio.

However, if you look here:
https://www.appveyor.com/docs/build-environment/#qt

They list where it should be installed:
> Qt 5.9.1: C:\Qt\5.9.1 (C:\Qt\5.9 mapped to C:\Qt\5.9.1 for backward compatibility)
MinGW 5.3.0 32 bit: C:\Qt\5.9.1\mingw53_32
msvc2017 64-bit: C:\Qt\5.9.1\msvc2017_64 (VS 2017 image only)
msvc2015 64-bit: C:\Qt\5.9.1\msvc2015_64
msvc2015 32-bit: C:\Qt\5.9.1\msvc2015
msvc2013 64-bit: C:\Qt\5.9.1\msvc2013_64

I don't know if that contains the static libraries, or how you would properly connect it with Visual Studio though
