### ISSUE TITLE
OoT random crash on subscreen

### ISSUE THREAD

**Issue by Epictheboss** [gonetz/GLideN64#1668]
PJ64 2.3.2.202

Ocarina of Time randomly crashes when attempting to open the subscreen.  Most of the time it works without a hitch, occasionally it's a little slow, and sometimes it just decides to crash.  This has happened on a massive variety of settings.  Copy Auxiliary Buffer is off.  It only seems to happen with GLN64, and the pause hack is off since other plugins take a long time to bring up the subscreen.

Also, when it crashes the CPU usage of the emulator skyrockets from about 4% to 30+%

video: https://youtu.be/dK8WPLabfzc

**Comment by gonetz** [comment]
Does it happen with original OOT rom, not with hacked one?

**Comment by Epictheboss** [comment]
@gonetz yes, it happens with it as well.

**Comment by retrobenny** [comment]
Most if not all OOT mods use the Debug MQ version of the game and that version is known to more likely crash on pausing into the sub-screen.
There is a crash fix code for the original Debug MQ version { also I ported that to (U) (V1.0) } which works better than the normal game's code since it prevents the same crashes with its value workaround.
GLideN64 is supposed to just work without crashing on the sub-screen normally but I have also seen it fail at one point earlier on,likely because of certain settings being on or off.

**Comment by gonetz** [comment]
@Epictheboss I will not spend my time on crashes in hacked roms. If 'good' rom works ok, please close the issue.
