### ISSUE TITLE
Video Settings Not Saving

### ISSUE THREAD

**Issue by Roggieh123** [gonetz/GLideN64#1696]
Hello,

I downloaded the latest version of GLideN64 and tried to use it with Project64 2.3.2. Unfortunately, I am unable to get any of my video settings to save. Whenever I adjust the settings (full screen resolution, aspect ratio, anti-aliasing and anisotropic filtering) and hit "OK", and then go back to the Video Settings, I find that none of these changes are saved and everything is reverted back to the default settings (resolution is back at 640 x 480 (4:3), AA and AF turned off, etc.).

I have permissions to write to the plug-in folder, too. I'm at wits end as to what to do about this, and am unable to properly enjoy the great graphical improvements this plug-in provides.

Thank you in advance, and I want to express my appreciation to you, gonetz, for all your hard work in creating this plugin, fixing bugs, and keeping it updated.

-Rog

**Comment by gonetz** [comment]
What is your OS?

**Comment by Parthros** [comment]
I downloaded the 3.0 public release and I'm having basically the same issue, where it won't save any video settings, including texture enhancement settings.

Other info:
Project64 2.3.2.202
Windows 10 Pro 64-bit

**Comment by gonetz** [comment]
Hello,

IIRC, Project64 default install folder is Program Files. Users do not have rights to write there.
GLideN64 stores settings in %Project64 folder%\Plugin\GFX\GLideN64.ini
You probably have no right to update the ini there.

Possible solutions:
- Install Project 64 to another folder, for example C:\Games\Project64
- or run Project64 as Administrator - right click on Project64 icon, select run as Administrator.

Please try it and report about the result.

**Comment by Parthros** [comment]
Hey, thanks for getting back to me!  I ended up deleting that post because I realized I'd failed to install the plugin correctly.  However, here's a quick summary of what got me working again.

1. Actually copy all the ini files included in the download to the Plugin folder.
2. I granted read & write access to the Plugin folder to pretty much all users on my machine.
3. Double checked that settings were saved both before closing Project64, and after restarting it.



The issue I originally had was that settings wouldn't save, even when I didn't restart Project64.  I'd click the "OK" button, go back and check what I'd changed, and it went back to its default value.  However, just installing the plugin properly fixed that, and granting read & write access to the Plugin folder fixed settings not being saved when restarting Project64.

**Comment by gonetz** [comment]
Roggieh123, is the problem still actual for 8? Have you tried provided solutions?

**Comment by gonetz** [comment]
Closed. Please reopen if the problem still exists.

**Comment by Dragorn421** [comment]
I had the exact same issue.
Switching PJ64's install folder (it was in Program Files) fixed it, but I would have preferred having been able to manually edit some ini config file to change the default config location. Is that possible?

**Comment by gonetz** [comment]
> I would have preferred having been able to manually edit some ini config file to change the default config location. Is that possible?

No. The plugin works only with its own ini files and these files must be in the same folder where the plugin is located.
