### ISSUE TITLE
Superman 2nd screen missing

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#173]
same issue than

https://code.google.com/p/glidehqplusglitch64/issues/detail?id=5&can=1&q=status%3DFixed

**Comment by gonetz** [comment]
To display second screen:
* enable copy buffer from RDRAM
* disable copy buffer to RDRAM

Please test and close.

**Comment by olivieryuyu** [comment]
ok you mean disable fb and render fb as texture.

it means that if there is any fb effects in another place of the game, it won't work. I dunno this game enough to say if there is or not fb effects.

Should I still close?

**Comment by AmbientMalice** [comment]
Superman has more complex FB problems. https://github.com/gonetz/GLideN64/issues/617

**Comment by gonetz** [comment]
> ok you mean disable fb and render fb as texture.

Disable copy buffer to RDRAM, enable fb as texture.

> it means that if there is any fb effects in another place of the game, it won't work.

If there is another fb effect, which needs copy buffer to RDRAM, it will not work.
We usually do not use these option both enabled.

> Should I still close?

The problem is solved with enabling the option, which is specially designed for such cases.
I don't see any reason to have it open.

> Superman has more complex FB problems. #617

I did not tested it, but problem description suggests the same options to make the effect working:
disable copy buffer to RDRAM, enable fb as texture.

#617 is not about issue in Superman, it is about the problem that "copy color to RDRAM overwrites data written by the CPU".

**Comment by olivieryuyu** [comment]
fixed but in case there would be in this game fb effects, there will be an issue.
