### ISSUE TITLE
Game image upside-down with GlideN64-Fast, correct with GlideN64-Medium

### ISSUE THREAD

**Issue by M-a-r-k** [gonetz/GLideN64#1749]
Emulator version 3.0.181 on Huawei G620S phone.

With GlideN64-Medium profile the game image is correct: the right way up matching the controller overlay. However with GlideN64-Fast, the game image appears upside-down.

**Comment by fzurita** [comment]
This is an issue with GPU drivers in your phone. Go to settings then display and chose the "Fix upside down screen" option.

**Comment by M-a-r-k** [comment]
Yep I know about that option. Just wondering, why it's only necessary for one GlideN64 profile but not another?

**Comment by fzurita** [comment]
I'm not quite sure. The "fast" just disables frame buffer emulation. With frame buffer emulation enabled, there is an extra FBO before a buffer gets put in the screen, so it probably has to do with that.

In the past, the "Fix upside down screen option" was needed for all profiles on affected devices. Maybe something we are doing now with frame buffer emulation makes it only needed when frame buffer emulation is disabled.

**Comment by gonetz** [comment]
In the past, FBO was not used when frame buffer emulation disabled. Currently FBO is always used. That allowed me to have MSAA regardless of frame buffer emulation. The difference between frame buffer emulation on/off is that when it is on, FBO rendered to main frame buffer with texture rectangle command, while when it off FBO can be put to main buffer with glBlitFramebuffer, if supported. The problem is with glBlitFramebuffer as I understand.

**Comment by fzurita** [comment]
To really fix this issue, we would need a database of GPU driver versions that have partially working glBlitFramebuffer. I don't think it's worth the effort. The user can choose the existing workaround if they have an affected GPU.

**Comment by gonetz** [comment]
I agree.
