### ISSUE TITLE
Render 2D elements in N64 Reolution Performance Hit

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1837]
This is one of my favorite settings in GLideN64, it just makes most games 2D look amazing at higher resolutions.

In F-Zero X when you place on the top 3, some fireworks of your character will get displayed. This effect has no impact on performance when you have Render 2D in N64 rez, but when its enabled it gets hit hard! 

With frame limit off, and Native 2D off it stays at 300+ VIs. 

With Native 2D enabled it drops from 300 VI to 30Vi.

This seems significant, and I am wondering if this is what should be expected? Can the code be improved to maker performance any better?

 
![untitled](https://user-images.githubusercontent.com/9299743/41261210-89a10656-6d8f-11e8-92d5-92c5840c519b.png)

**Comment by gonetz** [comment]
Texrects work quite slow in general and currently can't be optimized. "Render 2D elements in N64 Resolution" option makes them two-tree times slower. It is still ok when number of texrects is relatively low. When texrects are used for particles , that option can slowdown rendering without any positive effect, because each particle is separate image not aligned with others, and render it in native resolution has no benefits. I think, that it is possible to avoid that problem. I can analyze next commands in display list and find, if rendering in native resolution need to be applied. I can do it only in HLE though.

**Comment by theboy181** [comment]
@ledgenofdragoon has speed them up tremendously In AL, If iirc

**Comment by gonetz** [comment]
In AL?

**Comment by theboy181** [comment]
In Anrylion's Plugin, he was able to get 2d games that use texrects running at 700vi plus. Bangaio for example.

**Comment by theboy181** [comment]
AL+ runs this section faster, can that be explained?

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/41420713-f6b56158-6fa9-11e8-94bd-28b96f0daca7.png)

**Comment by LegendOfDragoon** [comment]
Bangaio largely uses Copy mode, so that's why I was able to achieve good performance in that game. I tested GLideN64 in a few 2d heavy games and GLideN64 was already fast.

I have not tried this F-zero mod though.

**Comment by theboy181** [comment]
Its straight up F-Zero X. Not just the MOD

**Comment by gonetz** [comment]
It should be faster in current master. If not, please give me savestate to test.

**Comment by theboy181** [comment]
Perfect now! Awesome work!!
