### ISSUE TITLE
Profiles introduced issues with save/load feature on PJ64.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1879]
Since Profiles have been added, loading states during debugging sessions have been painful.

Steps:

1.) Load any ROM
2.) Create a Save State
3.) Open GLideN64 settings window and change the resolution, press OK
4.) load the Save State
5.) Observe that the resolution changes back.

Is there a way to disable profile feature, or have it fixed?

**Comment by retrobenny** [comment]
I feel like I have ran into this issue as well,and other oddities because when I ran Conker and tried to adjust it for my monitor resolution change,it sometimes ends up with larger black bars on the sides or top/bottom when it was filled in better moments before then.

And for some reason,the custom profile stuff stopped showing up when changing settings on a running game,meaning you had no choice to change your mind by hitting cancel,unless I got confused and non-buffer settings don't have that condition.

Although,it reverts my resolution sometimes.
I think having the profile customization system should be optional,as some people can't be arsed to close a game to change settings then open the game on top of having to deal with another game being opened that lacks your pre-startup settings due to the custom stuff changing it to the last conditions you had it last due to changing a single setting.

I have to deal with something similar to this all the time in Dolphin Emu,but for stuff like their cpu clock override being very buggy and prone to reverting itself between game boot sessions,making things a pain when the game freezes and I have to redo the overclock setting to make it refresh to what I had last as the value shown is a lie.
(worst part is that long standing issue for Dolphin can't be fixed for Wx,leaving me out of the mix unless some super fans of the Wx interface make a branch to port most of the good stuff Qt got that Wx was shafted on)

**Comment by gonetz** [comment]
@theboy181 I hopefully fixed the issue. Please test:
https://drive.google.com/file/d/1MgdsEQDToLLfMwKE_RJGjGjHxtHvQuQ0/view?usp=sharing

**Comment by theboy181** [comment]
This seemed to fix the resolution switching. I’ll let you know if other settings are an issue as I use it. This is looking good now though. Thanks.

**Comment by gonetz** [comment]
Update:
https://drive.google.com/file/d/1kZMUj6rr45WdAH9pORhLFI1Q89XT6LRp/view?usp=sharing

**Comment by theboy181** [comment]
What has changed?

**Comment by gonetz** [comment]
Added warning: "Per-game settings enabled. Settings will be applied only for the currently running game."
Minor code cleanup.

**Comment by rafaelgasai** [comment]
Wow! Thanks for this actualitation! It's little but very powerfull. I needed it.

**Comment by gonetz** [comment]
@theboy181 Can it be closed now?

**Comment by theboy181** [comment]
Thank you, yes
