### ISSUE TITLE
Quest 64: Pink Borders Around Texts

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1924]
In Quest 64, there are pink borders around all text in the game. This happens in HLE of newest WIP (Master+FB) but doe not happen in LLE or in angrylion. Messing with the settings and deleting the shaders doe not fix the problem.
HLE:
![gliden64_quest_64_000](https://user-images.githubusercontent.com/37382324/46575424-a8783780-c969-11e8-9bae-8c95d93c704f.png)
LLE:
![gliden64_quest_64_001](https://user-images.githubusercontent.com/37382324/46575430-b3cb6300-c969-11e8-9d19-444cce864cb9.png)

**Comment by gonetz** [comment]
This game looks the same in HLE and LLE for me. Text is rendered with texrect command, which works the same for HLE and LLE. You probably has different settings for LLE mode.

**Comment by Yui12** [comment]
This is a legacy issue that affects all plugins it seems. Using the old glN64 with 2xSAI Texture Scaling kind of fixes it but the pause is kind of buggy with some text flickering when going through the menus.

**Comment by Kidboy17** [comment]
@gonetz I have the exact same settings for HLE and LLE. I'm using Project 64 2.4.0.668-gc506db5.

**Comment by gonetz** [comment]
@Kidboy17 It is obvious. Pink, green etc outline is result of bilinear filtering. Bilinear filter works correct in native resolution, but in higher resolutions it fetches texels, which are not designed to be used.  The problem explained in article found by gizmo98:
https://github.com/gonetz/GLideN64/issues/1898#issuecomment-427563738

**Comment by BigheadSMZ** [comment]
This is very interesting, after so many years I never would have guessed that RGB values in fully transparent pixels were the cause of the pink text. That article explained it in a way that makes far more sense in my brain. I actually came across a similar issue when helping Hypatia with custom textures for TLoZ: Wind Waker in Dolphin. The game expects RGB=255 and A=0 (not RGBA=0) or a lava texture becomes broken. So my texture tool I created options to remove or fill these "ghost" values.
https://forums.dolphin-emu.org/Thread-custom-texture-tool-ps-v38-0?pid=479243#pid479243

So it makes me wonder if this issue can be bypassed with custom textures, I'll have to test in the near future. This would be an alternative to pre-multiplied alpha, as filtering algorithms wouldn't be necessary if the "invisible noise" wasn't there to begin with. If the textures for the font really do have RGB > 0 where A = 0 in the transparent pixels, it would be an easy "fix" to the textures at least (set all RGB values to 0). That is, if the fonts actually dump correctly, it's been years since I've messed with N64 texture replacement.

The idea itself is basic: if pixel alpha = 0, set R=0, G=0, B=0. Perhaps it could also be a feature in GlideN64, but I could see it being slow as it would require checking every single texture pixel. That is, if this approach even works.

**Comment by BigheadSMZ** [comment]
Yep, there's that famous pink we all know. Analyzing the transparent pixels, it's everywhere.

![a](https://user-images.githubusercontent.com/9309452/51788029-365d7580-2147-11e9-9d4a-db34892c0d96.png)

Turns out a custom texture does work using only the original resolution (no upscaling). I only modified the uppercase and lowercase letters here.

![b](https://user-images.githubusercontent.com/9309452/51788050-702e7c00-2147-11e9-8bb3-8efe91d896a7.png)

The option "Use full transparencies" must be unchecked, otherwise it will try to filter the transparent data as black and you get the outlines again (except not pink).

![untitled](https://user-images.githubusercontent.com/9309452/51788060-981ddf80-2147-11e9-98a8-dbebecd49578.png)

Perhaps there is some way to do this in GlideN64 without custom textures? Like I mentioned before, all I did was find any pixel that has 0 alpha, and set the RGB data to 0.

**Comment by Jj0YzL5nvJ** [comment]
[Erm...](https://github.com/gonetz/GLideN64/issues/1933)

The full story [here](https://github.com/gonetz/GLideN64/issues/1898).

**Comment by gonetz** [comment]
@Kidboy17 fix for bilinear filtering is in master now, details in #1933. The fix removes the pink boarder around text in Quest 64. The issue can be closed now, don't you think?

**Comment by Kidboy17** [comment]
You are correct. All the pink borders about the text are gone no matter the resolution I use. Great job again guys!

**Comment by Heraes-git** [comment]
Guys, can you explain to people who are not developers of emulators softwares how to solve the problem of pink borders ?

If I understand, I have to use a GlideN64 plugin in my emulator to have a chance to solve the problem. So, I'm un M64py, I've gfound a way to use the GlideN64 plugin, but now I'm facing a huge option panel with nearly a hundred of options.

Could you not create a simple checkbox named "remove pink border on text" ? I know this would "conflict" with other options/checkboxes, but you could make them grayed if so.

**Comment by Ididntdothis1221** [comment]
Does anyone have a fix for this in retroarch?

**Comment by Jj0YzL5nvJ** [comment]
> Does anyone have a fix for this in retroarch?

Recompiling the "Mupen64Plus-Next" core with your own `GLideN64.custom.ini` file?

The core simply does not allow altering "problematic" settings by "inexperienced users", make a feature request to change that [in the core](https://github.com/libretro/mupen64plus-libretro-nx/issues).

**Comment by Helouj** [comment]
> Oh okay. Yeah I was trying to see how I could create that custom ini file. It's not terrible. Thanks for the reply.

Any chance you'd like to share with the rest of the class whatever guide you're using, and does it work with the japanese version of quest 64? :)
