### ISSUE TITLE
Mario Party 3 green/black lines

### ISSUE THREAD

**Issue by Tenolius** [gonetz/GLideN64#1931]
Using the latest Master + FB Fixes rev 067840da. When playing Chance Time, you will get a texture with green lines. This issue also occurs in certain minigames but is less noticeable (for instance, a smaller blue/black line can appear when playing Messy Memory or other minigames). 

Save state to immediately start Chance Time:
[Mario Party 3 (U).pj.zip](https://github.com/gonetz/GLideN64/files/2476121/Mario.Party.3.U.pj.zip)

Save file in case you wish to check Messy Memory in the Mini Game Room (uncompress zip file to get the eep save file):
[MarioParty3.zip](https://github.com/gonetz/GLideN64/files/2476124/MarioParty3.zip)

![mp301](https://user-images.githubusercontent.com/12527930/46912944-15766900-cf38-11e8-91bf-1224c016e148.png)

![mp302](https://user-images.githubusercontent.com/12527930/46912976-d563b600-cf38-11e8-8cc7-f67b29539455.png)

**Comment by gonetz** [comment]
Both issues related to common problem with bilinear filtering. The problem was discussed many times, you may check #1898 for example.
Currently bilinear filtering issues can be fixed only by using native resolution. So, either use "Original N64 resolution" option, or 'Render 2D elements in N64 resolution". The second options fully fixes issue with Chance Time, and should help to Messy Memory as well. However, due to an optimization I added to that method, it is not applied to rectangles with gloves and they still have black outlines.
