### ISSUE TITLE
Inquiry - Blur feature 

### ISSUE THREAD

**Issue by Exequiel3k** [gonetz/GLideN64#1943]
Hey,
First and foremost, thanks for making such a great plugin available to us all and bare in mind I’m aware there exists smoothing/sharpening within the video settings. What I was wondering is if it was possible to add a user-defined blur option which lets us blurr the output-frame to a certain level since at times on certain games everything seems “just too pixel-sharp/Ultra-HD” for its own good. It would be quite interesting to have an option which could imitate the “bluriness of old ntsc/crt screens”...

Also, I’m aware retroarch has shaders but this is just too darn good to switch :p

**Comment by CallistoNTG** [comment]
Have you tried setting the output resolution to native?

**Comment by Exequiel3k** [comment]
Yeah, it goes from one end to the other..

**Comment by gonetz** [comment]
You may use 2X, 3X .. native resolution to have blurred image.
If you use 1080p and original resolution is 320x240, 3X native will result in 960x720 rendering resolution, which will look blurry after upscale to 1080p but not that much as 1X native.

**Comment by Exequiel3k** [comment]
I’d like to do that, but in m64p I believe checking “fullscreen” in the settings automatically causes the game to match the output resolution. Is there’s another way to manually set the desired output resolution (for unwindowed fullscreen), could you indicate where? Thx!!

**Comment by gonetz** [comment]
As I understand, m64p  selects monitor's native resolution, when switching to fullscreen. It is set as plugin's output resolution. That is, OpenGL context will allocate main frame buffers with that resolution. If you set aspect to 4:3, plugin automatically adds black borders to output image to keep that ratio. It is important to understand, that plugin does rendering not directly to OpenGL main frame buffers, but into internal frame buffers, which can have arbitrary resolutions. These internal buffers then rendered into main buffers as textures. If resolution of internal buffer is less than resolution of main ones, the output image will look blurred because of image up-scale.
Look at this example:
![gliden64_the_legend_of_zelda_002](https://user-images.githubusercontent.com/8983092/49351183-ce5d5680-f6e4-11e8-9918-f5967563ec4f.png)

Game's internal resolution 320x240. Plugin uses 2X native, thus rendering resolution is 640x480. Output resolution is 960x720, thus image looks blurred. The same works for full-screen.

**Comment by loganmc10** [comment]
m64p defaults to matching the window resolution (640x480 is the default window size).

If you put it into full screen, it'll be the resolution of your monitor, while still respecting the aspect ratio of the game.

To force a different resolution, you use GLideN64's "NativeResFactor" setting, it's in the plugin settings.

"0" is the default, which means "match the window" any other number means "factor of native resolution". So "2" would be 2x the games native resolution

**Comment by Exequiel3k** [comment]
Wow, thanks for such a thorough explanation of the mechanics and how to enforce it. It’s exactly the information I needed on all levels :)

It’s kinda bitter-sweet closing this thread cause the information is on-point and most likely other people could ultimately have similar end-result inquiries.. Could there be a sticky-posts in the closed sections? :p
