### ISSUE TITLE
S2DEX fixes. Feedback.

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1971]
Current HLE implementation for backgrounds commands is too high level. Actual commands are very complex. The microcode is documented, but the documentation does not cover some tiny details in internal mechanics. Thus, existing implementation does not always work right. olivieryuyu decided to not rely on documentation and decode the microcode itself. The goal of that new decoding project was to implement commands in HLE as close as possible to LLE and obtain the result, which is as good as with LLE or better.

It was very long and hard project, which took circa six months. It is not finished yet, but we are close. Both background commands implemented and they produce exactly the same result as in LLE mode on all games we tested.

You may run current versions of the plugin in LLE mode and find numerous graphics glitches in 2D games. Some of glitches caused by errors in texture loading code. Backgrounds commands do texture loading in quite weird manner, which "normal" game code never uses. I fixed several hard issues in plugin's texturing subsystem during development of that project. However, many glitches remained after these fixes. These glitches can be called "the curse of hardware rendering". There are two main groups of such glitches:

* gaps between polygons. Background commands can not draw background by one piece because of limited texture memory. Background image becomes split on narrow strips. Each strip is loaded in texture memory and rendered by separate rectangle. There are no gaps between rectangles, but gaps between images in them may appear when rendering resolution is higher than game's native resolution. It usually happens when size of the image is not exactly the same as size of area where it will be rendered. Texture scaling in higher resolution may cause fetching texels out of texture image bounds, thus cause artifacts, which look as gaps between polygons.

* garbage between polygons. Looks like a line of colored garbage between two polygons. Is is seldom kind of glitches, but it does not fixed by switching to native resolution. I did not find yet, how it can be cured.

So, new implementation has issues, but most of them appears only in non-native resolutions. GLideN64 already has tool to eliminate issues with 2D graphics in high resolutions. You may enable "Render 2D elements in native resolution" option to activate it. I adopted that tool to work with new background commands. StarCraft backgrounds have glitches in high-res, but "Render 2D elements in native resolution" eliminates them. However, the tool is not bug-free by itself and in some games its use may cause disappearance of part of graphics. Besides, sometimes it is slow.

As you may guess from my explanations above, it is in rather alpha state. We tested it a lot, but with only two of us we could miss some regressions. Please test and leave bug reports. Sources reside in [s2dex_fixes](https://github.com/gonetz/GLideN64/tree/s2dex_fixes) branch. I suggest to start with  "Render 2D elements in native resolution" disabled and enable it only when you see aforementioned glitches. If use of  "Render 2D elements in native resolution"  causes new glitches, please report about it. Also, if you see glitches, please switch to LLE mode and compare. It is important for us to know about cases where LLE is still better.

**Comment by gonetz** [comment]
Related open issues:
#1896 
#1897 
#1870 
 #1869 
#1695 
#1619 
#936 
#1518 
 #315 (is it ucode issue though?) 
#329
#133

**Comment by Kidboy17** [comment]
Ok just did some testing. I have to say, this makes 2D images so much better than before, great job guys!
Everything I tested I did with the option Original N64 resolution since using any other output option, even only 2x on Multiple, would have very tiny graphic issues. I am using the latest development build of Project 64. 
Kirby 64: No more outlines on 2D objects. Looks very clean.
Yoshi Story: No issues with the clouds on the game over screen. No issue with invisible objects or invisible texts.
Pokemon Puzzle League: Background no longer jitters. Game looks great.
Goemon's Great Adventure: No tiling effect on the background.
Quest 64: No pink outlines on the texts.
Killer Instinct: No lines on character images
Mischief Makers: Game looks great!

**Comment by Kidboy17** [comment]
Ok just did some testing. I am using the latest development build of Project 64.
 
#1695 Kirby 64: The outlines appear unless you have Render 2D enabled or use Original N64 Res option. Game runs fine from what I have seen with Render 2D enabled.
 #1896 Pokemon Puzzle League: The background is fixed now. Works with and without Render 2D enabled. Played a few rounds, game seems fine if people want Render 2D on.

**Comment by Kidboy17** [comment]
Found a minor issue with Mario Kart 64. This happens in both LLE and HLE mode when not using Original N64 Res option. Render 2D does nothing to it.
![mariokart](https://user-images.githubusercontent.com/37382324/50389728-9beeba00-06e2-11e9-8ed3-67d367c467fb.png)

**Comment by CallistoNTG** [comment]
Resident Evil 2 glitchy backgrounds seem to be improved. Problem seen here https://github.com/gonetz/GLideN64/issues/1869 The hallway background renders correctly, and options menu only has some faint vertical lines on the text instead of heavily glitched lines. I'd post screenshots but Github isn't allowing it right now for some reason.

**Comment by gonetz** [comment]
> Resident Evil 2 glitchy backgrounds seem to be improved.

This is strange. New background code is currently incompatible with RE2, thus old code is used.
So, if something is improved in this game, it is because of some general fixes in texturing, which I've done in that branch.

**Comment by olivieryuyu** [comment]
a new bug here (recent)

![gliden64_gt64_000](https://user-images.githubusercontent.com/8987490/50400418-d14ce380-0786-11e9-9a73-d09d1d034e99.jpg)

**Comment by weinerschnitzel** [comment]
It looks like there are also alignment issues in the mini map

**Comment by gonetz** [comment]
Regression in GT 64 speedometer is fixed with f0b9f02e0.
Mini map looks a bit different in HLE and LLE.

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/50507929-70e2ce00-0a34-11e9-8dbe-c4ba4dd71ca3.png)
1080 has a regression with the background using this WIP Not sure why its not an SDEX title.

**Comment by gonetz** [comment]
I made several corrections in general texturing code, so any game can be affected.
I'll check, may be this regression caused by these corrections.

**Comment by OtavioRaposo** [comment]
Indiana Jones first level sky is looking strange. Also, there's this garbage line in the right corner.
![untitled](https://user-images.githubusercontent.com/36393971/50569243-66cc1280-0d47-11e9-912d-d39107f858b1.png)

**Comment by theboy181** [comment]
Same issue in 1080 Snowboarding.

**Comment by theboy181** [comment]
I think and I can’t double check right now that there is 2d regressions in Mario Golf again too.

**Comment by gizmo98** [comment]
After upgrading to ubuntu 18.04 and getting everything running again i had some time to test s2dex_fixes branch. Everything looks fine. I experience significant slowdown in Bakuretsu Muteki Bangaioh compared to an old branch from november 18.

**Comment by theboy181** [comment]
So none of the bugs reported ? @gizmo98

**Comment by gizmo98** [comment]
@theboy181
Ok. I just tested s2dex games. I will check the posted issues.

**Comment by gonetz** [comment]
I reverted commit, which causes issues reported by theboy181  and OtavioRaposo. Thanks for help!
Link on updated build is in [WIP builds 3](https://github.com/gonetz/GLideN64/issues/1574)

**Comment by Nerrel** [comment]
The Neon Genesis commit that was just reverted seemed to solve several problems in Majora's Mask.  This glitched ground seam was fixed by the initial S2DEX merge and is now broken again in the new WIP build:
![image of ground](https://c2.staticflickr.com/8/7833/31730344567_3614cef803_h.jpg)

Also, before the S2DEX merge objects that combined a larger grayscale texture with a smaller color texture used to require that the new custom color texture to be offset from the grayscale one by a few pixels diagonally to align correctly, otherwise this blurred/ doubled effect would be created:
![image of blurred ground](https://c2.staticflickr.com/8/7823/32797163928_c45f4df288_b.jpg)
![image of misaligned trees](https://c1.staticflickr.com/5/4835/32797258208_c904529b25_c.jpg)

After the S2DEX merge this offsetting was no longer necessary and the new HD color and grayscale textures aligned perfectly without needing any offset.  This seems like the correct behavior, since it's also how the same custom textures load in Dolphin.  The new build once again requires the textures to be offset.  

One last thing is that some custom textures aren't loading consistently after the S2DEX merge, and this is true in the latest WIP build as well.  The skybox textures flicker on and off suddenly; the entire skybox is dumping new textures with different filenames, but the old textures still seem to load intermittently.  Here's a brief video of the problem: 
https://youtu.be/PJ5gT6binCA

**Comment by gonetz** [comment]
@Nerrel It's a bad news :( 
Everything related to N64 texturing emulation is so complex and fragile. My current goal is to fix all regressions and make new release. Than I'm going to rewrite GLideN64 texturing to make it more friendly to HD textures.

**Comment by Nerrel** [comment]
Right, I don't expect custom texture fixes until that rewrite, but the mapping/positioning of many of the default textures was also improved by that commit.  The ground seam in that first photo also occurs with the original textures, for instance.  I just wanted to make a note of that build's fixes in case it wasn't known that it improved Zelda as well.  

Will the texture rewrite change the way the way the default textures are handled as well as custom textures?

**Comment by IceLancerSR** [comment]
@gonetz 
Small question and request if possible?

I tried to make PJ portable but i ran into a problem with plugin.

textureFilter\txPath=E:/test/Project64/Plugin/GFX/hires_texture
textureFilter\txCachePath=./Plugin/GFX/cache
textureFilter\txDumpPath=./Plugin/GFX/texture_dump

As u can see cache and texture dump is accepting relative pathing
but txPath is not. Only absolute is accepted.
is it possible to fix that?
Thanks

**Comment by gonetz** [comment]
@IceLancerSR I'll check, what is wrong with txPath.
Please open new task for it. This one is about S2DEX fixes, so I may just forget about your request as it has no separate open task for it.

**Comment by olivieryuyu** [comment]
can it be closed?

**Comment by gonetz** [comment]
I think it can
