### ISSUE TITLE
Sorry, this file is infected with a virus  Only the owner is allowed to download infected files.

### ISSUE THREAD

**Issue by IceLancerSR** [gonetz/GLideN64#1979]
Hey, i cant seem to dl ur glide releases. google gives me permission error

Sorry, this file is infected with a virus

Only the owner is allowed to download infected files.

Current master + s2dex fixes:
https://drive.google.com/file/d/1BVcJ7Werx4cSaSdVGXrzWYbCSWXvpJty/view?usp=sharing

Details in #1971

Details in #1971
No feedback here please.

Actually, i cant download ANY release, even old ones that i was able before, now it throws virus on google and prevents me from downloading

**Comment by 5schatten** [comment]
Well how did you end on this google drive share... below are the release pages of r3.0 and there is not google drive link at all.

https://github.com/gonetz/GLideN64/releases/tag/Public_Release_3_0
https://gliden64.blogspot.com/2017/12/public-release-30.html

**Comment by 5schatten** [comment]
This is a WIP = work in prgress build and **not** a release version and since [someone already stated that link is somewhat broken](https://github.com/gonetz/GLideN64/issues/1574#issuecomment-451739460) this "issue" is IMHO unecessary.

**Comment by IceLancerSR** [comment]
@5schatten his post is older then mine.
I wrote this a day ago. His post is 7 hours old. What are u trying to say anyway?

**Comment by oddMLan** [comment]
I swear to god that every year all of Google services are becoming increasingly worse...

**Comment by 5schatten** [comment]
@tony971 well *maybe* I had the impression that git repos are made for developement purposes but obviously it's for some broken links on google drive.

The start "post":

> Hey, i cant seem to dl ur glide releases. google gives me permission error
> Sorry, this file is infected with a virus
> Only the owner is allowed to download infected files.

refered to **releases** so everyone with common sense would think these files https://github.com/gonetz/GLideN64/releases are broken or infected with a virus but what he meant were WIP dev builds on a third party repo.

But go on, have fun and feel free to spam.

**Comment by IceLancerSR** [comment]
@5schatten Stop trolling u freak

**Comment by 5schatten** [comment]
@IceLancerSR Well how about setting up a build system and compile the stuff yourself? Otherwise it might useful to wait until a new WIP build, _not release_, is uploaded without spaming useless stuff on a git issue page? Time well spent...

**Comment by IceLancerSR** [comment]
@5schatten Ok , this is my last post WASTED on u.
1. Learn NOT to edit ur posts after the fact that u already got reply. Referring to couple posts up!
2. Stop bully attempt , ur freaking booring
3. U started massive spam with just posting here. Why the hell did u even do that? U got ur panties in the twitch so u had to go and shit in some github? Is that it? Very Well Time Spent IS it?
now gtfo

**Comment by oddMLan** [comment]
@5schatten Would you stop behaving like a pretentious moron, your tone is very condescending. Someone reported a valid issue, that evidently has nothing to do with the repo itself, but the method the WIP builds are delivered. You're the one blocking the thread with inflammatory "posts" after OP made clear he was referring to the WIP builds. Since this ticket is **_not relevant to you_** (you use your own build system right?)
![imagen](https://user-images.githubusercontent.com/7278372/50745105-99618980-11e5-11e9-964b-adcfd6b8d44a.png)
Leave it and let the users who depend on the WIP builds thread engage in a conversation and propose alternatives.

**Comment by IceLancerSR** [comment]
Issue solved!
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-451897261

**Comment by 5schatten** [comment]
@oddMLan 
Well just because you're obviously used to be called this way it's not okay to call others a moron. And I'm sorry about my condescending tone but I guess with a serious lack of reading comprehension skills you're familiar with that too. Once again this git repo is used by other distros too like [RetroPie](https://github.com/RetroPie/RetroPie-Setup/blob/5e2b080c7fdd4cb1a14fb271b4cf6501ff9b3393/scriptmodules/emulators/mupen64plus.sh#L66) or  [recalbox](https://github.com/recalbox/recalbox-buildroot/blob/27081f730e247d0c22ce15928241ab844681e588/package/mupen64plus-gliden64/mupen64plus-gliden64.mk#L9) so how about not scaring some maintainers up? Because maybe those people want to make sure they don't ship builds to thousands of users without any viruses...





How about that? Use the edit button and change the content to something meaningful?
![image](https://user-images.githubusercontent.com/36100210/50765929-c52d4f80-1277-11e9-98e4-dcb112be59a4.png)

For example:

[WIP builds] GDrive download links are broken

Hey, i can't  download your [WIP builds](https://github.com/gonetz/GLideN64/issues/1971). in particular [this file](https://drive.google.com/file/d/1BVcJ7Werx4cSaSdVGXrzWYbCSWXvpJty/view?usp=sharing),  google gave me a permission error:

> Sorry, this file is infected with a virus
> Only the owner is allowed to download infected files.

_And you're done but instead of thinking twice and reflecting if your rubbish post is valid you're trying to underline your non existing arguments with insults. Congratulations kiddos._

**Comment by tony971** [comment]
1. End user reports an issue that has poor wording in the first sentence, but provides links to the actual issue

2. You only read the first sentence and dismiss the issue

3. Everyone else reads the whole issue, realizes that the builds OP actually reported do have issues, then fixes those issues

4. You get embarrassed that you're the only one who interpreted it wrong and get mad at everyone for allowing the questionable wording from an end user

5. You get confused when you're considered the asshole in this situation
