### ISSUE TITLE
bgMode option does nothing in mupen64plus

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2007]
graphics2D\bgMode=0 (one piece) works perfectly in Project64 (v2.4.0-850). Texture Packs that do contain large single image backgrounds are then loaded by GlideN64. Awesome!

However, both the mupen64plus CUI and m64p (2019-02-08) don't seem to respect the changed variable and basically stay on graphics2D\bgMode=1 (stripped). With that, large single-file backgrounds are not loaded from the texture pack and the plugin falls back to vanilla backgrounds.

To reproduce, here is a texture cache with an upscaled background of Link's house in Ocarina of Time. Start the game and press C-Up while being in the beginning house. The upscaled texture should load with backgroundsMode=0.

[THE LEGEND OF ZELDA_HIRESTEXTURES.zip](https://github.com/gonetz/GLideN64/files/2877437/THE.LEGEND.OF.ZELDA_HIRESTEXTURES.zip)

Vanilla texture:
![the legend of zelda cdad9309 0 2_all](https://user-images.githubusercontent.com/31742919/52977356-39a5f300-33cd-11e9-9746-701087d8b457.png)

Upscaled texture:
![the legend of zelda cdad9309 0 2_all](https://user-images.githubusercontent.com/31742919/52977289-05cacd80-33cd-11e9-9f15-6ba9eff58182.png)

**Comment by gizmo98** [comment]
Maybe this happens because default value is int...
https://github.com/gonetz/GLideN64/blob/master/src/mupenplus/Config_mupenplus.cpp#L96
...and value which should be loaded is bool...
https://github.com/gonetz/GLideN64/blob/master/src/mupenplus/Config_mupenplus.cpp#L392

Just try to replace 0 with false.

**Comment by GhostlyDark** [comment]
Thanks for the fast response.
Unfortunately, this didn't do the trick. I tried changing it in the mupen64plus.cfg as well as adding a game specific setting for the game in GLideN64.custom.ini

**Comment by gonetz** [comment]
There are two problems here:

1.  I dumped background data from RDRAM with mupen64plus and with Project64. The dumps are different. Many values differ slightly, like 0x62d3524f<=>0x62d35a4f
Difference even in one byte will produce different checksums. Thus, mupen64plus just can't load that HD background because checksum is different. I don't know the reason of texture data discrepancy. Probably backgrounds stored in rom in packed format (jpeg?) and unpack works different with mupen64plus and Project64. The only way to fix this issue is to add two copies of HD background texture, with different names for PJ64 and m64p. To get name for bg texture, you need to dump it. Unfortunately, backgrounds dump was not implemented in GLideN64. I fixed it in commit 49465a094de. Dump gave me the following names for this background texture:
`THE LEGEND OF ZELDA#CDAD9309#0#2_all.png` for Project64
`THE LEGEND OF ZELDA#631C2E06#0#2_all.png` for mupen64
2. I corrected read of "BackgroundsMode" option. It is declared as int parameter in mupen64plus config and should be read as int. As I explained above, it is **not** a reason of the problem with HD background load.  Nevertheless, there is a problem with that option. Initially, mupen64plus had no support for custom ini. I tried to use meaningful names for mupen64plus config parameters because default way to change parameter in mupen64plus config is to edit it with text editor.  Config file for Project64 uses short parameters names because user control them via GUI elements. Custom ini file has the same format as main config for Project64 with the same parameters names. mupen64plus now can read that file, so GLideN64 uses the same custom ini for PJ64 and m64p. The problem is that names of many parameters are different for main ini and custom ini in case of mupen64plus. For example name for "BackgroundsMode" option in custom ini is "bgMode". You need to keep it in mind. This is inconvenient situation and options names must be unified somehow. Someday.

**Comment by GhostlyDark** [comment]
Thank you for the quick fix!

I dumped all the background textures with GlideN64 via m64p but did get a different name for the texture of Link's House:
`THE LEGEND OF ZELDA#CBA9E984#0#2_all.png`

It differs from the one mentioned in the previous post.

Regardless though, the checksums are consistent and texture loading now works with the alternative BackgroundsMode in m64p.

**Comment by gonetz** [comment]
If my guess is right and backgrounds images are stored in rom in packed format, data of unpacked image may differ with different RSP plugins or with different settings in core, for example re-compiler vs interpreter. It would be good to get explanation from emu core devs.
