### ISSUE TITLE
hires_texture Relative path

### ISSUE THREAD

**Issue by IceLancerSR** [gonetz/GLideN64#2017]
Small question and request if possible?

I tried to make PJ portable but i ran into a problem with plugin.

textureFilter\txPath=E:/test/Project64/Plugin/GFX/hires_texture
textureFilter\txCachePath=./Plugin/GFX/cache
textureFilter\txDumpPath=./Plugin/GFX/texture_dump

As u can see cache and texture dump is accepting relative pathing
but txPath is not. Only absolute is accepted.
is it possible to fix that?
Thanks

mupen64plus_x64

EDIT:
There were fixes to this before in 2015, and it stated that Plugin/GFX/hires_texture should work?
It doesnt.
neither is /Plugin/GFX/hires_texture
it doesnt accept any relative path only absolute

**Comment by gonetz** [comment]
Hi!

There is really issue with relative path. I need to check that path to hires_texture folder really exists, which is not that easy if path is relative. I need to switch to C++ 17 to get more-less convenient tools to work with file system. However, it your case lack of relative path support is not a problem. You need to define that testures folders are sub-folders of the folder, where plugin located, that is Project64/Plugin/GFX.
It is default location actually. You may just leave paths blank, and plugin will build correct absolute paths to the folders. There were mistakes in my code, and the plugin built the pathes wrongly. The bugs fixed in 08e15767a6. You may also use relative paths if you want. Plugin will detect that path is relative and will use default absolute path instead, see 4a925e149. These fixes are available in latest WIP build: #1574

**Comment by IceLancerSR** [comment]
Thanks! I tested
Only empty path works
textureFilter\txPath=
if i try to type in anything else it stops working. But its ok like this.

**Comment by IceLancerSR** [comment]
@gonetz , there might be more typos?
I tried to build under windows , but i am getting error of missing files. So here is diff
===================================================================
--- src/mupenplus/Config_mupenplus.cpp	(revision 732)
+++ src/mupenplus/Config_mupenplus.cpp	(revision 733)
@@ -165,11 +165,11 @@
 	wcstombs(txPath, config.textureFilter.txPath, PLUGIN_PATH_SIZE * 2);
 	res = ConfigSetDefaultString(g_configVideoGliden64, "txPath", txPath, "Path to folder with hi-res texture packs.");
 	assert(res == M64ERR_SUCCESS);
-	wcstombs(txPath, config.textureFilter.txCachePath, PLUGIN_PATH_SIZE * 2);
-	res = ConfigSetDefaultString(g_configVideoGliden64, "txCachePath", txPath, "Path to folder where plugin saves texture cache files.");
+	wcstombs(txCachePath, config.textureFilter.txCachePath, PLUGIN_PATH_SIZE * 2);
+	res = ConfigSetDefaultString(g_configVideoGliden64, "txCachePath", txCachePath, "Path to folder where plugin saves texture cache files.");
 	assert(res == M64ERR_SUCCESS);
-	wcstombs(txPath, config.textureFilter.txDumpPath, PLUGIN_PATH_SIZE * 2);
-	res = ConfigSetDefaultString(g_configVideoGliden64, "txDumpPath", txPath, "Path to folder where plugin saves dumped textures.");
+	wcstombs(txDumpPath, config.textureFilter.txDumpPath, PLUGIN_PATH_SIZE * 2);
+	res = ConfigSetDefaultString(g_configVideoGliden64, "txDumpPath", txDumpPath, "Path to folder where plugin saves dumped textures.");
 	assert(res == M64ERR_SUCCESS);

**Comment by gonetz** [comment]
@IceLancerSR Have you tested with my latest WIP build?
I set the options in my GLideN64.ini as
```
textureFilter\txPath=./Plugin/GFX/hires_texture
textureFilter\txCachePath=./Plugin/GFX/cache
textureFilter\txDumpPath=./Plugin/GFX/texture_dump
```
Everything works properly

I set 
```
textureFilter\txPath=
textureFilter\txCachePath=
textureFilter\txDumpPath=
```
Everything works properly either.

**Comment by IceLancerSR** [comment]
@gonetz 
u are absolutely right. I am sorry. I made mistake , accidentally swapped and used older version of plugin in the test
Relative path works perfectly !
