### ISSUE TITLE
File Tex Storage disables hires textures

### ISSUE THREAD

**Issue by JustNoon** [gonetz/GLideN64#2079]
Project 64 2.4.0.966
GlideN64 WIP 4 + Tex Storage

"use file storage instead of memory cache" under hires textures causes the hts file to generate (possibly) correctly but doesn't actually display any hires textures. Works fine when cache is enabled. Have tried rebuilding shader cache and deleting all htc and hts files.

Tested on a custom texture pack for Banjo Kazooie. I have provided a trimmed down version with the copyright, dialogue text, title screen logo, etc for testing. Also provided is the hts it generates.
[BK-TexStorDisabled.zip](https://github.com/gonetz/GLideN64/files/3512474/BK-TexStorDisabled.zip)

![image](https://user-images.githubusercontent.com/45368472/63217827-c75f6280-c112-11e9-8dc3-1aa000f0bea0.png)
![image](https://user-images.githubusercontent.com/45368472/63217830-cfb79d80-c112-11e9-89af-8ae7b06a769f.png)
![image](https://user-images.githubusercontent.com/45368472/63217833-d6461500-c112-11e9-8788-18ce778626aa.png)
![image](https://user-images.githubusercontent.com/45368472/63217835-dba35f80-c112-11e9-8186-af40e7b3417e.png)

**Comment by gonetz** [comment]
You need to enable "Save enhanced texture cache to hard disk".
This options may sound a bit confusing because it enables save for both enhanced textures cache and hi-res textures cache. You may use texture cache without saving, but it will be dropped after your game is closed.
If "file storage" does not work for you at all without save to disk option, it is a bug. I did not test it in that mode.
You don't need to remove .htc cache files. Plugin searches for .htc files when file storage disabled and for .hts file when it is enabled. If cache with required format does not exist plugin tries to create it from .png textures located in hires_texture/ROM_NAME folder.

**Comment by gonetz** [comment]
@JustNoon Please test with latest WIP build from #2037
Your problem with file storage could be caused by unchecked cache compression, see #2120
I've fixed that issue.

**Comment by gonetz** [comment]
Closed until feedback from @JustNoon
