### ISSUE TITLE
Could you please make a WII64 whit it?

### ISSUE THREAD

**Issue by Halfshadow** [gonetz/GLideN64#2220]
Hello. Could you please make a WII64 version (is open source the emulator) with this plugin like they made a Rice plugin version? I want to play Cruis'n Exotica on the WII and this openGL plugin seems to be the only.

**Comment by weinerschnitzel** [comment]
As I recall Wii64 originally used a derivative of n64gl, so it should be possible to update the wii with some of the advancements here.

Some concerns though:

This plugin uses a higher level of opengl than original n64gl. Are necessary features compatible?

Another concern is speed. Rice is a very fast plugin but GLideN64 is a bit more resource intensive. Would you get acceptable speeds with this plugin on the wii?

Another concern is general Big Endian support. Wii is PPC based so GLideN64 would have to be Endian agnostic to work correctly.

Tbh, I think this a task best suited for the Wii64/Not64 guys to consider. I also think Rice is "as good as it gets" for old platforms like the xbox and wii since it as not as CPU intensive. Just my 2 cents though.

**Comment by Halfshadow** [comment]
> As I recall Wii64 originally used a derivative of n64gl, so it should be possible to update the wii with some of the advancements here.
> 
> Some concerns though:
> 
> This plugin uses a higher level of opengl than original n64gl. Are necessary features compatible?
> 
> Another concern is speed. Rice is a very fast plugin but GLideN64 is a bit more resource intensive. Would you get acceptable speeds with this plugin on the wii?
> 
> Another concern is general Big Endian support. Wii is PPC based so GLideN64 would have to be Endian agnostic to work correctly.
> 
> Tbh, I think this a task best suited for the Wii64/Not64 guys to consider. I also think Rice is "as good as it gets" for old platforms like the xbox and wii since it as not as CPU intensive. Just my 2 cents though.

Thank you for your reply. I have to admit that I don't know the WII CPU and the system requirements for this plugin, but I can tell that Not64 uses always n64gl and can play Cruis'n World almost at 100% of the speed. Cruis'n Exotica is lighter to emulate by Cruis'n World (at least in project64) and also in Not64 with the same n64gl plugin, the only issue is that cannot load the right textures.

Rice instead decodify partially the textures (not entirely) and is slower by n64gl, but I thought was only due to the wrong decription (is also buggy with freezes) I didn't know about the WII cpu power issue, the WII64/Not64 developers told that the issue was the necessity to use an openGL plugin to works with the WII, otherwise Jabo3D8 would be a fast video plugin to do it, the only issue is that isn't an opengl one.

Then the best way would be fix n64gl to work with Cruis'n Exotica? But that plugin is always under development?

**Comment by gonetz** [comment]
> Tbh, I think this a task best suited for the Wii64/Not64 guys to consider.

Agreed. I probably can help if they will have questions and especially with Big Endian support.
But I definitely will not update N64 emulators for Wii by myself.
