### ISSUE TITLE
Black screen since Appveyor release 1.0.575

### ISSUE THREAD

**Issue by backgamon** [gonetz/GLideN64#2252]
Hi,

Since Release 1.0.575 [Commit 096115d9 ] from appveyor i only have a black screen with sound running behind.
Using PJ64 (any version).
Older than 1.0.575 working well.

Windows Pro X64 (18363.778)
32Gb Trident Z RGB 3466Mhz@XMP3200Mhz
Gigabyte 2070 RTX 8G OC (445.87).

**Comment by IronYoshi64** [comment]
I was literally right about to post a new issue on this! :)
And I found out this only happens if you have the Overscan option turned On. Turning off Overscan resolves it. And yeah I found out the last version that did not have this issue was this one: https://github.com/gonetz/GLideN64/commit/096115d99794bf8f6b171fe71cb5084f4ea51fa8

**Comment by LuismaSP89** [comment]
Confirmed here, also the game Jet Force Gemini doesn't work in previous versions "for example in": 438bcc46  unless you disable the overscan. So maybe the issue started before this commits.

**Comment by gonetz** [comment]
Please check again with latest build.

**Comment by backgamon** [comment]
It work now, good job!
