### ISSUE TITLE
dark rift background issue

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2257]
![GLideN64_DARK_RIFT_004](https://user-images.githubusercontent.com/8987490/81532020-051caf00-9364-11ea-8fc9-93ef0c22062f.png)

**Comment by gonetz** [comment]
@standard-two-simplex I need you help on this. This regression is caused by Texture Engine modifications. Backgrounds are rendered by two sets of texrects. First set is for far background. It uses 321x6 textures. The second one is for closer background with big rocks. It uses 256x6 textures. The problem is with the second set. I suppose texture clamp works wrong here.

**Comment by standard-two-simplex** [comment]
The game is in copy mode. GLideN64 reports `masks=0` and `sh` seems to be high enough not to clamp to 256. Therefore, we get `s` texture coordinates greater than 256 and `texelFetch()` returns zeros (invisible color).

The programming manual says that in copy mode clamping is implicitly disabled and judging from angrylions plugin, it should be wrapping at coordinate 256. However, texture coordinates are in theory able to go up to 1024 and the other background texture seems tu use them .

In master, `texture()` calls automatically wrap at texture edge, so a correct picture shows. I can write a generalworkaround in `clampwrapmirror()` to wrap around the texture edge if after clamp wrap and mirror the texture coordinate is out of bounds. 

While that is the current behaviour of master, I don't know what a N64 does in this cases.

**Comment by standard-two-simplex** [comment]
Ok, I think I had a moment of illumination and I know whats happening in real hardware.

To the hardware, textures aren't rectangles but an array of colors. When the sofware ask texture with coordinates `(255,2)` it is not returning color at position `(255,2)` but color at position `2 * 256+ 255` (assuming `width=256`).

Therefore, it doesn't care if you give it bigger coordinates than the width. For example, coordinate `(258,2)` gives color at position `2*256 + 258 = 3*256 + 2` so it is standard coordinate `(2,3)` !!! That's why master is showing a black line, the texels are meant to be fetched from the next row. 

I'll try to implement this idea.

**Comment by standard-two-simplex** [comment]
Success!

**Comment by gonetz** [comment]
Indeed. Cool, thanks!
