### ISSUE TITLE
Request for the ability to force custom textures to different formats

### ISSUE THREAD

**Issue by Nerrel** [gonetz/GLideN64#2287]
As I understand it the different texture types N64 uses are denoted by the dump filename, with files ending in "all" being 32-bit per pixel with RGBA channels and textures ending in "RGBA" being 24-bit with the alpha channel being intensity only.  If possible, I'd like to be able to force a texture to use the 32-bit "all" format to enhance certain textures.

As an example, the fairy wings in OoT and MM are 32-bit textures ending in "all" and support a smooth gradient from transparent to opaque, which allows for a nice translucent effect: 
![image of tatl](https://live.staticflickr.com/65535/49947451906_ebc5d8101f_z.jpg)

The bee wing texture name ends in "RGBA" and does not support anything other than 100% opacity or 100% transparency, meaning I can't achieve the same effect.  A texture exported with semi-transparency will show up fully opaque in-game.  
![image of bee](https://live.staticflickr.com/65535/49947452016_604c3da26a.jpg)

The only way to get semi-transparency right now is to dither the pixels, which looks very bad: 
![image of dither](https://live.staticflickr.com/65535/49947740017_f225e64fea.jpg)

I'd like to be able to change the texture format in cases like this to have the full range of transparency.  For other examples, I could smoothly feather the edges of many of the signs and windows in the game to better blend them into walls or bake in shadows to make 2D objects look more 3D.  
![image of windows](https://live.staticflickr.com/65535/49960808187_07bab2e1d8_c.jpg)

I'm guessing the easiest way to force the change would be to let the modder rename the file to match the format they want it to be forced to.  So for the bee wing texture I would change it from "ZELDA MAJORA'S MASK#07558098#2#0#FFFFFFFC_ciByRGBA" to "ZELDA MAJORA'S MASK#07558098#4#1#all" and ideally the plugin would load it as a 32-bit "all" texture.  I actually tried doing this already to test what would happen and the plugin did load the texture but there were no changes to its behavior.  

This is another low priority request and I'm not sure if it's possible to do, but it could lead to better textures in this and other games.  Thanks for all the great work on this plugin!

(My understanding of the texture formats is based on this, which may be outdated: https://github.com/TASVideos/mupen64-rr/blob/master/doc/HiRezTexture.txt )

**Comment by gonetz** [comment]
N64 supports 32bit textures, but they are expensive for N64 hardware and thus rarely used. Most common cases are 16bit RGBA in format 5-5-5-1 (5 bits for color 1 bit for alpha) and CI (color indexed) textures. CI textures also use 16bit RGBA color. 16bit IA (intensity-alpha) textures also use full alpha, but only one channel for color (intensity). 

So, 5-5-5-1 is most used format for N64 colored textures. 1 for alpha means either full transparency or full opaque. It is very limiting. That's why KoolSmoky implemented an option, which he named "Lets texture artists fly". This option enables special mode for loading textures from png files. The code analyses how alpha channel is used in texture, and if it is differs from 1 bit scheme, the texture is loaded as full 32bit RGBA texture. In GLideN64 this option is named as "Use full transparencies" and is enabled by default. Thus, your request is already fulfilled. I haven't checked how this option works. If it does not work properly for dome of your textures, I may check what is wrong.

**Comment by Nerrel** [comment]
It must not be working correctly then, I've had it checked since the start of the pack.  If I recall, there were textures in the past that did allow for full transparency and at some point ceased to support it.  I had a few soft shadows on some objects that suddenly turned to hard black blocks, so I had to remove them.  I'll have to double check later  

If you want to test the bee example, here's a savestate of the area and the bee wing texture with the wings at 50% opacity (just walk forward a few steps).  I tried disabling use full transparency just to see what would happen and the bee wing disappeared almost entirely:  https://drive.google.com/file/d/1Xd-Vif5Zx6jVFc7jZWWfnILLdxV48RZ1/view?usp=sharing

**Comment by gonetz** [comment]
Wing texture works like this for me:
![Wings_hd](https://user-images.githubusercontent.com/8983092/83601264-6ec25e80-a59a-11ea-8d6a-f8712806d3e3.png)

As you may see, the "Use full transparencies" option works.
From the other side, the wing looks fully opaque. I'm not sure why it ever works - color blender is disabled for wings polygons, and alpha test is disabled too. So, we should see the whole texture with  black areas. It is true for the original texture too, which looks transparent.

**Comment by gonetz** [comment]
I found what removes transparent pixels of the wings. There is another special code, which works as alpha test. It is enabled when CvgXAlpha flag is set and it discards all pixels with alpha below 0.125. CvgXAlpha is set for the wings. Alpha combiner assigns  texel alpha to pixel alpha, so all pixels where texel is transparent are discarded. If I disable that test, wings will look like this:
![Wings2](https://user-images.githubusercontent.com/8983092/83628326-7eee3400-a5c2-11ea-8172-33844a70207b.png)

Conclusion: it is impossible to make the bee wing translucent, because the game disables color blender for it and thus it is impossible to blend color of the wing polygons with color of the polygons behind it. Sorry, but the game designed like this.
Of course, it can be hacked, but hacks are evil.

**Comment by oddMLan** [comment]
I wonder if it can be hacked though a GameShark code.

**Comment by Nerrel** [comment]
I see, thanks for looking into it.
