### ISSUE TITLE
Request not an issue: GUI 

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#2289]
dump/edit textures = off texture caches.

**Comment by GhostlyDark** [comment]
Hi there,

you should probably explain a bit more what you mean by that. Do you want the texture cache to be disabled when dump/edit textures is enabled? I am strongly against that, as dumping new textures with an existing pack would be a huge pain.

I wanted to create a new issue to request a GUI change as well. I'll start here instead to avoid confusion.

**I want dump and edit to be seperated options.** The issue is that I always accidentally hit R and reload my 20GB+ cache file, either when testing textures or when dumping the ones that aren't part of the pack yet. It's an issue with PJ64, e.g. when adding cheat codes. Mupen64plus is even worse, as background input always works, even when not focused, unless the emulation is paused.

**Comment by gonetz** [comment]
> **I want dump and edit to be seperated options.**

Done in 7228d0d5db

> dump/edit textures = off texture caches.
> you should probably explain a bit more what you mean by that.

Yes, I also need to know what you mean by that.

**Comment by Nes-player4Life** [comment]
i wanted .htc loading off if texture dumping is on. Although i guess i didn't put much thought in my post.

i like the feature added  https://github.com/gonetz/GLideN64/commit/7228d0d5db323e9540f7466e7b387b0f7cdc5968
/closed
