### ISSUE TITLE
HD textures show aliasing

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2311]
Probably introduced by 2f5280c

![aliasing](https://user-images.githubusercontent.com/31742919/87969049-b442d880-cac1-11ea-99ea-c9e8682dcbd9.png)

Top: current
Bottom: before

**Comment by Professor-CDawg** [comment]
It appears to me that this issue is visible across the whole image, not just on 2D elements/HD textures. 

Furthermore, it seems, in my testing, to only occur when using an aspect ratio setting other than 4:3.

![GLideN64_ZELDA_MAJORA'S_MASK_006](https://user-images.githubusercontent.com/68561018/87970665-0d931380-ca92-11ea-94ad-2ded24b4c749.png)
Using "Try to adjust game to fit"

![GLideN64_ZELDA_MAJORA'S_MASK_009](https://user-images.githubusercontent.com/68561018/87970744-2b607880-ca92-11ea-9323-1afe31f3338f.png)
Using 4:3

If you look closely at the aliased edges, they look considerably more garbled in the top image, using "Try to adjust game to fit." Using 16:9 creates the same effect.

This garbling becomes perhaps more apparent when using MSAA:

![1 (MSAA 8x, Adjust)](https://user-images.githubusercontent.com/68561018/87970874-6b276000-ca92-11ea-98e0-e535176b5314.png)
MSAA 8X, "Try to adjust game to fit" - Edges have strange jaggies, though not the same as with AA off

![4 (MSAA 8x, 4-3)](https://user-images.githubusercontent.com/68561018/87970944-8c884c00-ca92-11ea-820d-681ea9b8d04b.png)
MSAA 8X, 4:3 - Edges look smooth and clean, as expected when using MSAA


Finally, I'm unsure if it is related, but the aliasing, as well as this strange garbling issue, seem to become far worse when using a high multiple of N64 resolution as the internal res (these screenshots were taken using "same as output resolution" for internal res

**Comment by oddMLan** [comment]
@gonetz Don't use nearest neighbor to downscale a high resolution image. Use OpenGL bilinear.
Same thing with downscaling native resolution. Hybrid filter to downscale native res is just wasted processing. I'm 90% sure plain bilinear should look the same. 

https://github.com/gonetz/GLideN64/issues/2301#issuecomment-653642997

**Comment by gonetz** [comment]
@oddMLan I'm currently very busy and will not be able to look at it until August. Could you make necessary corrections and provide a PR to test?

**Comment by oddMLan** [comment]
> @oddMLan I'm currently very busy and will not be able to look at it until August. Could you make necessary corrections and provide a PR to test?

I looked at the relevant code but I'm not fully understanding the logic behind it. You check for downscale if `blitParams.srcWidth >= blitParams.dstWidth && blitParams.srcHeight >= blitParams.dstHeight;`. Shouldn't it be `blitParams.srcWidth >= blitParams.dstWidth || blitParams.srcHeight >= blitParams.dstHeight;`? It's still technically downscaling if either of the dimensions is being resized down.

Also, why the check for `config.frameBufferEmulation.nativeResFactor != 1`? Seems strange. Couldn't it happen that the the game uses hires mode (640x480) and rendered in a smaller window? Current code says if that's the case, it's considered upscaling, and if hybridFilter is disabled, it will use nearest neighbor, which _will_ distort the image. Downscaling no matter what has to use bilinear to avoid distortion.

Anyway made PR #2313. @gonetz, please review the changes when you have time.
Test builds for PJ64 and Mupen64Plus.
[test builds.zip](https://github.com/gonetz/GLideN64/files/4986639/test.builds.zip).
