### ISSUE TITLE
Broken shadow-like effect in HLE with GoldenEye

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#2321]
Said effect only appears in very specific parts of the map.
https://imgur.com/a/3nighpa

Mupen64Plus savestate: https://0x0.st/igWB.zip

**Comment by olivieryuyu** [comment]
hmm how odd...

@gonetz 

I have email issue

**Comment by gonetz** [comment]
> @gonetz
> 
> My email does not work anymore :(

Please send me a message from any other mailbox.

**Comment by olivieryuyu** [comment]
ok sent on your ngs.ru :)

**Comment by gonetz** [comment]
@Jj0YzL5nvJ Could you give me a savestate for Project64? I wonder, how it looks with other HLE plugins.

**Comment by Jj0YzL5nvJ** [comment]
PJ64 1.6 savestate: https://0x0.st/i73V.7z
Current versions of PJ64 do not work OOTB with Wine 5.0.3 and my WinXP VM doesn't help...

**Comment by gonetz** [comment]
Thanks!

As I see, other HLE plugins work the same. Shade (vertex) color is different in HLE and LLE mode:
![goldeneye-000](https://user-images.githubusercontent.com/8983092/101012995-38d85400-3596-11eb-96ee-6aa937929330.png)
![goldeneye-002](https://user-images.githubusercontent.com/8983092/101013001-3c6bdb00-3596-11eb-9f07-254c5e406198.png)

It can be tricky.

**Comment by gonetz** [comment]
I found what is wrong. This effect did not work until recently in both HLE and LLE. It started to work after my LLE fixes. It requires noperspective shade color, which I enabled for both HLE and LLE. So, this effect worked in HLE until my commit 03b404bd4e6, where I disabled noperspective shade color for HLE because "noperspective works incorrect for polygons, which are partially out of view".

So, we can't use noperspective shade color for non-clipped polygons. I tried hard to avoid software polygons clipping, but it is another argument for it.

**Comment by standard-two-simplex** [comment]
@gonetz Are you planning to write a software polygon clipper?

I also encountered problems with clipping when rendering polygons using their screen coordinates and I considered writing it. I eventually didn't do it because I wasn't sure how to integrate it to current code. I.e., I know how to compute the clipped vertices (say, I could generate up to four `SPVertex` objects) but I don't know how to pass the new polygons to OpenGL to process them.

**Comment by gonetz** [comment]
> Are you planning to write a software polygon clipper?

Yes. I'm planning to take a vacation for two weeks. I hardly will go traveling since borders are closed because of the pandemic. So, I'll probably implement a software polygon clipper before new public release.
Moreover, I'm thinking about emulation of RSP clipping code, that is with N64 fixed point arithmetic. There is a tiny hope that it may help to fix or reduce the polygons misalignment issue. However, I need @olivieryuyu help with it.

**Comment by olivieryuyu** [comment]
Hmm clipping code is a quite complex code to decipher. i understand the principles but I am far to catch the whole matter. Emulating this means emulating the whole fixed point math for vertex calculations. It would be a significant work.

**Comment by weinerschnitzel** [comment]
Just curious, would the amount of work be feasible for software, and would this scale up well with higher resolutions without performance issues?

Lots of plugins have implemented a software vertex clipper but RSP style clipping sounds more expensive than those.

**Comment by gonetz** [comment]
> would the amount of work be feasible for software

Generic vertex clipping is a fast operation. As you may remember, UltraHLE worked full speed on Pentium2.
Glide64 works fast on mobile devices.
RSP style clipping can be slower but hardly too expensive.
Anyway, if we going to use software clipping, we can have several implementations and even switch between them by config setting. It is question of architecture.

**Comment by gonetz** [comment]
> would this scale up well with higher resolutions without performance issues?

RSP clips vertices coordinates with sub-pixel precision. The coordinates then can be converted to floats and scaled as usual. I hope that clipping algorithm with fixed point arithmetic will do the same precision errors as RSP one. There is a hypothesis that polygons misaligned is caused by too precise float point calculations of vertices. It is only speculation though, nobody proved it afaik. Another problem with RSP clipping is that its result is LLE triangle, which has no vertices at all and can't be used for hardware rendering. That is, we need to understand how it works and take only part of it for our implementation. As you may see, this idea has many "if" and no guaranty for a good result.

**Comment by weinerschnitzel** [comment]
I see, thanks. Well if RSP style clipping isn't successful or is slow, we would still need a regular software clipper, and we know that will be fine.

I have other thoughts regarding polygon misalignment. Wouldn't this just fix alignment issues for polygons outside of clip bounds? Anything that is fully within clip bounds will be left as is, and we would still have misalignment there?

Lots of questions and if's. I hope the juice is worth th squeeze!

**Comment by gonetz** [comment]
> I have other thoughts regarding polygon misalignment. Wouldn't this just fix alignment issues for polygons outside of clip bounds? Anything that is fully within clip bounds will be left as is, and we would still have misalignment there?

Yes, polygons misalignment is not directly related to clipping, as it is seen on my screen shots from #1731 
RSP style clipping means that vertex coordinates must be in fixed point format, that is vector and matrix multiplications must be in fixed point. Thus, clipped or not, vertices will slightly differ from ones with float point calculations.

**Comment by olivieryuyu** [comment]
Doing the vtx vector and matrix multiplications could be reversed but the clipping process is quite heavy and difficult.

**Comment by weinerschnitzel** [comment]
I think if aligning triangle coords is 1:1 and neighboring triangle are 1:1 then that would prove reversing the RSP clip algorithm more worthwhile.

Super exciting if it pans out. All the same if we just end with a lesson learned.

**Comment by ToruTheRedFox** [comment]
this could also potentially fix wonky polygon drawing in LLE too

LLE:
![image](https://user-images.githubusercontent.com/15708278/103136017-a585d080-46b4-11eb-8a1d-178f6c9dadcf.png)
HLE:
![image](https://user-images.githubusercontent.com/15708278/103136020-b1719280-46b4-11eb-8a24-1e056beb2fd6.png)
and of course, AngryLion:
![image](https://user-images.githubusercontent.com/15708278/103136027-c2220880-46b4-11eb-87f5-3d384b1b0446.png)

**Comment by gonetz** [comment]
The original issue is fixed.
