### ISSUE TITLE
Difference between the QT and WTL version of this plugin?

### ISSUE THREAD

**Issue by ImSpecial** [gonetz/GLideN64#2393]
Hey Gonetz, no dumb questions right?

I'm a bit confused here, what's the difference between the QT and WTL version of your plugin if I want to use them for Project64? Which one do I use, I currently have the official release one that's v4.0 but that's over a year old!!!, it's also 10MB's in size vs. these smaller ones, 5MB & 1MB~ respectively.

https://i.imgur.com/diXUpRC.png

And also about installing it, I grabbed the latest Project64 dev build from [this link](https://www.pj64-emu.com/nightly-builds) and noticed it already comes with a version of your plugin, but I don't know how old it is, if it's current or different/a custom build, do I just replace the newly downloaded one above with the one already in this GLideN64 Folder that came with Project64? BTW, the one not in this GLideN64 folder shown in the picture is just the old v4.0 release, where I thought it was suppose to go, but now this new folder has me wondering if install location has changed for your plugin.

https://i.imgur.com/71m4quX.png

Also also, 5.0 when! And keep up the great work!!

**Comment by rez-** [comment]
you could also use m64p, it has the latest version of GLideN64, no configuring required! :) 
https://m64p.github.io

**Comment by Jj0YzL5nvJ** [comment]
@rez- , different strokes for different folks. I prefer **_scripted_** mupen64plus-ui-console, someone else will prefer [RMG](https://github.com/Rosalie241/RMG), 1964, BizHawk, OpenEmu, RetroArch or god knows what. Pls don't open Pandora's box.

@ImSpecial , the answer of your question is a pain in the ass, literally. It involves knowledge inherent to anyone who considers himself a programmer. BTW, I'm not a programmer but I have the foundations of one.

> Q: What's the difference between the QT and WTL version of your plugin if I want to use them for Project64?

A: Currently, functions such as configurable hotkeys are missing in the WTL version, but they will be implemented in the future. #1497

> Q: Do I just replace the newly downloaded one above with the one already in this GLideN64 Folder that came with Project64?

A: If you want to guarantee that you are using the latest version, yes.

**Clarifications:**
The size difference between the Qt vs WTL version is because the [WTL](https://en.wikipedia.org/wiki/Windows_Template_Library) only needs some native DLLs in Win10's case, [Microsoft Visual C++ Redistributables](https://support.microsoft.com/kb/2977003) installation for any other Windows. The Qt version embeds all the DLLs inherent to the [Qt software](https://en.wikipedia.org/wiki/Qt_(software)) needed to display the GUI. The mupen64plus version available here has no GUI (only CLI).

Each version of GLideN64 includes the files and folder structure necessary for its correct operation, the only file they all have in common is `GLideN64.custom.ini`. Any file not inherent the corresponding version will be ignored.

Version 5.0 will be released when @gonetz deems it necessary.

**Comment by ImSpecial** [comment]
@Jj0YzL5nvJ 
Thanks, that pretty much answers all my questions, I'll stick with the WTL version I guess as it seems less "bloat" what without the redundant dll files ect., since I'm already on Windows 10, if they do the exact same (minus hotkeys), might as well go with the smaller one.

**Comment by oddMLan** [comment]
Yeah, and Project64 will always come with whatever the latest build of GLideN64 is at the time of the Project64 nightly build. But if there's a newer build of GLideN64 you want to try, you can update the DLL manually, either the WTL or Qt version should work the same (minus the hotkeys part - I'll look into it when I'm done with the semester).

**Comment by ImSpecial** [comment]
Good to know about and how the GLideN64 plugin and Project64 nightly builds relationship works too @oddMLan, so there probably not much difference for me right now, since they were each downloaded not even a day apart, but I'll just grab the latest from here to make sure it's the absolute latest bleeding edge plugin. :P

**Comment by Searinox** [comment]
About 80% of the plugin size was coming from Qt library code. With that removed, the plugin went from 10MB to 2MB.

**Comment by gonetz** [comment]
> Also also, 5.0 when

Soon. May be even earlier.

**Comment by gonetz** [comment]
Issues like this, which actually are not issues but questions, should be opened/asked somewhere else. But where? Discord?

**Comment by oddMLan** [comment]
> Issues like this, which actually are not issues but questions, should be opened/asked somewhere else. But where? Discord?

You could link to the Discord64 server in the README.md or the Wiki and tell people to check the #gliden64 channel once they verify themselves. But you'll need to check every once in a while or have Discord running in the background. People can tag you and get notified as well. The nice thing is that other people can answer since it's a public medium unlike email or something like ask.fm

**Comment by ImSpecial** [comment]
Not everyone wants to create an account/sign up to the latest facebook, twitter, discord, latest trend just to ask a simple question. I have no desire to ever use Discord, and not just because it's a privacy nightmare. I don't see the issue (Ha) with just asking things here, maybe have some kind of tagging system in place for different things, like "Question", "Bug", "Regression", etc. so people can tag and filter accordingly, and if you find things getting out of control maybe a Mega thread or similar for all general talk/questions, something like this. https://github.com/Aris-t2/CustomCSSforFx/issues/308

**Comment by dezraj** [comment]
I was also trying to update my GlideN64 plugin and didn't know which version I had to download. Then I looked for "gliden64 wtl qt cli" on Google and this page was the first result. Perhaps an explanation could be placed in the GitHub Actions page to help people distinguish the versions' differences.

And if anyone else who came here is also wondering what the acronyms in the builds mean:

CLI: Command-line Interface (so no graphical user interface for this version)
QT: (pronounced "cute") cross-platform software for graphical user interfaces
WTL: Windows Template Library, free library for developing Windows applications and user interface components.

**Comment by Jj0YzL5nvJ** [comment]
> I was also trying to update my GlideN64 plugin and didn't know which version I had to download. Then I looked for "gliden64 wtl qt cli" on Google and this page was the first result.

Congratulations, not all users get the lightbulb moments.

> Perhaps an explanation could be placed in the GitHub Actions page to help people distinguish the versions' differences.

To users it's better to let them know the minimum amount of information possible or you will end up confusing them or wondering _And which one is better?_
If we were to tag the binaries with the build **subsystem** and **tools**, the end user would literally go nuts.

You can also build against MinGW with other varieties of subsystems ([MXE](https://mxe.cc/), [MSYS](https://en.wikipedia.org/wiki/MSYS), [MSYS2](https://en.wikipedia.org/wiki/MSYS2), [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), etc, etc, etc). Let's not touch on the MSVC **shared** build variants... the iceberg can go deeper.
Thank goodness @gonetz only distributes binaries for [MSVC](https://en.wikipedia.org/wiki/MSVC) **static** subsystems, yet there are always "astray" users of Libretro subsystems reporting bugs here.

I remember a user on reddit asking which [DuckStation](https://github.com/stenzek/duckstation) executable was better for his PC ([Qt](https://en.wikipedia.org/wiki/Qt_(software)) vs [SDL](https://en.wikipedia.org/wiki/Simple_DirectMedia_Layer)) and users giving him more information only ended up confusing him more and more. The ironic part is that for DuckStation users, "sdl" is the equivalent of "nogui" (CLI). Which puts in evidence that none of the said users tried to run the version incorrectly labeled as "sdl" to see if it even "worked" (IT RUNS AND CLOSES! Exclaimed the ignorant user). Current versions have already changed the misleading "sdl" tag to "nogui" (CLI).
