### ISSUE TITLE
WipEout 64 Texture Pack

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#2423]
Hello!

NR74W is known to make some great texture packs for WipEout games. He recently did one for WipEout 64, but there as some issues when using it with GLideN64. As described by NR74W himself:

- At the present time, no emulator / plug-in can correctly display the textures of WipEout 64. The textures had to be edited to work around this problem.
The normal HD textures can be found in the master branch, in case this issue is resolved in the future. It is not usable yet.
In the "workaround" branch are stored the modified textures which can be rendered correctly (hack).

- Tested on Project64 2.4.0 / GlideN64 4.0 Public Release (does not work on the latest version of GlideN64).

Do you know why these issues happen and can you fix them? I've tried using it on the latest version of GLideN64, but there are a lot of black stripes over the textures.

Link to the texture pack: https://github.com/NR74W/WipEout-64-HD-Texture-Pack

**Comment by gonetz** [comment]
Bisected to 0338f27225

**Comment by gonetz** [comment]
I've analyzed the first screen of Wipeout64.
Everything is rendered by triangles (not a texrects) in 1-cycle mode.
Texture filtering is off. Texture clamping is off. Texture mask is 0.
It looks ok with original textures with the master build, with only few minor artifacts:
![1](https://user-images.githubusercontent.com/8983092/104088820-2e4b6180-529c-11eb-9dbc-76150321f3e1.png)


Hires pack has black lines in the logo:
![2](https://user-images.githubusercontent.com/8983092/104088829-3a372380-529c-11eb-9d12-e77979dd51be.png)

I made an experiment: 
I dumped original textures for this screen and magnified them 16x times to get textures of the same size as in the texture pack.
I load these magnified textures as HD texture pack and got nearly the same picture as with original textures:
![3](https://user-images.githubusercontent.com/8983092/104088834-3efbd780-529c-11eb-9390-81f21c893fa1.png)

I suppose that there is a problem with the hd pack. Probably textures are shifted by pixel or there are black pixels on texture's edge.
If everything is done right, texture pack should have the same artifacts as the pack with magnified original textures.
@NR74W please check it. I attached the magnified textures I used for testing.
[Wipeout 64_magnified_original_textures.zip](https://github.com/gonetz/GLideN64/files/5790457/Wipeout.64_magnified_original_textures.zip)


There is a problem on plugin side though. Public Release 4.0 renders this screen without visible artifacts:
![4](https://user-images.githubusercontent.com/8983092/104088855-520ea780-529c-11eb-8404-fe937bd4bbdf.png)

The artifacts are caused by changes from commit 0338f27, which fixes #2097.
If I revert that commit (that is set offsetS = 0.5f and offsetT = 0.5f) the artifacts gone as well as the issues with the texture pack.

@standard-two-simplex do you have any idea what may cause these artifacts? Textures for the logo have size 32x30.
Texture coordinates (0.0,0.0)-(31.0, 29.0) No clamping, no wrapping, no filtering.
![5](https://user-images.githubusercontent.com/8983092/104088936-04466f00-529d-11eb-80a7-64dee5d183ff.png)

**Comment by standard-two-simplex** [comment]
What are the width and height of the triangle? Do a pair of triangles form a rectangle of size 32x30?
Another thing that affects texture coordinates are tile attributes. Do you know what SL and TL are for that tile?

**Comment by standard-two-simplex** [comment]
It seems they are screen space triangles. The scene renders correctly in LLE, better even than HLE before 0338f27.

I am not very sure where LLE and HLE differ, but I believe the wrong vertex position reach the rasterizer, which end up generating wrong texture coordinates.

**Comment by gonetz** [comment]
> The scene renders correctly in LLE, better even than HLE before

Indeed! Great, that you noticed it. LLE renders this screen using texrects. Logo texrects use texture coordinates (0, 0) - (32, 30)
HLE uses gSPSprite2D:
http://n64devkit.square7.ch/n64man/ucode/gspSprite2D.htm
GLideN64 implementation renders backrounds using triangles. Logo texture coordinates calculated as (0, 0) - (31, 29)
It is because of 
```
	f32 lrs = uls + pSprite->imageW - 1;
	f32 lrt = ult + pSprite->imageH - 1;
```
This code came from Glide64. I don't remember for which purpose that -1 was added. I removed it (7d237650) and did not find any regression. The HD pack by @NR74W looks just fine, but only **master** version, not the **workaround** one:
![GLideN64_Wipeout_64](https://user-images.githubusercontent.com/8983092/105630588-a610b300-5e7c-11eb-9e47-0878d958bd2e.jpg)

**Comment by gonetz** [comment]
@DonelBueno please check the HD pack (from its master branch) with the latest master build.

**Comment by standard-two-simplex** [comment]
> 	f32 lrs = uls + pSprite->imageW - 1;
	f32 lrt = ult + pSprite->imageH - 1;

Gosh, I cracked my head for a few hours and couldn't find the source of the issue. Now I feel stupid. xD

**Comment by DonelBueno** [comment]
Nice, I'm goingo to test soon.

Strangely, I didn't receive any notifications about this thread.

**Comment by gonetz** [comment]
> Gosh, I cracked my head for a few hours and couldn't find the source of the issue. Now I feel stupid. xD

I started to check textures coordinates using GLideN64 debugger.
I was surprised to see that HLE uses triangles while LLE uses texrects, so I dumped a debug log. The log showed the actual command for the backgrounds.



> the master branch pack worked perfectly, thanks for the fix.

Good. Close then.

**Comment by aybe** [comment]
> @standard-two-simplex do you have any idea what may cause these artifacts? Textures for the logo have size 32x30. Texture coordinates (0.0,0.0)-(31.0, 29.0) No clamping, no wrapping, no filtering. ![5](https://user-images.githubusercontent.com/8983092/104088936-04466f00-529d-11eb-80a7-64dee5d183ff.png)

@gonetz could you explain how to debug textures like you did in the screen above? thanks :)

**Comment by gonetz** [comment]
> @gonetz could you explain how to debug textures like you did in the screen above? thanks :)

It is build-in debugger. It is available only in debug builds. That is, you need to build the plugin from sources in Debug configuration. Press ScrollLock, then Insert and debug mode will open. press 0-9 to switch between panels with debug info.
Unfortunately, the debugger was heavily broken after commits with texture fixes, and currently is barely usable.

**Comment by aybe** [comment]
Great, that worked, thank you! 😁
