### ISSUE TITLE
Pixel Coverage is being enabled by default

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2426]
Per discussion on issue #2401, coverage generates a performance hit on low end devices, and most of the time it makes no difference, so the option should be disabled by default no?

How I reproduced:
- Downloaded latest GLideN64 Qt for Project64
- Changed plugin in settings
- Opened Plugin config, saw that coverage is enabled by default
- "Reset to defaults" still keeps the option enabled.

I think despite the performance hit it should enabled as a ini entry for games where it will make a difference, like Turok and Pokemon Snap (see issue #1938).

**Comment by CallistoNTG** [comment]
It's more accurate behavior, and it's best to assume a game is using pixel coverage for something, somewhere. N64 pixel coverage is the reason real N64s and accurate emulators don't have seams everywhere. Fixing that issue will likely require pixel coverage as a baseline.

GLideN64 ought to aim to be as reasonably accurate out of the box as possible. If people's hardware can't handle pixel coverage, then they should turn it off. In contrast, the reason accurate N64 depth compare isn't enabled by default is because the performance impact of that setting was rather severe. I don't think pixel coverage is anywhere near as high impact as depth emulation on desktop PC hardware.

**Comment by oddMLan** [comment]
>N64 pixel coverage is the reason real N64s and accurate emulators don't have seams everywhere. Fixing that issue will likely require pixel coverage as a baseline.

How confident are you about this? The seams problem seems more like a floating point precision issue.

**Comment by CallistoNTG** [comment]
If you take Angrylion's software plugin and remove VI filters on a game like Perfect Dark, seams appear. Even on real hardware you can glimpse seams on some surfaces at the right angle & distance. There is possibly an additional precision issue, but as mentioned in [this](https://github.com/gonetz/GLideN64/issues/2397) issue, there are N64 games where two planes are misaligned, but a real N64 renders them as a contiguous surface because of how its anti-aliasing system works.
