### ISSUE TITLE
Black Squares? or something like that? Mario Kart 64

### ISSUE THREAD

**Issue by RedEBoi** [gonetz/GLideN64#2477]
![image](https://user-images.githubusercontent.com/82115989/113915283-fbd6d500-97b4-11eb-8b55-e756478fd9c9.png)

Is there a way to fix this? im using retroarch Mupen64Plus-Next

Also srry for my bad english, my main lenguage is Spanish

**Comment by IronYoshi64** [comment]
I think I found the reason. The culprit is having the **Native res. 2D texrects** On, which is forced when having the **INI Behavior - Prioritize INI over Core Options** On. Setting that to **Prioritize Core Options over INI**, and making sure **Native res. 2D texrects** to Off fixes the weird issue with the invisible cursor box and the character select screens. But this does cause bad lines all around the images in menus and the character select screen.

I wonder if this is also an issue in standalone GLideN64 with PJ64, or just a RetroArch core regression?
I will test that in a few.

**Comment by IronYoshi64** [comment]
Yup, in Latest Dev build of PJ64 with GLideN64 latest master version, it is perfectly fine. So my theory is that either there is a regression in latest mupen64plus_next core or the INI file is not setup correctly by default for the game.

**Comment by otorre** [comment]
I just faced the same issue and solved by turning ON "Less accurate blending mode"

**Comment by Syntaxrabbit** [comment]
> I just faced the same issue and solved by turning ON "Less accurate blending mode"

This was indeed the solution.
