### ISSUE TITLE
Mario Kart 64 - HD textures show lines

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2487]
Depending on the internal resolution the game is rendered with as well as the resolution factor of the HD textures, one may or may not experience lines with textures that are split.

The title background is combined 1920x1440, which equals an upscale factor of **6x** (original: 320x240). Using the option to use a multiple of the N64's native resolution factor, using **6x or lower** will not display any lines. Using **7x or higher** will however. Same logic applies to the "same as output resolution" option. So in this example a 1080p user will not experience issues in fullscreen while a 2160p user will.

1x-6x:
![image](https://user-images.githubusercontent.com/31742919/116314422-62955000-a7af-11eb-893b-a1e2cdb2fc3f.png)

7x-16x:
![image](https://user-images.githubusercontent.com/31742919/116314443-688b3100-a7af-11eb-98a4-f5f7ecc7cfae.png)

HD Title Background:
[title-background.zip](https://github.com/gonetz/GLideN64/files/6387723/title-background.zip)

**Comment by gonetz** [comment]
The problem seems to disappear if "inaccurate texture coordinates" option is used.
May be @standard-two-simplex can explain why the seams between tiles appear with accurate texture coordinates in resolutions above 6x native?

**Comment by standard-two-simplex** [comment]
If I recall correctly the game issues several texture rectangle commands to copy the background. The rectangles have full screen width and one or two pixel height (can't recall which).

Even if the game sets the filtering mode to bilinear, the texture coordinates generated fall on top of the samples, so no filtering occurs. This is, the `t` coordinates generated are integers, so the bilinear filter generates the same result as a nearest neighbour filter. It would be better to use a nearest neighbour filter for this, but in the case of native resolution, the output is identical.

When you raise the internal resolution, more pixels are needed. For example, rendering in 2x two samples will be needed where one was needed before. The new method spaces this samples equally between the whole range. In other words, in 1x integers `0,1` are two evenly spaced numbers between `[-0.5,1.5]`. When splitting this range in four, the texture coordinates generated will be `-0.25,0.25,0.75,1.25`. The samples in between correctly mix neighbouring texels. However, the samples on the edges will wrap and mix partly with pixels on the other side of the texture, creating the visual artifacts. The higher the resolution, the farther the last samples will be from `0` and `1`, so the artifact will be more and more noticeable.

In order to avoid this, the game should design the split textures as having one common pixel on the edges so that it is possible to filter using them instead of wrapping. I beilieve the game itself doesn't do so, making it is impossible to filter correctly.

When using HD textures, those numbers are added 0.5, multiplied by the HD ratio and subtracted 0.5. So for 4x the original textures in 2x internal resolution you would get coordinates `0.5,2.5,4.5,6.5`, which filters correctly. But in 8x internal resolution they would be `-0.25, ... , 7.25`, which doesn't filter correctly.

The textures you posted are 6x the height of the original one, so the scene renders correctly up to 6x internal resolution.

I believe the old branch generates coordinates differently, which may produce artifacts in other games/situations, but doesn't in this one.

I wouldn't consider this a bug of the plugin, but a result of a poor game design, which allows correct image only in native. The best workaround is, in my opinion, targetting a certain resolution and making the HD textures using the same ratio, i.e, 4x textures for 4x internal resolution, 8x textures for 8x internal resolution etc. Not only it will look ok in this situation, but they'll look better than downsampled big textures, specially with 2D.

**Comment by GhostlyDark** [comment]
Thanks for the explanation.

To sum up, there are three ways around this:
1. Increase the resolution of the HD background
2. Limit the output resolution (in this case: 6x or lower)
3. Use inaccurate texture coordinates option
