### ISSUE TITLE
[feature request] option to chose which screen to go full screen on.

### ISSUE THREAD

**Issue by nick1802** [gonetz/GLideN64#2513]
Im wondering if there's a chance to add a option to select what screen goes it go to in full screen.
at the moment it only goes full screen on screen that is primary.

**Comment by gonetz** [comment]
It hardly possible with mupen64plus, because rendering context created on emulator's side.
It is probably possible with Project64, but it should be emulator's option, because emulator provides plugin the handle to render window. Probably it is not possible: https://stackoverflow.com/questions/28491806/opengl-on-a-secondary-display

**Comment by gonetz** [comment]
Rosalie241created a PR to add multi-monitor support:
https://github.com/gonetz/GLideN64/pull/2578

Please check these builds:
https://github.com/gonetz/GLideN64/actions/runs/1246282372

It does not work on my hardware, but may be it will help you.

**Comment by gonetz** [comment]
@nick1802 Please try builds from #2686 for Project64
New "borderless window" option supports monitor selection.
I still don't know, how to select non-primary display for true fullcreen mode, but "borderless window" should work with any monitor you have attached.

**Comment by gonetz** [comment]
Fixed with PR #2686
