### ISSUE TITLE
Artifacts older than 1 month are automatically deleted

### ISSUE THREAD

**Issue by anonymous7002** [gonetz/GLideN64#2530]
This means I can't download master builds if the latest commit was done over a month ago.

**Comment by IronYoshi64** [comment]
Yeah I agree this is a very bad idea, I don't like that this happens either. Is there a certain build you wanted to get?

I do have an old QT version of 189afd39, which is what I recommend right now due to newer ones having some regressions, etc.

[GLideN64-189afd39-QT_for_Project64.zip](https://github.com/gonetz/GLideN64/files/6850082/GLideN64-189afd39-QT_for_Project64.zip)

**Comment by Jj0YzL5nvJ** [comment]
https://ci.appveyor.com/project/gonetz/gliden64/builds/39800958/artifacts
https://ci.appveyor.com/project/gonetz/gliden64/builds/40020772/artifacts
https://ci.appveyor.com/project/gonetz/gliden64/builds/40031687/artifacts

**Comment by gonetz** [comment]
AppVeyor changed their 'Artifacts retention policy'. It was 6 months, now it is just one month.


> Yeah I agree this is a very bad idea, I don't like that this happens either.

Any suggestions?

**Comment by IronYoshi64** [comment]
I think Gitlab and travis are also a thing, but I have no idea on how to navigate those very well, or how good those would be.

**Comment by Jj0YzL5nvJ** [comment]
Pre-releases or mirrors...

**Comment by standard-two-simplex** [comment]
I don't know how to set it up, but I believe GitHub Actions allows publishing/updating a release whenever a commit is pushed to master.

https://github.com/gonetz/GLideN64/actions

**Comment by anonymous7002** [comment]
I would also suggest a version with -DMUPENPLUSAPI_GLIDENUI to be built in Appveyor.
