### ISSUE TITLE
Kirby 64 breaks when changing between full screen and windowed

### ISSUE THREAD

**Issue by xiartic** [gonetz/GLideN64#2563]
Parts of the right side of the screen gets more and more misaligned and garbled up every time you change between full screen and windowed.

Latest PJ64 and GLideN64 nightly.
![GLideN64_Kirby64_000](https://user-images.githubusercontent.com/78692485/131245244-cbc0731b-a319-4e27-8e67-1bba2f0ebbc4.png)
![GLideN64_Kirby64_001](https://user-images.githubusercontent.com/78692485/131245245-010140df-be96-4c7e-a786-946eb1734b0b.png)

**Comment by gonetz** [comment]
It can't be fixed because of the way that game is programmed.
The border is rendered only once at the level start. After that only part of image inside the border is updated. When you switch windowed mode, graphics context is re-created. Border is not restored because the game does not render it Thus, you have garbage on this place.
