### ISSUE TITLE
[Feature Request] Option to respect texture format and size

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2569]
Same texture, different texture format. First dump is a water bubble, second one is a blood effect during the fight against Barinade. Current behaviour retextures both instances with one and the same HD texture.

I'd like to suggest a checkbox to control whether or not texture format and size information is ignored. Current behaviour should remain the default as it would otherwise break tons of texture packs. Such an option can fix instances like these and can help in uncovering wrong texture names.

**Current behaviour:**
![image](https://user-images.githubusercontent.com/31742919/132851106-4e8c5632-acb3-4135-af6e-219c3a963789.png)

**What is should look like:**
![image](https://user-images.githubusercontent.com/31742919/132851128-7da2bdd3-8b1f-425b-bdb8-ee1ee1fd55a2.png)

**Bubble texture (the one with more transparency):**
![image](https://user-images.githubusercontent.com/31742919/132851175-6446e3f5-6361-4171-a40d-7c53ee0efd15.png)

**Vanilla textures:**
THE LEGEND OF ZELDA#AE749099#3#1_all.png
![THE LEGEND OF ZELDA#AE749099#3#1_all](https://user-images.githubusercontent.com/31742919/132669511-d43ffbf2-7566-403b-af0e-57c4dad38a8a.png)

THE LEGEND OF ZELDA#AE749099#4#1_all.png
![THE LEGEND OF ZELDA#AE749099#4#1_all](https://user-images.githubusercontent.com/31742919/132669527-8a4d60e6-b4cc-46ea-8717-cb3e2c88e71f.png)

**Ocarina of Time 1.0 (USA) Savestates:**
[bubble.pj.zip](https://github.com/gonetz/GLideN64/files/7143599/bubble.pj.zip)
[blood.pj.zip](https://github.com/gonetz/GLideN64/files/7143600/blood.pj.zip)

**HD textures:**
[bubble-textures.zip](https://github.com/gonetz/GLideN64/files/7143602/bubble-textures.zip)

**Comment by gonetz** [comment]
Thanks for detailed FR!

>I'd like to suggest a checkbox to control whether or not texture format and size information is ignored.

The texture size and format information is not ignored.
As you noticed: "Same texture, different texture formats".
The texture is indeed the same, with the same checksum.
Current tex cache code distinguishes textures only by checksum.
Textures with the same checksum treated as duplicates, duplicate is removed.
If you use only one of these two textures, it loads correctly.
If you use both, 'THE LEGEND OF ZELDA#AE749099#3#1_all.png' loads first.
'THE LEGEND OF ZELDA#AE749099#4#1_all.png' has the same checksum as the first one and thus not loaded at all.
Note, that such situation is quite rare.
To solve the problem, we need to add texture format and size to cache's key.
It will change format of texture pack cache file. That is, existing texture cache files will be necessary to update.
It is not always possible, since some packs distributed only as cache file, without hd textures.
Unfortunately, I did not foresee the need for version support. It can be problematic to distinguish old and new formats and
load them automatically. I'll try to do it, but probably some user option will be necessary.

**Comment by fzurita** [comment]
To distinguish, you could add a magic keyword at the beginning of the file. If the keyword doesn't exist, then it means it's the old format.

**Comment by gonetz** [comment]
@GhostlyDark
PR created: #2640
Please test it.

**Comment by GhostlyDark** [comment]
**Functionality**
From what I can tell the PR works as it should. I wasn't able to spot any regressions.

**Cache compatibility**
Old HTS/HTC files are working with the PR build as if nothing has changed, which is good.

There's an incompatiblity the other way around (loading new cache file in older build):
- Emulator freezes when attempting to load the first texture when no PNG textures exist
- GLideN64 rebuilds cache if PNG textures are present

Any tools to extract or convert new cache files fail to do so ([gliden64-cache-extract](https://github.com/ecsv/gliden64-cache-extract) / [HTC2uHTS](https://github.com/Rosalie241/texturepack_utils)).

**Toggling old behavior**
Is it feasible to implement an option to ignore the texture format? As existing cache files lack that information, cache extracts default to the `#3#0` texture format for all extracted textures resulting in a lot of HD textures not loading using the current PR build. Emulationking for instance hosts such cache extracts as PNG download options for Djipi's Zelda packs.

A workaround I can think of is to build a cache file with an older GLideN64 version and use that with a newer GLideN64 build.

**Comment by gonetz** [comment]
All texture pack convertors should be rebuilt after this feature included to master.

> A workaround I can think of is to build a cache file with an older GLideN64 version and use that with a newer GLideN64 build.

Workaround for what? A cache built with older GLideN64 version can't contain several textures with the same checksum, so the original problem will not be solved.
If you want to distribute your texture pack in  a form of cache file, and you need to make it compatible with older GLideN64 versions, you indeed should use older GLideN64 version for that. I can add an option to save cache in the old format, but is it really necessary?

**Comment by GhostlyDark** [comment]
> If you want to distribute your texture pack in a form of cache file, and you need to make it compatible with older GLideN64 versions, you indeed should use older GLideN64 version for that. I can add an option to save cache in the old format, but is it really necessary?

There are two things that concern me here:

1. New cache formats break/won't load in older GLideN64 builds. For legacy support, I'd have to use older GLideN64 builds to build the files.

An option to switch to the old format wouldn't necessarily solve anything here. It would allow creators to use the newest GLideN64 to build the old cache format for compatibility reasons. However, if you want the new cache format to be the default (which makes sense because it's more accurate), then I don't think that option is really worth it. It may end up confusing users more than it is worth implementing. If possible, just use PNG files.

2. Any user building their own PNG pack from a cache extract will experience missing HD textures whenever they update GLideN64.

I'd expect user reports on this eventually (from e.g. Djipi pack users). I can create renaming scripts without much effort that will fix the texture format in the texture file names for any games that I have personally worked on.

Maybe this cache format change is worth mentioning in the Wiki as this is a breaking change? All in all, I think the PR is good to go.

**Comment by GhostlyDark** [comment]
Scripts are public:
https://github.com/GhostlyDark/Texture-Scripts

One thing I noticed is that the texture size is still being ignored. Is it intentional?
For instance:

**Dump:** `THE LEGEND OF ZELDA#9D8F7B68#0#3_all`

`#1#0, #2#1, #3#0` do not load (texture format mismatch)
`#0#1, #0#2, #0#4` all load (texture format matches, size mismatch)

**Comment by gonetz** [comment]
Cache extracting is a matter, which I did not think of.
Originally, texture cache was invented by KoolSmoky as a fast way to load hi-res textures.
Rice format implies that texture pack distributed as a set of properly named image files.
Collecting all textures from a pack is slow. Texture cache loads all textures at once and converts them into OpenGL (originally Glide3x) texture formats. If user changes some parameters of the cache, the cache is re-generated from the image files.
That is initially the cache was not intended to replace the image files texture packs.
Later some texture artists decided to distribute their work in the form of texture cache, considering it as a form of DRM protection. It is an ill idea, the pack was not intended for it. Since the plugin is open source, creation of cache extraction tools was a matter of time. There is a problem with it: "due to GLideN64's cache format lacking the texture format and size information ...". Texture format and size information was not necessary to find HD texture in the cache, it is useful only for optimal conversion of texture image to OpenGL format. Now, when you found that the same texture data can be used for different texture formats, I changed cache format and included texture format information. Why I did not include the texture size information as well? I can't imagine the situation when the same texture data can be used for different textures of the same format but different texel size. That is CRC + format should be enough.
I packed texture format information into existing data structures, which are used for old cache format. So, cache size did not change. That was not exactly necessary, just made code changes simpler. The were no free room for size info though. Again, I did not think about possibility to extract the cache file. If this feature is really useful for users, I can store texture size information in the cache as well. That will make cache extraction as simple as possible. As I said, I don't like use of cache file as a DRM protection. If some texture artists want to use it that way, ok, old formats allow doing that. New cache format can be made more user-friendly.

**Comment by GhostlyDark** [comment]
Cache extraction is misused as (useless) DRM, that is unfortunately true. It's not all evil though, it can be used for debugging:

- See how much space a texture occupies in an uncompressed cache
- See how type 4 textures get modified
- Extract transparent type 4 textures without having to mess with the alpha channel yourself

Cache extraction aside, it might make sense to add the size to the cache format just in case. I don't know of any edge cases with the texture size, but I don't want to see the cache format have to change again.

**Comment by gonetz** [comment]
> I don't want to see the cache format have to change again.

Good point. I made another attempt. Please test: #2640

**Comment by gonetz** [comment]
Done, 58faa2874a6ee, #2640

**Comment by GhostlyDark** [comment]
For the sake of documentation:
Super Mario 64 uses a water texture for the fog in Shifting Sand Land. Same hash, different texture format.

![image](https://user-images.githubusercontent.com/31742919/213538116-2fa1ac8d-2ed0-43f6-95c1-26686f68d148.png)

![SUPER MARIO 64#DFFBB688#0#2_all](https://user-images.githubusercontent.com/31742919/213538066-e0599b9d-a993-4861-93ef-576fda5767fb.png)

![SUPER MARIO 64#DFFBB688#3#2_all](https://user-images.githubusercontent.com/31742919/213537933-a9192297-7df0-4189-ae9d-3801a7491bce.png)

The new texture cache format allows this to be retextured properly.
