### ISSUE TITLE
PD odd glitches with widescreen hack

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2619]
There seem to be issues with the widescreen hack and perfect dark.
![Perfect Dark (U) (V1 1)  !](https://user-images.githubusercontent.com/11581687/145659430-54c4088c-4725-4dda-abdf-19c30aa8847b.png)

Even in the non-extended areas there are issues.

**Comment by Nejsplitter** [comment]
i think this game has its own built in widescreen 16:9 option in game settings

**Comment by fzurita** [comment]
Yeah, that's true.

**Comment by Nejsplitter** [comment]
Happy new year to you and @gonetz and the rest of the devs 🎉🎉😀👍
thanks for all you guys do :)

**Comment by gonetz** [comment]
widescreen hack modifies coordinates of all 3D polygons, including the ones inside the original viewport. These black polygons are probably part of auxiliary geometry, which normally should be hidden, but became visible after coordinates modification. The problem probably can be fixed with a hack, but it is better to use built in widescreen 16:9 option.

**Comment by gonetz** [comment]
> Happy new year to you and @gonetz and the rest of the devs 🎉🎉😀👍 thanks for all you guys do :)

Thanks!
