### ISSUE TITLE
many coding for pokemon stadium /PS2 is unhandled/unused...

### ISSUE THREAD

**Issue by overlordchaos** [gonetz/GLideN64#2652]
this games has insane level of tricks, and hacks to truly use 100% of the nintendo 64 resources and are unhandled. many many minimal graphical mistakes are present since the original creator (witch we talked and help him to debug releases on this games) told me "well i am not wasting time on two pokemon games so while they work thats the state they will remain in" witch is not what a developer should think. whatever special code PS/PS2 uses could be used on other N64 games as well.

**Comment by gonetz** [comment]
Why it is here?

**Comment by gonetz** [comment]
If you are talking about unhandled microcode commands, there are no one. The plugin handles all the commands. There is nothing special in PS/PS2 microcodes. The glitches in these games are mostly caused by "insane level of tricks" with frame buffer. Frame buffer effects are hard to emulate on PC hardware.
Anyway, logging unhandled commands is a good idea. I made it in commit 1a711257ed7.
If there is an unknown command, Message "UNKNOWN GBI COMMAND" will appear in gliden64.log

**Comment by overlordchaos** [comment]
> If you are talking about unhandled microcode commands, there are no one. The plugin handles all the commands. There is nothing special in PS/PS2 microcodes. The glitches in these games are mostly caused by "insane level of tricks" with frame buffer. Frame buffer effects are hard to emulate on PC hardware. Anyway, logging unhandled commands is a good idea. I made it in commit [1a71125](https://github.com/gonetz/GLideN64/commit/1a711257ed78131aff4d0e39933df14082f52f0c). If there is an unknown command, message "UNKNOWN GBI COMMAND" will appear in gliden64.log

would you do a new release with this change? will love to give it a test but dont know how to compile it. as well would you do nightly (even if it is like once a week) releases with newer changes???

**Comment by Jj0YzL5nvJ** [comment]
:facepalm:

> would you do a new release with this change? will love to give it a test but dont know how to compile it. as well would you do nightly (even if it is like once a week) releases with newer changes???

https://github.com/gonetz/GLideN64#readme
