### ISSUE TITLE
64 de hakken HLE not working.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#268]
GFX issues in HLE, not so bad but very slow in LLE

**Comment by olivieryuyu** [comment]
custom microcode, it uses texture with different flags

**Comment by olivieryuyu** [comment]
F3DTEX/A is the microcode. it is slighty different than the F3DEX but not much i guess

TEX stands certainly for texture.

**Comment by olivieryuyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8987490/21080786/02b70bbc-bfb8-11e6-9a3d-244c37b4b243.png)

The TRI command is slightly different.

**Comment by LegendOfDragoon** [comment]
How do you know that's the tri command? I've been wanting to HLE gfx microcode for a while now, but never figured out where each function was located. I ended up learning HLE audio since I located good docs that helped me figure out where the audio functions are located.

If I could understand how Gonetz was able to implement Turbo3D and Zsort, it could help me a lot. I understand RSP code very well, I just don't see much of a resemblance between RSP code and the current HLE code.. I'd also like to figure out how to HLE the RDP since that's the main bottleneck, most of the time.

**Comment by Gillou68310** [comment]
@olivieryuyu having different jump targets doesn't always mean that the code is different it could be just an additional nop instruction somewere that shifts instruction address + jump targets.

**Comment by olivieryuyu** [comment]
@Gillou68310 

yes you are right the instruction address where simply shifted!!!

![image](https://cloud.githubusercontent.com/assets/8987490/21083499/30b6c6f8-bff2-11e6-8c44-adeff958749b.png)

**Comment by gonetz** [comment]
> If I could understand how Gonetz was able to implement Turbo3D and Zsort, it could help me a lot.

There are GBI.h for both ucodes. Also, olivieryuyu found two demos with sources for Zsort. It helped me greatly to understand, how it works.

**Comment by gonetz** [comment]
> I'd also like to figure out how to HLE the RDP since that's the main bottleneck, most of the time.

HLE RDP is oxymoron. There is no software layer over RDP, which you can emulate on High Level.

**Comment by LegendOfDragoon** [comment]
I use this plugin when profiling CPU or RSP.
https://www.dropbox.com/s/pd2xe3rf13qu108/NO%20VIDEO.dll?dl=0

>HLE RDP is oxymoron. There is no software layer over RDP, which you can emulate on High Level.

If that's the case, why are HLE plugins so much faster in games where RSP is hardly being used? For example on my laptop, Tower and Shaft only uses 7% of a cpu core on RSP gfx when using PJ64's RSP interpreter, yet the performance difference between HLE and LLE plugins is greater than that.

I only say that because HLEing the RSP for WDC won't give me the speed boost I need, to run it full speed on my laptop. So I'll need to speed up the RDP too.

>Also, olivieryuyu found two demos with sources for Zsort. It helped me greatly to understand, how it works.

Thanks for the tip. Where can I find these 2 demos with sources?

**Comment by gonetz** [comment]
> If that's the case, why are HLE plugins so much faster in games where RSP is hardly being used?

RSP plugin. It still does its work for translating HLE display list to LLE one.
Also, GLideN64 has rooms for optimization for LLE mode. But it has nothing with HLE.

> Where can I find these 2 demos with sources?

I'll search for them in my archives.

**Comment by olivieryuyu** [comment]
ok so for turbo3d, here the sample:

[gt.zip](https://github.com/gonetz/GLideN64/files/645308/gt.zip)
[blocks turbo.zip](https://github.com/gonetz/GLideN64/files/645309/blocks.turbo.zip)

**Comment by olivieryuyu** [comment]
and the Zsort:

[Zsort.zip](https://github.com/gonetz/GLideN64/files/645351/Zsort.zip)

Both ucodes are explained in devkit.

WDC is a modified version of Zsort as per the devs of the game themself. Will be not easy to RE I think.

**Comment by olivieryuyu** [comment]
@gonetz 

first time i heard about the word "oxymoron". I learn every day something :)

**Comment by gonetz** [comment]
:)

**Comment by LegendOfDragoon** [comment]
>RSP plugin. It still does its work for translating HLE display list to LLE one.
Also, GLideN64 has rooms for optimization for LLE mode. But it has nothing with HLE.

I see.

@olivieryuyu thanks for the sources. It will be useful for HLE development. i think I'll look into Turbo3D.

>WDC is a modified version of Zsort as per the devs of the game themself. Will be not easy to RE I think.

I honestly could not see a resemblance between Mia Hamm (which uses Zsort) and WDC. WDC is not that hard because there isn't much microcode.

**Comment by olivieryuyu** [comment]
Well I contacted the devs a long time ago. They could not help out or were not keen on helpinp out, which is understandable of course. The only ucode i have no clue about are the ones from Factor 5. May be they wrote them from scratch, which would be quite amazing imo.

**Comment by olivieryuyu** [comment]
The additional command(s) seems to be related to a matrix. A wild guessing lead me to guess a texture matrix stack.

May be I am totally wrong. I have not enough skills to decode further :(

**Comment by olivieryuyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8987490/22175476/96efb0d8-dff5-11e6-9674-9702164e1679.png)

There is 2 new commands in this ucode which are actually not standard.

0XB5 and 0XBE

**Comment by olivieryuyu** [comment]
Finally understand how the command works. Nothing to do with a texture matrix, they seems just texture related commands.

**Comment by olivieryuyu** [comment]
@gonetz : It seems that both 0xB5 and 0xBE are used jointly (as RDPHALF 1 & 2). Weird

**Comment by olivieryuyu** [comment]
:D

![success](https://cloud.githubusercontent.com/assets/8987490/22455957/d315e5d6-e78f-11e6-9594-67ef1c9b1fd1.jpg)

**Comment by olivieryuyu** [comment]
and another game HLEZied!!! Great stuff!!!

**Comment by weinerschnitzel** [comment]
Nice work olivieryuyu!

**Comment by olivieryuyu** [comment]
i guess we can close this ticket
