### ISSUE TITLE
question about buffer swap 

### ISSUE THREAD

**Issue by Nejsplitter** [gonetz/GLideN64#2827]
hi @gonetz , in vi.cpp what does this line do?

bNeedSwap = bCFB ? true : (gDP.colorImage.changed != 0);

and this one:

bNeedRender = (gDP.changed & CHANGED_COLORBUFFER) != 0;

also, is it possible to not use buffer swap at all like original gln64 did?

**Comment by gonetz** [comment]
bNeedSwap - swap buffers required.
bCFB - color frame buffer was modified by CPU, we need to swap buffers to show these modifications
gDP.colorImage.changed != 0 - there were modifications of color frame buffer since the previous VI_UpdateScreen() call

bNeedRender = (gDP.changed & CHANGED_COLORBUFFER) != 0;
it means that there was a call of RSP_ProcessDList(), color buffer was changed and thus it should be rendered.

> also, is it possible to not use buffer swap at all like original gln64 did?

Yes, but why?

**Comment by Nejsplitter** [comment]
understood, thanks for the answer gonetz

**Comment by Nejsplitter** [comment]
> bNeedSwap - swap buffers required. bCFB - color frame buffer was modified by CPU, we need to swap buffers to show these modifications gDP.colorImage.changed != 0 - there were modifications of color frame buffer since the previous VI_UpdateScreen() call
> 
> bNeedRender = (gDP.changed & CHANGED_COLORBUFFER) != 0; it means that there was a call of RSP_ProcessDList(), color buffer was changed and thus it should be rendered.
> 
> > also, is it possible to not use buffer swap at all like original gln64 did?
> 
> Yes, but why?

Hi @gonetz if it is not too complex for you to demonstrate, could you show me how the code would look if i wanted to not use buffer swap at all, and render FBO right into front buffer like original glN64 worked. i would like to do some testing.
