### ISSUE TITLE
gSPDMATriangles

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2831]
Checking out the ucode of Mickey Speedway USA, i went through command 0x05.

I am not sure that the implementation in Gliden64 matches it.

At the start of the command, the code checks this nibble:

051**1**0020

if 0, texturing is set off.

if 1, texturing is set on

The number of triangles managed by this command is this nibble + 1

 0x05**1**10020

in this example it is therefore 2.

The code goes to the list retrieved from RDRAM to DMEM, decrementing the number of triangles to draw till 0.

data retrieved from RDRAM to DMEM has this structure

byte: mode 
byte: vtx0
byte: vtx1
byte: vtx2
word0: S&T0
word1: S&T1
word2: S1T2

the higher nibble of byte mode is either 4 or 0.

4 means that G_CULL_BACK in geomode is getting off.

0 means that G_CULL_BACK in geomode is getting on.

This is all what this command does for what i can understand from the code.

**Comment by gonetz** [comment]
The current code uses the second nibble of the command to get the number of triangles.
As you can see, in command 0x05110020, it is also 2.
I checked, for command cmd, the second nibble is always equal to the sixth nibble + 1: 
((cmd>>20)&15)+1) == ((cmd>>4)&15)
But if the ucode actually uses value of the sixth nibble, ok.

>if 0, texturing is set off.
 if 1, texturing is set on
 
I was not used. I added that code.

The rest is already implemented exactly as you described, see gSPDMATriangles function.

Fixed in commit b021d8ee4372.
I don't expect any changes in  Mickey Speedway USA and JFG, which use that ucode.

**Comment by olivieryuyu** [comment]
@gonetz 

actually DKR has exactly the same code for gSPDMATriangles. No distinction should be made here so between DRK and JFG.

**Comment by gonetz** [comment]
> actually DKR has exactly the same code for gSPDMATriangles. No distinction should be made here so between DRK and JFG.

Done.
