### ISSUE TITLE
Army Men - Air Combat GFX issues

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#290]
![capture](https://cloud.githubusercontent.com/assets/9299743/6657440/81745112-cb09-11e4-925a-985514af1ce5.PNG)

**Comment by olivieryuyu** [comment]
many games of this issue actually (i.e rainbow six)

**Comment by theboy181** [comment]
I pointed out that backgrounds are all a little off, this might be a byproduct of that?
https://github.com/gonetz/GLideN64/issues/241

**Comment by standard-two-simplex** [comment]
This doesn't happen when rendering in 640x480 or lower but happens when rendering in higher resolutions.

At a quick glance to the nintendo64 programming manual let's me see that gsSPTextureRectangle(params) allows to render rectangles with vertices given as integer screen coordinates. In this case, if two contiguous textures have contiguous coordinates, when multiplying by a number greater than two (in some cases even less) and rounding down, they will no longer have contiguous coordinates.

I could not easily locate in your released code where you handle this. Do you think that could be the problem @gonetz ?

**Comment by AmbientMalice** [comment]
Fixed with native resolution.

**Comment by olivieryuyu** [comment]
if it is a scaling issue, can t it be fixed for non native res?

**Comment by AmbientMalice** [comment]
>if it is a scaling issue, can't it be fixed for non native res?

Maybe. It's likely there are some bugs in texture tiling that are making things worse for some games, but Glide64 had to use hacks to fix quite a few games. It's not unique to the N64. PCSX2 has to use hacks to deal with scaling issues above native resolution. Scaling based on multiples of native resolution helps quite a bit, though.

**Comment by gonetz** [comment]
This problem can be fixed by any of 2D fixes options.
