### ISSUE TITLE
Widescreen Hack FS issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#326]
When I select Adjust for screen settings and attempt to go full screen I get garbage picture. I have seen this before on an earlier build too.
In both cases my video card eventually crashes and I have to restart.

![agliden64_zelda_majora s_mask_000](https://cloud.githubusercontent.com/assets/9299743/6838254/6f1fe154-d313-11e4-81bb-0dd595d662da.png)

**Comment by gonetz** [comment]
I also sometimes have video driver crash when switch to fullscreen. I haven't had that issue in previous builds though.

**Comment by gonetz** [comment]
Do you have that issue with other games but Zelda?

**Comment by theboy181** [comment]
Both Zelda games so far that I have tested do this.
Mario 64 worked. minor issues with transitions and the sky, but not same issue as Zelda
SSB64 no change
Starfox 64 worked great, similar background issues like Mario 64.

**Comment by gonetz** [comment]
Graphics glitches with Widescreen Hack are expectable. Rare N64 game meets necessary condition to work properly with it. There is little I can do about it. 

My question was about crash when switch to fullscreen. I found myself that this bug is ancient. I seldom use fullscreen mode, so I did not notice it before. Fixed.

Please test and if fulscreen/window switch works correct for you, please close that issue.

**Comment by gonetz** [comment]
Fixed
