### ISSUE TITLE
Nintama Rantarou Gallery 64: extremely slow

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#329]
nearly unplayable

**Comment by gonetz** [comment]
The game is programmed in very stupid way. It uses bg command from S2DEX microcode, but instead of rendering the background with 1 bg command it splits the image on 32x32 tiles and renders each tile with separate bg command. As the result it uses hundred bg commands instead of one. GLideN64 is optimized to draw background as one piece. It calculates checksum of the whole image. Here it dies on  checksum calculation. Special optimization needed for that case.

**Comment by LegendOfDragoon** [comment]
Is it playable in LLE?

**Comment by gonetz** [comment]
> Yes LLE is much faster

Ok, no Special optimization needed.

**Comment by olivieryuyu** [comment]
faster indeed, slow compared to other games in HLE though.

Is it due to a HLE implementation issue? Would be good to be able to play the game in both modes.

**Comment by LegendOfDragoon** [comment]
>Is it due to a HLE implementation issue?

Yes. I believe it's basically the same issue as the SD Hiryuu one, as purplemarshmallow pointed out. Both games use S2DEX.

**Comment by olivieryuyu** [comment]
Pro Mahjong Kiwame 64 has the same issue

**Comment by gonetz** [comment]
Now it works fullspeed with "Background rendering mode" set to Stripped.
However, it has gaps between polygons in non-native resolutions.
This can be fixed with "Render 2D elements with native resolution", but this option also makes the game  slow.
