### ISSUE TITLE
F-1 Pole Position 64 (E) - Bottom Cut

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#401]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7134394/de036972-e29c-11e4-9337-408a29e0084e.jpg)

**Comment by olivieryuyu** [comment]
@gonetz 

I read the VI code but I don't understand how you calculate the height. 

May I kindly request me in a simple way how it is working in your code?

In this game my calculation arrive at 300 of height for this game.

**Comment by gonetz** [comment]
Simple way? Hardly, because VI height calculation is bunch of hacks and heuristics.

The main formula is simple. Height is number full scan lines used, multiplied by vertical scale.
REG.VI_V_START contains indices of the first and the last half-lines. 
REG.VI_Y_SCALE contains vertical scale.

Thus
`VI.real_height = vEnd > vStart ? (((vEnd - vStart) >> 1) * vScale) >> 10 : 0;`
gives us number of scan lines. It is where the science ends and magic begins. 

I need to know height of frame buffer. SetColorImage command provides only buffer width. Frame buffer will be displayed on screen by VI. There is a correspondence between frame buffer size and parameters of VI. Thus, I'm trying to use data for VI to calculate frame buffer height. Result depends on region (PAL/NTSC), is output interlaced/non interlaced and some other conditions. It is known, that VI shows not the whole frame buffer: number of scan lines usually less than buffer height. Thus, VI.real_height is multiplied by magic constant to get full height or VI.height, which is used for frame buffer  allocation.

For this game VI.real_height is 222, VI.height is 224. Interesting, that the game uses scissor (0, 0, 319, 239), so real frame buffer height can be 239 or 240.

**Comment by olivieryuyu** [comment]
Woa I spent yesterday 5 hours on reading on the topic and I have a complete different view on the matter. My calculations are totally different.

I guess I am missing some points :(

First of all you arrive to 224 instead of 225. Is it because the width set by SetColorImage of the framebuffer is width-1? Or do you retrieve an odd line as if the game is in interlaced mode?

Could you please let me know what is the buffer width as per SetColorImage for this game? I would like to see if my calculation leads to the same VI.real_height or not.

**Comment by olivieryuyu** [comment]
i compared Ricevideo with Angrylion plugin.

Rice set the game as follow:

![image](https://cloud.githubusercontent.com/assets/8987490/21491256/acecf5a2-cbfb-11e6-9b88-4c7331bd5b4e.png)

It would be somehow what you have: 319, 239 after scissoring.

However Angrylion does show the same results: the image is less height.

On the left Rice and Angrylion on the right.

![image](https://cloud.githubusercontent.com/assets/8987490/21491299/f1ebd344-cbfb-11e6-9a53-756197d444a4.png)

**Comment by olivieryuyu** [comment]
ok but comparing Rice and GlideN64, Rice is obviously incorrect.

![ok](https://cloud.githubusercontent.com/assets/8987490/21491498/78614aca-cbfd-11e6-80ff-cfe29469bdbe.jpg)

**Comment by olivieryuyu** [comment]
now I try to compare angrylion with gliden64.

![image](https://cloud.githubusercontent.com/assets/8987490/21492567/3050a3bc-cc06-11e6-9748-23c04222292b.png)

GlideN64 is slightly too small in its height. i guess 222 instead of 225.

**Comment by gonetz** [comment]
> First of all you arrive to 224 instead of 225. Is it because the width set by SetColorImage of the framebuffer is width-1? Or do you retrieve an odd line as if the game is in interlaced mode? 222 is 224-2 odd lines?

`VI.real_height = vEnd > vStart ? (((vEnd - vStart) >> 1) * vScale) >> 10 : 0;`
VI.real_height = 222 for this game. VI uses 222 scan lines That's why black lines on top and bottom are so wide.
Then plugin detects PAL region and multiplies real height by magical constant:
`VI.height = (u32)(VI.real_height*1.0126582f);`

VI.height = 224 for this game.

SetColorImage sets buffer width to 320.

**Comment by olivieryuyu** [comment]
Ok so let me see if I have the right maths on your equation.

vEnd (95) - vStart (569) = 474. >> 1 means it is divided by 2, so 237. I understand, may be incorrectly, that, as this game uses non-interlaced mode, only the even-numbered fields are displayed. It means that indeed we need to divide the number of lines per 2, leading to 237 value.

vScale = 960 (0x3C) as per the register.

Then you are right shifting by 10 and you get 222 which are the number of lines. It would be a cross product, having in mind that 1024 corresponding to 237 with 960 is 222.

That make sense :)

Now how did you get this magical constant? Can it be slightly inaccurate? My calculation arrives to 325 and seems logical.

**Comment by gonetz** [comment]
Magical constant is a number, which being multiplied by number of lines produces correct buffer height.
237 => 240
478 => 480
and like this

Of course, it is inaccurate. A hack in fact. I don't know a better way. How you do calculations and how you got height of 225?

> the 320x222 is actually the displayed area so but it does not have to correspond to the framebuffer size?

Yes, the displayed area does not have to correspond to the framebuffer size. And this causes lots of troubles. I just don't know another way to estimate frame buffer height.

**Comment by purplemarshmallow** [comment]
z64gl uses yl of setscissor command to calculate the buffer's height. Is this a better way or is it problematic too?

**Comment by gonetz** [comment]
It also not reliable way. GLideN64 uses scisor, viewport, VI.height,  heuristics to guess buffer height. Sometimes all of this is not enough.

**Comment by olivieryuyu** [comment]
I made further tests with other games and I failed. It is a puzzling matter.

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by gonetz** [comment]
Good.
