### ISSUE TITLE
undefined symbol: glMemoryBarrier

### ISSUE THREAD

**Issue by sergiobenrocha2** [gonetz/GLideN64#420]
Trying run with Nvidia GeForce GT 740M, I'm getting "undefined symbol: glMemoryBarrier" :

```
primusrun mupen64plus --gfx mupen64plus-video-GLideN64.so m64p_test_rom.v64

UI-Console Error: dlopen('/home/sergio/Projects/libretro/mupen64plus/m64p_helper_scripts/test/mupen64plus-video-GLideN64.so') failed: /home/sergio/Projects/libretro/mupen64plus/m64p_helper_scripts/test/mupen64plus-video-GLideN64.so: undefined symbol: glMemoryBarrier
```

Xubuntu 14.04, 64 bits.
kernel 3.14.34
OpenGL core profile version string: 4.3.0 NVIDIA 340.76
OpenGL version string: 4.4.0 NVIDIA 340.76
GLideN64 Early Release

**Comment by degasus** [comment]
Hint: linking of GL functions which aren't in 1.X isn't allowed, you have to fetch them throw glXGetProcAddress. Or just use glew or libepoxy

**Comment by gonetz** [comment]
glMemoryBarrier Core since version 4.2
Strange that it is missing in 4.4.0 driver.

>> Hint: linking of GL functions which aren't in 1.X isn't allowed, you have to fetch them throw glXGetProcAddress.

I hoped that only Windows has that problem. Ok, thanks!

**Comment by gralco** [comment]
I'm using fc21 ARM64 and I get this when attempting to use GLideN64 with m64py:

Frontend: ERROR: failed to load plugin /usr/lib64/mupen64plus/mupen64plus/mupen64plus-video-GLideN64.so: /usr/lib64/mupen64plus/mupen64plus/mupen64plus-video-GLideN64.so: undefined symbol: glMemoryBarrier

and this with just mupen64plus:

UI-Console Error: dlopen('./mupen64plus-video-GLideN64.so') failed: ./mupen64plus-video-GLideN64.so: undefined symbol: glMemoryBarrier
UI-Console Error: Specified Video plugin not found: mupen64plus-video-GLideN64.so

Note that I'm having to use using primusrun in order to be able to perform the OpenGL operations used by GLideN64.

**Comment by sergiobenrocha2** [comment]
You need to compile with -Wl,--no-as-needed otherwise you will get "undefined symbol: glGetProgramBinary"

I'm getting "undefined symbol: glMemoryBarrier" yet

**Comment by gonetz** [comment]
I have no compilation issues.
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by olivieryuyu** [comment]
can we close?

**Comment by sergiobenrocha2** [comment]
Why this issue was closed? I'm still getting undefined symbol: glMemoryBarrier on nvidia

**Comment by gonetz** [comment]
I compiled on Ubuntu with Nvidia card just yesterday. No issues with compile and run. Your problem is not plugin's issue, I can't se

**Comment by sergiobenrocha2** [comment]
What Ubuntu version are you using @gonetz ? What nvidia card, and what driver version?

**Comment by gonetz** [comment]
Ubuntu 14.04
GTX 970
driver version 352.63
