### ISSUE TITLE
GPL violation?

### ISSUE THREAD

**Issue by tj90241** [gonetz/GLideN64#421]
The plugin is in the violation of the GPL, as described here:
https://nocluez.wordpress.com/2015/04/19/a-word-on-gliden64/

Please send me a copy of the source code, or make it available, per the GPL license.

**Comment by Fanatic-64** [comment]
*Semi-legal expert here, the proper procudedure for this is to email Gonetz with a DMCA Takedown Notice, ordering him to stop distributing binaries in violation of the license. Plus, you must be the copyright holder (Orkin) to take action against the infringement. If you are MarathonMan or anybody else, you legally have no business interfering in this affair. You may attemp to contact Orkin to notify him of the infringement though.

**Comment by AmbientMalice** [comment]
@Fanatic-64 I believe under GPL, anyone who possesses the binaries is allowed to redistribute them and ALSO allowed to request the original source code. Not providing said source to whomever requests it is a GPL violation.

It's one of those "That's just how it is" situations. I'm mildly sympathetic to Gonetz in this situation, but from a purely legal viewpoint, he does seem to be violating GPL. (I could be wrong, granted.)

This isn't a new issue. In the past, N64 emu devs have gotten in trouble for forking Glide64 and 1964 while refusing to hand over source to PJ64 devs who demanded it. Also forks of Angrylion's software renderer and HatCat's RSP where the dev refused to hand over source.

What makes this situation bearable, if not legal, is that Gonetz has promised to open up the source in less than two weeks. When that happens, this problem will vanish assuming he doesn't repeat this behavior down the road.

**Comment by olivieryuyu** [comment]
The source will be released in the coming weeks, at the end of the public project.

Why making up such a drama now for nothing?

**Comment by neobrain** [comment]
@AmbientMalice Mostly correct. From my understanding, there's a minor detail though with regards to your first paragraph: Source need not only be provided on request, but distributed along the binary. There are some alternatives to that as listed on http://www.ifross.org/en/what-obligations-are-involved-distributing-software-licensed-under-gplv2 , but it doesn't change anything about the situation as a whole.

@Fanatic-64 
> Plus, you must be the copyright holder (Orkin) to take action against the infringement

That might not be quite correct. You could argue that potentially the right for us to access the source code is being violated. I'm not sure if that is actually the case, or if instead that right has never been given and hence only the license is being violated.

@olivieryuyu I think it's terrible that apparently the whole N64 community is so ignorant against licenses. Granted, it's a nice gesture of gonetz to open the source *eventually*, but if he keeps ignoring this issue and holds on his project plan for no reason, that's not really any better than prior GPL situations within the N64 community. Not clearing this issue up properly will just encourage people to further act around like this.

**Comment by olivieryuyu** [comment]
it is not eventually, it will happen as clearly stated in the project. So there is not drama here.

**Comment by AmbientMalice** [comment]
>it is not eventually, it will happen as clearly stated in the project. So there is no drama here. 

It's still a GPL license violation, though. And that is serious business\drama in some circles. Some people feel strongly that unless *ALL* GPL violations are at least warned, then the GPL will become worthless.

Let's not forget that in the original Project Plan, the release date for the source code was January.

Now I have a great deal of respect for Gonetz and his contributions to N64 emulation. But it would not be advisable for him to brush off this matter so lightly. At the very least, he should promise to not violate GPL in future, even if he doesn't release the source until two weeks after Early Release as he has stated.

**Comment by Royerson** [comment]
This shit really is completely unacceptable and you apologists make me sick. Gonetz has purposefully violated the license, and releasing it in a couple of weeks is not going to change that.

Nothing will likely ever come of it, even if he keeps doing it, but it doesn't make it right, and doesn't mean you shouldn't be mad about it.

**Comment by Mushman** [comment]
There a few facts that need to be straightened out. In February, @gonetz actually [made a thread](http://gliden64.boards.net/thread/76/gliden64-license) detailing the projects he used, what licences they have and asked how to licence GLideN64, so this information comes from there.

Firstly, Orkin's glN64 plugin doesn't appear to have a licence, opposed to @Fanatic-64's comment. However, the code that is under the GPL is from z64 OpenGL (which I think isn't working at the moment; GPL2), GlideHQ (which was released with Glide64; GPL2), Glide64 (made by gonetz; GPL2) and MupenPlusAE's port of glN64 (for the Android port hasn't been released yet; GPL3).

You can see how this disorienting this all is. On top of that, there's another project that has its own custom open source licence. gonetz admitted he was "illiterate in juridical questions", that "I feel myself dumb when I'm trying to understand software license agreement" and tried to approach it in a way to "avoid attacks". zilmar (@project64) agreed that "licensing is a mess" and that "most people seem to just care is there source or not".

For the record, no-one on the private backer forums has requested the source. The first time it was asked for was by @neobrain in the Early Release Reddit thread, who then asked directly on gonetz's blog. neobrain's initial comments were reasonable, but then started to get a little intimidating, as gonetz pointed out his replies. Think about it: the project's been up for many months now and all of a sudden someone with absolutely no prior connection to the project begins insisting on the source code release now when it's only one and a half weeks away? There are backers on the forum who have talked keenly and enthusiastically about actually contributing to the source code, yet are patiently waiting until it becomes available. Moreover, Glide64 had very sparse outside contribution. I don't blame gonetz for thinking that neobrain is only causing trouble.

That said, neobrain is still right that the source code needs to be provided due to it inheriting GPL somewhere along the track, despite the project plan.

Nevertheless, I question some of neobrain's comments. I don't think gonetz's comments show that he is deliberately choosing to violate the GPL like neobrain asserts, but instead that he is threatened and taking inaction because of it. I think it's ridiculous for neobrain to acknowledge exactly that by saying he's "someone lacking understanding of a license and using it regardless", and then to take to Reddit and say "I guess properly following the license of code that a project builds upon is asking too much for someone who received more than 8000$ for that project". First he sees a misunderstanding and then tries to convince others he's doing it because of the money? It seems really disingenuous.

Look at neobrain's blog post that was in the original comment for this thread. "I don’t like all the drama which is present in emulator communities, nor do I like personally being the one stirring more drama up..." But that blog post is longer than the conversation he and gonetz actually had. It just looks like he spent more effort on creating drama than trying to resolve it. I think the point he made about the campaign misleading people is merely an assumption, since I haven't seen anyone who might believe it. When I donated, I wasn't "tricked into thinking they are being provided an additional service by getting access to preview builds and getting the project open-sourced by funding it". I donated because I wanted to support the plugin's development. I think that part about wanting to "set an example" epitomises the post, especially because it also takes opportunities to talk down the project for other unrelated reasons.

Look at the Reddit thread. This approach has already caused some unnecessary damage when the situation should have been handled more diplomatically. Geez, and look above me just now too.

Despite this, neobrain is still right. I will discuss this on the forums myself and attempt to reach a resolution before this gets even worse.

I'm extremely disappointed by this. This project was a positive point among Nintendo 64 emulation. I hope this drama doesn't hurt it...

**Comment by tj90241** [comment]
@olivieryuyu It's not about the "drama"; I'm trying to make a point. Apologies in advance to @gonetz for making him the poster child, but N64 history is rooted in license violations, and this one is particularly bad as he's not only violated the license clear as day, but pay-walled off the binary. As for former offenders: look at "pokefan", "suanyuan", and the many others who have forked JD/MooglyGuy and angrylion's works and tried to hold it hostage, and in some cases, even claimed it as their own.

Plus, as an emulator developer who doesn't use the archaic Project 64 plugin type (or Mupen64Plus's, which may be different?), I get left to pound sand because nobody can respect licenses. Irritating, to say the least.

@gonetz already received the money, so it's not like he's at a loss for releasing the source code, sans a few potential late backers. But you can't assume there are many of them, since the binaries are being leaked all over the place, as I'm sure you by now know. So when you say "it's only a few more weeks" -- consider it from the flip side. If you're only a few weeks from source release, why not just release it now? Is there a reason other than "the code isn't clean yet"? There's already a bunch of people out there who appreciate this plugin; they're not going to look at the code and say "well gee this sucks, off to another one!".

**Comment by tj90241** [comment]
@Fanatic-64 "If you are MarathonMan or anybody else, you legally have no business interfering in this affair."

False. The binary is GPL'd. I have full right to demand for source, since I have a binary. You're confusing that with the fact that Orkin would have to assert the copyright if something like this were to go into a formal dispute.

**Comment by neobrain** [comment]
@Mushman Thanks for writing this obviously well-informed and (on both sides) understanding comment, as well as for providing some "insider information". I will be brief in my reply, so that things can maybe de-escalate a bit.

>  Think about it: the project's been up for many months now and all of a sudden someone with absolutely no prior connection to the project begins insisting on the source code release now when it's only one and a half weeks away

First off, I have been following GLideN64 since the first blog article about it, and tried to make worthwhile suggestions whenever gonetz wrote about problems he encountered, at least some of which ended up being useful to him.
As for bringing up the matter so late: I did not know that GLideN64 was based on GPLed code until gonetz mentioned it in the comment section of the latest blog post.

> Nevertheless, I question some of neobrain's comments.
A lot of what you mentioned happened after the discussion on the GLideN64 blog, and the negativity was mostly due to gonetz's final comment. I was surprised to have my argument (which I thought to be quite reasonable and informative, even for people unaware of the GPL details) contered with being categorized as a "copyright purist". Hence the maybe somewhat drastic reaction.

> But that blog post is longer than the conversation he and gonetz actually had.
It felt like that conversation had reached a point where there was no going forward anymore. All I could have done was repeating myself. I figured if other people shared similar concerns, things would be taken more seriously (which it appeared not to be during the discussion).

> I think the point he made about the campaign misleading people is merely an assumption
I think that point of mine came across wrong. I didn't mean to accuse anyone to intentionally mislead people into backing the project. Once I get home (later today), I will clarify my intended point, or maybe remove it entirely if that ends up digressing the blog post too much.
As you suspected, there are indeed some aspects about fundraisers that disturb me, but rest assured I tried to keep

**Comment by MooglyGuy** [comment]
Thank you, TJ, I appreciate it. Personally, I don't care one way or another if someone decides to use my modifications to angrylion's code, but I'd like to think that they would at least respect the modified MIT license that MAME and MESS use rather than wrapping it up in some binary.

As for the whole matter at hand, this is ridiculous. We have @olivieryuyu on one corner basically defending GPL violations with a pathetic argument of "who cares", and @Mushman in the middle with a mealy-mouthed defense of @gonetz being "threatened and taking inaction because of it." Yeah, let's see how far that sort of argument would get anyone in a court of law. "Your honor, I was threatened by Officer Smith giving me a ticket for speeding, so I took inaction because of it." Are you people literally stoned?

As for @gonetz violating the GPL, can any of you honestly say that this comes as a surprise to anyone? We're talking about someone who started a crowd-funding campaign to pay for his time developing GlideN64, as if everyone owes him something for something he does in his spare time. I for one have never asked for a thin dime as a result for my 15 years of working on emulation, and I never would, because the preservation of history is something that transcends money. If you don't believe that preserving consoles and games is its own reward, and instead think that you're some Indiana Jones, then go do something else as a hobby. Speaking to the GPL violation itself, again, is anyone surprised? We're talking about someone in Russia, where the laws are, to say the least, malleable. Finding a GPL violation should be about as surprising as finding a straw of hay in a haystack.

Personally, I don't think @tj90241 is going to get anywhere by appealing to anyone in this corrupt and morally bankrupt community, because if the popularity of HLE, and the sacrifice of historical preservation in order to play l33t fr33 g4m3z!11!1!, has taught me anything, it's that nobody gives a good goddamn what's right. People will continue to skirt the line of legality and downright step over it as much as they want, and there's little to be done about it, especially via an issue submission page on Github. Submit a proper DMCA request to Github, get this thing taken down if it means that much to you, but leave the drama for the idiots who think that emulator developers are gods above the law.

**Comment by Mushman** [comment]
> First off, I have been following GLideN64 since the first blog article about it, and tried to make worthwhile suggestions whenever gonetz wrote about problems he encountered, at least some of which ended up being useful to him.

My apologies. I didn't think to check that.

> It felt like that conversation had reached a point where there was no going forward anymore.

Yeah, I can see that. I was just worried when I saw some of the discussion move away from measured, direct communication with some of those angry reactions.

> I think that point of mine came across wrong. I didn't mean to accuse anyone to intentionally mislead people into backing the project. Once I get home (later today), I will clarify my intended point, or maybe remove it entirely if that ends up digressing the blog post too much.

I believe you. Change it if you still think it needs clarifying.

Let's hope this gets sorted out when gonetz comes around.

**Comment by Mushman** [comment]
...And then in comes another comment. :/

> Yeah, let's see how far that sort of argument would get anyone in a court of law. "Your honor, I was threatened by Officer Smith giving me a ticket for speeding, so I took inaction because of it." Are you people literally stoned?

@MooglyGuy Let's not pretend that we're all going to get lawyers and take this matter to court. This is a community dispute. gonetz still did the wrong thing, but he didn't do it with bad intentions. That's the point I'm trying to make to calm some of the fiery rhetoric and move to more co-operative dialogue, which is the best direction to get a proper resolution. Seriously, what's the chance of solving the problem if there's a witch hunt going on? Who is going to listen if the discussion is just shouting each other down? C'mon man, work with us, not against us.

The rest of your comment is entirely unhelpful and mostly off topic. We're all a community and we can't just presume the worst of those who disagree with us. We need different ideas. But that's an entirely different argument. Right now, we're trying to correct the mistake and get the source code released.

This is exactly the kind of thing I was afraid of.

**Comment by twinaphex** [comment]
> The rest of your comment is entirely unhelpful and mostly off topic. We're all a community and we can't just presume the worst of those who disagree with us. We need different ideas. But that's an entirely different argument. Right now, we're trying to correct the licencing mistake and get the source code released now.

He (gonetz) conveniently ignored both my post and neobrain's where we already brought up this issue and it's been well past over two days since with him even continuing to post in that thread section after we made our posts, so he has obviously seen them and read them.

http://gliden64.blogspot.nl/2015/04/early-release.html#comment-form

Therefore I see little reason to believe he will suddenly start seeing the light and getting rid of what is obviously bad PR for him and his future pursuits. So no, I don't think the Wikipedia-style 'assume good faith' policy is worth much here.

Stupid thing about all this is also, this could be done at the drop of a hat. There's already the Github repo, only thing that needs to happen is the sourcecode uploaded to the same repo. Hell, having a commit history log instead of just a tarball release will mean more than any kind of code cleanup or code refactors in the world, and that is unfortunately where the shoe wrings everytime one of these 'auteur-style coders' just 'codedumps' their sourcecode, it then falls onto others to start making sense of your code instead of being able to easily traverse the commit history and see why certain decisions were made and when.

**Comment by neobrain** [comment]
@twinaphex Side note: from what I've read, the plan was to actually release the full git repository including commit logs.

**Comment by twinaphex** [comment]
Let's 'hope' for the best I guess.

**Comment by Mushman** [comment]
Look, I hear you @twinaphex. I just think that it's a developing situation. This thread appeared in his absence. We still have chances to discuss this. It's the first time I've seen this issue. I'm willing to help you in the best way I can. I believe the best way is to get him on side is to show him that a lot of people care about the issue and reinforce the positives. I don't believe antagonising him will help at all.

**Comment by gonetz** [comment]
Gentlemen, what is going on here?

Why you turn simple bug report, which soon will be resolved, into discussion board. Why not use better stages for that?

OK, if you already spoiled it anyway, let me say few words too.
1.	I don’t understand why you created that panic right now? The project is more than year in development. Where have you been before? Now it looks like hypocritical attempts of some people to get PR points before big release. I also suspect that some comments motivated by envy to the project, which collected 8K. To your notice, final sum is ever higher. It did not make me reach though. The project took much more time than initially planned.
2.	The main accusation point: “you can’t distribute GPL’ed binaries without sources”. Which binaries distribution are you talking about? I never published public links to any binaries. The only exception was link to GUI prototype, which contained both binaries and sources. The project campaign on Indiegogo clearly states condition for public release: “Source code is clean, free and open-source, licensed under the GPL”. This condition is not met yet, so the plugin is not released. Release is planned to be done soon, but so far there were no official public distribution of anything. You may have some binary code, which may or may not be related to the project. Since there were no official public binary release, there is nothing to compare with. If you got some binary release and make it public (leaked) it is now YOUR responsibility to provide source code for it.
3.	I not intended to offence anyone or violate somebody’s rights. Cite: “The project aims to provide to the public free of charge the most advanced N64 graphics plugin, with the full source code available under GPL. This is purely a non-commercial, non-profit project. This crowdfunding will just allow me to spend the time to finish it.” Just let me finish my work and you will get it free of charge with the full source code available. 
4.	The people, who started that persecution probably think that they do right thing and struggle for law. Actually, you just distract me from my work.  Look at the current state of N64 emulation scene. It’s because of you. Devs don’t like when somebody say them what to do. They avoids community with large percent of initiative idiots.
5.	I admit that I’m "illiterate in juridical questions". I don’t care about difference in GPL 2 and 3. So, I could be wrong somewhere. The sources not released yet because the project is not ready. I’m working alone and while I’m working alone I don’t share my code with others. When I’ve done: look, take, do whatever you want. I prefer to work that way. I worked that way on Glide64 project, which is currently forked on many projects. Now I’m switching to Android port. It implies command work, and thus another level of communication, where source code exchange is must. It is not because I must obey license, it is logic of technology process.
6.	I’m very busy with release preparations and don’t have time to participate in that discussion anymore. Such talks never have positive results. My most important point is under number 3. And again: I’m working on current incident and it will be fixed soon.

**Comment by Mushman** [comment]
> 2: The main accusation point: “you can’t distribute GPL’ed binaries without sources”. Which binaries distribution are you talking about? I never published public links to any binaries.

@gonetz, to be fair, I believe this is the core point of contention. Thank you for explaining why you made the decision, but let me explain why others are having a problem with it.

GPL has a very strong history in free and open-source software. In short, the GPL was developed to prevent closed development, like in the way you are developing GLideN64. The GPL forces developers to release their software for free, and for everyone, along with the source code so that users are free to change it. Code is considered private by the GPL if it only exists on the developers' environment. In the eyes of the GPL, the releases on the restricted backer forums are now in the hands of some of the public (including me), therefore they are in the hands of all of the public.

If it sounds like there's some philosophy going on there, the truth is that's correct. Supporters of the GPL are very passionate about the philosophies the GPL stands for, for better or worse.

> 5: I admit that I’m "illiterate in juridical questions".

The people here have more experience with GPL. Wouldn't the best scenario be to take their advice?

> The sources not released yet because the project is not ready. I’m working alone and while I’m working alone I don’t share my code with others. When I’ve done: look, take, do whatever you want. I prefer to work that way.

Unfortunately, the GPL prevents you from working this way. Maybe it's best to publish it and tell everyone you're ignoring all pull requests until you are reached the stable milestone? I think you can even disable pull requests on Github?

I know this is not the situation you wanted to be in, but we can still put this all behind us. Please commit the repository. (:

**Comment by purplemarshmallow** [comment]
I hope gonetz still wants to publish his development history and the commit logs after this chaos

**Comment by tj90241** [comment]
@gonetz:
1) As @neobrain said, I didn't know that Glide64 was GPL'd. Otherwise I would have raised a stink from day 1.
2) I'm talking about the GlideN64 plugin that you're withholding source from. It doesn't matter HOW the binaries were published, officially or not -- they were distributed and that's all that matters. Also, you forked something that was already GPL'd, so any releases you do are thereby GPL by nature (unless you contact all former authors who hold copyright and agree to a licensing change, etc.).
3) The GPL doesn't have an "intentions" clause. Otherwise I'm sure RedHat and many other companies that benefit from GPL'd sources would be doing a lot better in business right now. :)
4) I'm a highly active contributor to N64 emulation. I know what it feels like "to be told what to do", but I also know that going against what a license dictates is not ok.
5/6) I don't even know how to respond to that, but again -- being "busy" doesn't preclude you from adhering to the license. Period. If this project had more traction in the FOSS world, you'd be hearing from the FSF shortly.

**Comment by theboy181** [comment]
I want to note that I did request a portion of the source, and it was delivered immediately.

I figure this is all nonsense personally, but I guess it does help make headlines. 

Attitudes like this are only going to hold people back from going public in the future. The N64 scene is becoming secret society where new comers, and new ideas are frowned up on.

I don't claim that I understand the GPL, but I know that its there for good reason. I am confident that @gonetz didn't purposely try to break the GPL.

**Comment by gonetz** [comment]
@Mushman – thanks for explaining the situation. I don’t care about threats, but your calm words are very convincing. My respect.

Lets make a compromise. Release of current source code resolves the problem with GPL violation. I mostly finish with core refactor. So, I’ll upload archive with ‘master’ revision. No history. @Mushman, is it formally enough to settle the situation down?

Regarding project history: do not worry. I understand importance of project history for developers, so eventually I will upload it to GitHub. It will happen when I’ll be ready to process pull requests.

@neobrain – my apologies. Your good advice on the Blog was really helpful. I did not recognize you when you suddenly attacked me with the demands to provide you with the sources. The situation when people can’t wait a bit for promised complete release still looks weird for me. From my POV it looked like “daddy, I want that puppy NOW”. Again, thanks @Mushman for explanation of historical roots of the question.

@tj90241 cite: “I didn't know that Glide64 was GPL'd. Otherwise I would have raised a stink from day 1.” I have no doubt in your abilities. Every your post in that thread stinks.

**Comment by MooglyGuy** [comment]
@theboy181, welcome to the N64 development scene, where it's exactly as it has been for the past 15 years. You're not treading any new ground. And if attitudes like "The GPL is something to be respected and abided by" will "hold people back from going public in the future", then that's great, there will be less people in the scene acting indignant when called out on their behavior.

As for being envious over 8 thousand dollars, pardon me while I dry my tears on a hundred thou bonus sitting in my bank account right now. I know 8K seems like a huge amount of money in a country where it can buy you 10 bribed police men, 3 mail-order brides, 72 hours on a botnet and a discount membership with a credit card fraud ring, but here in the real world, it's about as much as it would cost to buy a used card. And hey, we wouldn't have to have a dashboard cam installed in order to guard against people pulling insurance fraud scams.

**Comment by tj90241** [comment]
@gonetz Sorry if I come off as harsh; I fully acknowledge that my tone isn't exactly amiable. But I speak mostly out of passion and frustration for the fact that licenses are being violated and sources are being withheld for the zillionth time in the N64 community. If you push master, even without the commit history, I'll be the first one to congratulate you and apologize for any ruckus that I've incited.

**Comment by neobrain** [comment]
@gonetz Releasing a source tarball of the current code (or the code used to build the early release) would be perfectly acceptable for me. Thanks for changing your mind.

As soon as we can put this aside, I'm also joining @tj90241's words. It's hard to stay patient about GPL matters like this with all the frustration that usually comes out of it. It's nice to see this turning out to the better side after all :)

**Comment by gonetz** [comment]
From which universe you came to us @MooglyGuy ? And I said that tj90241 words stink! 
@tj90241, my apologies. You may be harsh man but you are man. Not sure about MooglyGuy. He acts like reptiloid.

Again, to the agreement. I'll not push master. I'll upload 'master' revision of sources as publicly available archive. I'll push whole project history later.

**Comment by tj90241** [comment]
@gonetz Hats off to you, sir. Sorry if I wasn't clear -- yes, a release of the current source (in any form) is exactly what (most?) people are hoping to see come of this. Thank you in advance for moving forward with this and doing the right thing. I apologize for my abrupt and off-putting tone.

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/releases/download/v0.9/GLideN64_master.7z

Please close the issue.

**Comment by tj90241** [comment]
Gladly. :+1:

**Comment by gonetz** [comment]
Phew! Time to sleep. Thanks to everyone for interesting discussion. I've learned many new facts about world of free software.

Next time please select more appropriate place for discussions. E,g, http://gliden64.boards.net :)

**Comment by balr0g** [comment]
@gonetz: Thanks!!! For reference, the correct thing to do is to release the source code used to build the binary releases either together with the binary releases, or to whoever asks. It would probably be easiest to just make tarballs with each pre-release. That said I don't know how many more pre-releases you plan to make :)

**Comment by Fanatic-64** [comment]
Also for reference, MooglyGuy has a history of stirring and participating in drama, within the MESS developers, in EmuTalk.net, and elsewhere. I recommend reading this opinion of Angrylion about him: http://www.emutalk.net/threads/54131-Announcement-Cycle-accurate-N64-development-underway?p=452735#post452735

Nice to see things were solved in a civil and satisfactory manner, and didn't end with just mindless rage.

**Comment by gonetz** [comment]
@Fanatic-64 Thanks for the reference. It fully corresponds to my initial impression about that person. In such cases its good to know whom you are dealing with.
