### ISSUE TITLE
Create Screensots A Weird Way

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#425]
When I push F3 it creates folders & images with various signs, ingame happens nothing when I hit F3 (bmp & jpg) 
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7333829/6353b97c-eb7d-11e4-9206-e42078288a89.jpg)

**Comment by gonetz** [comment]
It had to be fixed with latest build. Screen shot path provided by emulator and it is simple non-unicode string. Latest build converts that string to QT string using your system locale. I also had problem with screen shots before if path to emulator contained non-ASCII characters. Now I can use local non-ASCII characters in path to Emulator folder and screen shots stored correctly. Strange that it does not work for you. What is full path to your Project64 folder?

**Comment by Predator82Germany** [comment]
C:\Users\WC\Desktop\Project 64 2.2.0.3

**Comment by gonetz** [comment]
Only spaces, no special symbols?
Ok, I'll made the same path on my PC and check it.

**Comment by Predator82Germany** [comment]
No special symbols, exact like above

**Comment by gonetz** [comment]
I made the same path, only on D: drive. Works fine for me. My settings are on the screen shot:
![screenshot](https://cloud.githubusercontent.com/assets/8983092/7342987/79cde69e-ecdd-11e4-9b3a-3a60ff0bc139.png)

**Comment by Predator82Germany** [comment]
Did you make a screen?

**Comment by gonetz** [comment]
Yes, screen shots saved in "D:\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots" folder

**Comment by Predator82Germany** [comment]
Fixed in #409
