### ISSUE TITLE
Banjo-Kazooie huge black borders around the screen

### ISSUE THREAD

**Issue by etking** [gonetz/GLideN64#482]
The game (any region) shows huge black borders on a 16:9 display in 1080p on all 4 sides around the screen in any of the 4 aspect ratio settings. Black borders should be minimized in 4:3 or 16:9 modes and  be completely absent in stretch mode.

**Comment by purplemarshmallow** [comment]
VI Emulation adds borders
http://gliden64.blogspot.co.at/2014/01/frame-buffer-emulation-part-iii.html
you can disable framebuffer emulation and they will be gone

**Comment by etking** [comment]
I just checked on real hardware and the black borders are there too. But wouldn't it be possible to hack them away by cropping and resizing the final output image with some resource efficient and high quality method? Nobody likes black borders and it should not be necessary to sacrifice frame buffer emulation to remove them.

**Comment by AmbientMalice** [comment]
>But wouldn't it be possible to hack them away by cropping and resizing the final output image with some resource efficient and high quality method?

In theory, maybe. But that kind of thing is sort of dirty. And it would have to be applied on a per game basis - plus you've got games that switch resolutions. (And crop-resize does terrible things to image quality.) It's not impossible, though.

Nobody likes black borders and it should not be necessary to sacrifice frame buffer emulation to remove them.

This is unfortunately the price of (more) accurate N64 emulation.

**Comment by thecoreyburton** [comment]
If it's on the hardware too, then unfortunately it's programmed into the game to account for CRT overscan at the time. It varies from game to game because it never had a set value and could vary from TV to TV (some games even had an adjustment option).

The only possible workaround I see to this is a "crop" option in the plugin, allowing users to custom select an amount of pixels to crop from each side. Eg: top 5,  bottom 5, left 0, right 0 would crop slightly off the top and bottom. This way users who wanted this feature could enable it and set custom-per-game settings.

**Comment by Mushman** [comment]
I would also like features to remove the overscan regions. There are a few methods you can achieve this.

**Crop Viewport**
Reduce the size of the render area to only show the used space. Problems with this include resolution and aspect ratio being changed by the game so that they no longer exactly reflect user settings. Another issue that's tricky to work with is that some games use different overscans in different places, so that means a static clip will either over-crop or under-crop the view, or determining how to deal with dynamic cropping.

**Scale Viewport**
Proportionally increase the rendering area to remove surrounding blank space. The drawbacks of this method are uneven scaling coefficients (the resizing factor is likely to be some ugly fraction or decimal, although this can already happen with user resolutions) and disproportional overscan resulting in scaling not removing all of the inactive area or cropping some of the active area.

**Render to Overscan Area**
Like adjusting the aspect ratio in the widescreen hack, force the game to display outside its normal boundaries. The only issue for this is that the games are not designed to do this, so there might be some weird behaviour beyond the normal limits. However, the widescreen hack works rather well, so it might not be too bad.

These can all be implemented using a custom configuration setting specifying the co-ordinates of the overscan on the original resolution. Alternately, it might be possible to write an algorithm to do it dynamically, but that could also be very difficult.

I personally wouldn't mind seeing more flexible options for the widescreen hack. Sure, it's usefulness has limitations, but there might be some cool things that come from it that aren't yet known. For example, Jet Force Gemini's widescreen mode combined with the widescreen hack will make the game display in 21:9, which is an increasingly popular monitor aspect ratio.

It's also worth noting that some games have screen adjustment options. Possibly another solution is to use cheats or romhacks to achieve the desired outcome. It's interesting to see the community making changes to actual game engines this way.

**Comment by CraigClements** [comment]
Orkin implemented overscan in Direct64, mostly to eliminate the dungeon entrance map icon appearing in the top left corner in areas in Ocarina of Time. The icon is not normally visible on standard CRT televisions due to overscan, but can be seen with emulation as the area is not hidden. Obviously Direct64 is closed source, so there is no insight into how exactly he tackled his implementation.

**Comment by standard-two-simplex** [comment]
@Mushman I think the most appropriate thing would be to render into some resolution (user selected, possibly multiple of native) and then resize (or map into video card buffer) the central 90% (whatever old TV-s cropped actually) of it to fit the output resolution.
This way, there would only be black borders if there were so in old TV-s, and games like Oot would look more real, as the hud would be closer to the edge, and some garbage scanlines in many games would be hidden (see Majoras Mask when changing area or Ogre Battle).
The fraction part should not be a problem because bilinear filters do a nice job and it could potentially solve problems caused when rendering to custom resolutions.
Cropping different amounts in each dimension would be against the VI emulation itself, and I find resizing each dimension by a different scale quite ugly. As for the hack to render to overscan, the important part of the game is in the center so it is probably not a very good idea to extend the small dimension (I can't see how it can be better than the second option).

In any case, the issue title should be changed into a feature request, as it is not an issue with emulation (or possibly closed and a feature request open).

**Comment by Mushman** [comment]
Well, all three fit different use cases.

Crop - Start with the set resolution but just get rid of the borders and leave the rest. Don't worry about the resolution or aspect ratio being different.
Scale - Resize the viewport to the set resolution as best as possible. Cropping out part of the scene or leaving a smaller remaining border is okay.
Render Overscan - Don't crop or scale the area, just extend the viewport to match the set resolution. If the game does weird stuff in the formerly inactive area, let it.

Each is useful, so it's important to understand them.

**Comment by gonetz** [comment]
Crop feature discussion:
https://github.com/gonetz/GLideN64/issues/805
