### ISSUE TITLE
Ocarina of Time: Map Select text shows as solid colors

### ISSUE THREAD

**Issue by notwa** [gonetz/GLideN64#495]
GLideN64:
![the_legend_of_zelda-015](https://cloud.githubusercontent.com/assets/1459466/7446566/3675ddbc-f191-11e4-94a3-ca07987658d5.png)
glide64mk2:
![the_legend_of_zelda-016](https://cloud.githubusercontent.com/assets/1459466/7446567/3e586e46-f191-11e4-840d-be53d3c0ddbb.png)

you can reach this menu in the game by either:
* running the Master Quest debug ROM and selecting the first save file
* using [the appropriate cheat codes][tcrfms] on a release version

[tcrfms]: https://tcrf.net/Proto:The_Legend_of_Zelda:_Ocarina_of_Time_Master_Quest/Map_Select#OoT_1.0

**Comment by notwa** [comment]
still an issue as of commit 74afd9f.
Project 64 2.2 savestate: [The Legend of Zelda - Ocarina of Time (U) (V1.0).pj.zip](https://dl.dropboxusercontent.com/u/9602837/temp/The%20Legend%20of%20Zelda%20-%20Ocarina%20of%20Time%20%28U%29%20%28V1.0%29.pj.zip)
no cheats or debug roms required!

**Comment by TheOlilink** [comment]
Would be nice if this can be fixed...

**Comment by AmbientMalice** [comment]
I think this is fixed. Likely by https://github.com/gonetz/GLideN64/commit/d8f8f587cf4ee6280612bf06befd96cdf1f6704e but I've only tested with mupen64plus, since that's the only version I can build.

![the_legend_of_zelda-001](https://cloud.githubusercontent.com/assets/10704701/13977629/7643b2fe-f116-11e5-81c4-7b7a44a629b3.png)

**Comment by olivieryuyu** [comment]
fixed, can it be closed?
