### ISSUE TITLE
Text issues on Intel HD

### ISSUE THREAD

**Issue by JamCR** [gonetz/GLideN64#512]
Using Project 2.2 and Intel HD Graphics 5500 (10.18.14.4170)

![2](https://cloud.githubusercontent.com/assets/12295203/7514840/5480e592-f4b9-11e4-9e30-e2b55774f5d8.png)
![3](https://cloud.githubusercontent.com/assets/12295203/7514842/5629fa28-f4b9-11e4-92d8-7c10b46d0af5.png)
![4](https://cloud.githubusercontent.com/assets/12295203/7514845/5803e2b4-f4b9-11e4-96a9-253da5e4f500.png)

**Comment by Talantyyr** [comment]
Similar Text issues with Diddy Kong Racing on a Intel HD 4000. (Just watch the intro and look at the texts). Think it's related to this issue.

**Comment by HeyAlucard** [comment]
I have the same issue with Intel HD 4600 Driver Version: 10.18.14.4170 
![untitled](https://cloud.githubusercontent.com/assets/12204238/7531676/6143bec2-f512-11e4-9e5d-c6ad7b9d7fdc.png)

**Comment by JamCR** [comment]
![1](https://cloud.githubusercontent.com/assets/12295203/7555274/b361cc80-f73d-11e4-9bf9-4fe9ad424d1d.png)

Yeah definitely not just Ocarina of Time

**Comment by vgturtle127** [comment]
I need some more info to help debug this.

I need info like operating system, specs of your PC, do you have latest drivers and DirectX, what other plugins are you using, etc.

**Comment by HeyAlucard** [comment]
I can definitely give more info.
Im using Windows 7 64 bit professional. i7 4790k cpu using intel hd
graphics 4600 driver : 10.18.14.4170
Direct x 11

**Comment by vgturtle127** [comment]
Do you guys have the latest drivers installed?

Do you have access to a computer with a graphics card to see if it is just the integrated graphics?

Also, do you have the latest DirectX and Windows updates installed?

I ask because recently Intel released drivers that fixed rendering problems with many DirectX and OpenGL applications running on integrated graphics.

**Comment by HeyAlucard** [comment]
Just double checked. I do have the latest drivers installed. I believe its
just integrated graphics but cant quote it just yet. I currently dont have
access to a graphics card. Im buying a graphics soon but not atm. uh let me
check for direct x. I dont have the latest windows updates installed. is
there any particular update i would need? Gimme one sec checking direct x

**Comment by vgturtle127** [comment]
You should always install the latest updates for Windows, regardless of what they are. They are mostly bug fixes and improvements nowadays.

What graphics settings are you using? This might be caused by a rendering issue. I believe other emulators have had problems with rendering text in various games and systems as well.

**Comment by HeyAlucard** [comment]
I'm using the default settings that comes with gliden64 1.1 no changes to
the settings will post screen shot of settings if needed

**Comment by vgturtle127** [comment]
Hm. I can't seem to replicate the problem. I am using Project64 2.2 with GlideN64, Azimers audio, NRAGE, and default settings.

Can I have a screenshot of your settings please?

**Comment by HeyAlucard** [comment]
![123](https://cloud.githubusercontent.com/assets/12204238/8143238/c5d58436-1157-11e5-832e-250896f80083.png)
![untitled](https://cloud.githubusercontent.com/assets/12204238/8143239/c82bd712-1157-11e5-8a22-a1c4534871e7.png)

**Comment by vgturtle127** [comment]
Could I also have a screenshot of the video tab, textures tab, and post filters tab?

I'd look myself but my computer is in storage at the moment.

**Comment by HeyAlucard** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12204238/8147494/7fd20dda-1222-11e5-8008-b5a3a6394659.png)
![untitled1](https://cloud.githubusercontent.com/assets/12204238/8147495/7fd54ec8-1222-11e5-91f3-aa765726e10a.png)
![untitled3](https://cloud.githubusercontent.com/assets/12204238/8147496/7ff1573a-1222-11e5-982a-579f6026d0d2.png)
![untitled4](https://cloud.githubusercontent.com/assets/12204238/8147497/7ff1e380-1222-11e5-915e-2d199c34c186.png)
Here is all the settings requested let me know if i can provide more [:

**Comment by vgturtle127** [comment]
Maybe try unchecking compress texture cache and save texture cache to hard disk?

Leave post filters and texture enhancement off.

Maybe try unchecking per game settings as well?

The only thing other than that that I can think of would be to mess with frame buffer settings. But try the other settings first.

**Comment by HeyAlucard** [comment]
sadly none of those settings that i changed fixed the issue :/

**Comment by vgturtle127** [comment]
Have you tried the framebuffer settings?

**Comment by phly95** [comment]
I found a solution. Get the Dell drivers instead of the drivers on Intel's website. There is still a glitch that exiting fullscreen and save states ruin everything (black screen) but that's a separate bug.

**Comment by HeyAlucard** [comment]
dell drivers? really? ill give it a try

**Comment by phly95** [comment]
Actually, I found it was because I got an outdated driver from dell. Because it's the new driver that causes this issue, downgrading with dell fixed the problem.

**Comment by phly95** [comment]
I have reported the issue to Intel here: https://software.intel.com/en-us/forums/topic/560079 we'll see if they respond to the issue.

**Comment by Talantyyr** [comment]
That's happening on my Surface Pro 3, the intel drivers are from Windows update (they are pretty new) , i won't install Dell drivers on my surface as i don't want to mess up my system. Would be nice if that can be fixed...

**Comment by vgturtle127** [comment]
Installing different drivers shouldn't "mess up your system". If anything, you might just need to re-install the old drivers or something. Anyway, I don't usually recommend integrated graphics for emulation or games, since mostly this happens.

**Comment by phly95** [comment]
What he means is that he has a Microsoft surface and not a dell machine, so he'd rather not risk it. On the other hand, dell just updated their drivers and now I'm stuck with a later version that has this issue.

**Comment by vgturtle127** [comment]
Oh, if we are talking about the surface I can note a few problems you will encounter. Thermal throttling, CPU bugs, driver issues, all kinds of stuff. Even on Surface 3.

**Comment by phly95** [comment]
Well, I am on a Dell Laptop, and now that Dell finally updated their drivers, and I don't have a copy of the old ones, it has this same problem. It worked before, it should work now. Damn intel you infidel!

**Comment by phly95** [comment]
Could you possibly pinpoint the driver issue that is causing this error in the first place? I would really like to start playing majora's mask again.

**Comment by vgturtle127** [comment]
I'm not sure if you were referring to me, but I'm going to assume anybody on integrated graphics or running a Surface Pro has the potential to run into problems due to the differences in how they work as opposed to dedicated graphics. Yes, integrated graphics are getting better, and yes, drivers and software are getting better at supporting integrated graphics, but I seem to always run into problems when I don't have dedicated graphics.

For example, my parents have a computer with integrated graphics and everything was slow, and they had many problems. Put a very low cost graphics card in and all the problems went away. I had the latest drivers and everything on the machine before, so I don't think it was an issue there.

This problem is hard to pinpoint, since it is most likely caused by hardware I don't have access to.

I would say it is definitely a integrated graphics problem, but I can't be for sure. After toying with settings, emulators, and trying different plugins, I really can't tell what the problem is.

I would suggest that you all fully update Windows, ensure you have the latest drivers, update Project64 if you aren't on the latest version, and update the plugins as well. If none of that works, then I would talk to Intel and see what they say. I would assume that they wouldn't care if it was causing issues in an emulator though, so they may just shrug it off and tell you to contact the project developers or something. Also, you may want to check your motherboard manufacturer website instead of Intel directly, because if they release drivers for it and they work better it may be because they optimize the drivers for their board. Unless those don't work as well as Intel drivers, then it would be vice-versa.

I don't know, without coding dirty hacks I don't think we can solve the problem without more research.

**Comment by phly95** [comment]
" Yes, integrated graphics are getting better" Thing is, this is a regression, and I can't find the old drivers I had anywhere, so I'm kinda stuck. It worked before, but then it ceased to work with the latest update. I did notify intel but they seem to be shrugging it off. Think I'll get an AMD next time I get a laptop, as they actually specialize in gaming.

**Comment by phly95** [comment]
I found the old version that I was using that allowed the plugin to work! Here it is: http://www.dell.com/support/home/us/en/19/drivers/DriversDetails?productCode=latitude-e7440-ultrabook&driverId=35GXP because this is the same GPU as the surface, it should install, or you should be able to extract the driver file and manual install.

**Comment by phly95** [comment]
OK, so you may not know how to extract an EXE file, so I did it for you *NOTE: THIS IS 64 BIT VERSION, please do not install the 64 bit driver on a 32 bit PC, if you need a 32 bit, Please ask.
So here is the x64 driver for intel HD 4000+ that allows GLideN64 to function as a zip in case dell locked the driver, so you can play on your surface/HP computer: 

https://app.box.com/shared/static/5wt60owwty8t4vnziyjj56fmfk1l42ho.zip

If setup.exe does not work for you, follow these instructions to force install on your PC. If something goes wrong (unlikely), enter safe mode and simply use windows update to get usable drivers:

    1. Login with administrator privileges
    2. Open Control Panel
    3. Open Device Manager
    4. Click on "Display adapters"
    5. Double click "Intel HD Graphics"
    6. Click on the "Driver" tab
    7. Click on "Update Driver" button
    8. Click on "Browse my computer for driver software"
    9. Click on "Let me pick from a list of device drivers on my computer"
    10. Click on "Have Disk" button
    11. Click "Browse"
    12. Navigate to the folder that you unzipped the Intel HD Graphics driver to
    13. Navigate to the Graphics sub-folder
    14. Double click the 3574-64 file
    15. Click "OK"
    16. Click "Next", Driver should now be installing.
    17. If successful, click "Close", Reboot.

**Comment by vgturtle127** [comment]
"AMD specializes in gaming"

No, they make hardware. Sometimes that hardware runs games, but that doesn't mean AMD specializes in anything. Intel and AMD and NVIDIA all just make stuff that runs stuff, whether that is a game, application, operating system, or anything else doesn't matter to them. If everything works, they feel good about what they make. Saying that AMD specializes in gaming is kind of like saying Microsoft specializes in gaming. Just because you make something that runs games doesn't mean that is your specialty. It's kind of like Valve, they make game engines and Steam/SteamOS, but that doesn't mean they specialize in Linux or web-based services. Do you get what I'm trying to say? :laughing: 

Anyway, I'm getting a feeling that maybe the driver issue is caused by the Intel driver due to the fact that Intel may be using the Intel compiler to make their driver. The Intel compiler seems to cause problems for everything that isn't designed to use it. I will contact them about this and see if I can get a response.

I have a feeling Intel won't care though. :disappointed:

**Comment by phly95** [comment]
Intel is finally responding https://communities.intel.com/message/314088 I hope they fix the issue on the newest driver soon :+1:

**Comment by vgturtle127** [comment]
Cool, hopefully they do something. Maybe they can tell us what is happening.

**Comment by gonetz** [comment]
May be Intel will add GLideN64 as test application for their drivers :)

**Comment by phly95** [comment]
It would make a pretty good test too as this plugin alone probably uses some of the most advanced features of opengl in a wide variety. I'd be surprised if they didn't.

**Comment by vgturtle127** [comment]
@gonetz If they do something like that, I will eat my hat (alright, fine, I don't have a hat).

Although, I suppose stranger things have happened.

@phly95 Good point, it does utilize a lot of OpenGL. I would think things like Dolphin, PCSX2, Citra, and the many SDL games would be good tests for the driver as well.

**Comment by phly95** [comment]
Well, it seems Intel is not going to fix the issue, however, I have found that LLE emulates the graphics perfectly. The issue with LLE is it is very slow when too many things come on the screen. I have also not experienced issues with other OpenGL applications, only GlideN64, so there must be some way to fix it. Remember, the Intel HD 4000 is the most popular GPU ever according to Steam, so by not supporting it, you alienate a huge potential userbase 
![capture](https://cloud.githubusercontent.com/assets/3526540/8939064/5a81835e-3530-11e5-8b6c-a725aa6a5256.PNG)

**Comment by phly95** [comment]
About 20% of all steam users have an Intel GPU of some sort, which means possibly around 1/5 potential players are eliminated from using GlideN64, and this is a bug that affects all Intel cards.

**Comment by phly95** [comment]
So, tried Windows 10. This brings it to a whole new level. Attempting to start GlideN64 causes a BSOD. The good thing is that this is a better motivation for MS and Intel to get their shit together.

**Comment by vgturtle127** [comment]
What does a Windows 10 BSOD look like? I have never seen one! :smiley:

**Comment by phly95** [comment]
basically the same as windows 8.
GOOD NEWS! If you follow these instructions http://www.lifehacker.com.au/2015/07/stop-windows-from-automatically-updating-your-hardware-drivers/
you can install the old Windows 8 drivers that I have posted on Windows 10. This fixes the problem that is caused in Project64, but unfortunately, that means other games may have performance issues due to old drivers. Not a huge deal if playing Project 64 games a lot.

**Comment by AmbientMalice** [comment]
Can anyone confirm whether this is still happening?

**Comment by vgturtle127** [comment]
@AmbientMalice Seems like text issues are exclusive to Intel graphics, perhaps? I have never encountered this bug in Project64...

**Comment by purplemarshmallow** [comment]
I tested with intel HD 5500
Seems to work with the latest drivers. I think this got fixed from intel's side
