### ISSUE TITLE
image glitches/scaling -native res rendering

### ISSUE THREAD

**Issue by fallaha56** [gonetz/GLideN64#540]
Hi just wondering about native resolution in Gliden64 -so many games have glitches from hi-res rendering/AA, slowdowns too...

Also the nVidia driver doesn't handle 640x480 or below :-(

So...would it be possible to render internally at say 1280x960 then scale down to native game res ~320x240 to give a really authentic N64 look but with effective 16x SSAA?

**Comment by Mushman** [comment]
Do you mean that NVidia cards don't support *fullscreen* resolutions which are 480p or less? I've certainly ran windowed sessions with low resolutions. Regardless, you might be able to work around that by setting a custom resolution in the NVidia Control Panel. I have set up a video mode for 856×480 for emulation before. Hopefully that helps you out. Although, I'm not sure I understand why you would want to use a low resolution but with SSAA instead of a larger one, but eh, no big deal.

**Comment by AmbientMalice** [comment]
If you have slowdown on an Nvidia card, make sure Prefer Maximum Performance is enabled in driver settings for your emulator.

**Comment by Gagert** [comment]
There was a plugin called angrylion's RDP that with some kind of mathmagic could output the real native resolution of N64 games. Until some time ago it was assumed by many that the native N64 res was 320x240 in all instances, but this plugin showed otherwise. After taking a couple of ingame screenshots, the image details showed that Mario 64 had a res of 320x238 (which was very common for N64 games) Perfect Dark 320x218 and Banjo-Kazooie 292x214.

If one is aiming for both a pixel perfect resolution and still be able to handle HD-like res on the 3d-models ingame, it would be great if this plugin had some kind of algorithm to always multiply the native res of the given game with a single digit. 

Let's say that I always choose to run the emulator in 1920x1080 and was going to play Banjo-Kazooie with both sharp polygons and square pixels. If the plugin then took the native res of the game at 292x214 and multiplied it with 5, the result would be the game running in 1460x1070. 

Sure it would be an awkward res, but if the plugin also added black borders to the rest of the image at 1920x1080, one could be spared of adding weird custom resolutions in nvidia control panel and such.

I don't know how hard such a feature would be to implement though, but as of now this plugin does a better job than most plugins at adding square pixels in N64 games. Personally I run Project64 with this plugin in 1280x960, because this is very close to the multiple of the native N64 screen resolution.

**Comment by AmbientMalice** [comment]
N64 games run at all sorts of eccentric resolutions. The N64 itself upscaled all graphics to 640x480, regardless of source.

Perfect Dark's American version runs internally at 640x222 in high resolution mode. Games such as Turok 2 run at 480x360. Rogue Squadron/Battle for Naboo/Indiana Jones run at 400x440 ingame.

**Comment by fallaha56** [comment]
@AmbientMalice @Gagert that's precisely it -there's no point in creating custom resolutions

it might make for a highly authentic N64 experience plus solve a few problems if the plugin could render this way -plus a little bit of supersample magic to smooth out the edges? ;-)

-also my resolution/speed issues prob relate to my HDMI amp and attempts to run@1080p 8x SGSSA...

@gonetz can it be done?

**Comment by thecoreyburton** [comment]
@fallaha56 Are you thinking something like "internal resolution" and "output resolution" as separate options? Internal resolution being what the plugin is rendering at (eg 2560x1920). Then output resolution being what you see on the screen (eg 640x480)?

**Comment by fallaha56** [comment]
Something very like that yeah.

To create an authentic look that leverages the GPU for an antialias boost (and that will work even with N64 depth compare):

1) leave screen resolution at desktop/native res, eg 1920x1080
2) plugin reads game's native N64 res and renders at x2 or x4 (640ish x 480ish etc)
3) plugin downsamples N64 graphics back to native res
4) plugin displays image +/- a lovely PAL/NTSC filter to blur, chromatic aberration etc

=old school N64, any thoughts?

**Comment by olivieryuyu** [comment]
@gonetz 

native resolution has been implemented so this ticket can be closed, no?

**Comment by gonetz** [comment]
Yes
