### ISSUE TITLE
SD Hiryu

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#590]
Menus run slow in HLE but are working fine in LLE

**Comment by LegendOfDragoon** [comment]
Interestingly, this particular issue seems to be an issue in every other HW gfx plugin, for me. GlideN64 LLE is the only HW plugin that doesn't run the menu at a ridiculously low speed.

When I profiled the menu with 1964 Video, a ridiculous amount of time spent was in CreateTexture. So it looks like most hardware plugins are constantly creating textures, because I notice the RAM usage of the emulator skyrockets in these slow menus.

I'd like to see how this kind of problem is fixed.

**Comment by gonetz** [comment]
What about z64? Is it slow too?

**Comment by LegendOfDragoon** [comment]
z64gl is at least 2x as slow as GlideN64 LLE, in the menu. That's still much better than any HLE plugin, where it's like 3 VI/s and the RAM usage gets abnormally high.

Z64gl's problem must be something else since the RAM usage doesn't skyrocket.

My guess is that something with the HLE code is causing it to constantly recreate textures.

**Comment by LegendOfDragoon** [comment]
@gonetz ,  I found a hack that fixes the performance problems for the menus, but idk what kind of possible side effects exist.

https://github.com/gonetz/GLideN64/blob/master/src/Textures.cpp#L1196

dividing numBytes by 32, significantly improves the performance for HLE in that game.

Hopefully this will help lead towards a proper fix. What I do know is that it's spending way too much time in CRC_Calculate().

**Comment by purplemarshmallow** [comment]
reminds me of #329

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/18419273/c8bb971e-780b-11e6-8164-6d0c4f4f1983.PNG)


Forgot How slow HLE really is.

Do we know why?

**Comment by theboy181** [comment]
@LegendOfDragoon anymore progress on this? should I close this ?

**Comment by olivieryuyu** [comment]
@gonetz 

I guess this one can be closed, no?

**Comment by gonetz** [comment]
Yes
