### ISSUE TITLE
Slowdown with framebuffer emulation enable (GLES)

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#592]
Here's a video of the slowdown, it happens while the birds start flying out of the tree (game speed is set at 250%)

https://dl.dropboxusercontent.com/u/27654797/mupen64plus-ui-console%202015-06-25%2018-21-00-29.avi

This seems to be caused by a dummy swapbuffer, here's a statistics graph showing draw calls (the slowdown starts after the red line ;-))

![sans titre](https://cloud.githubusercontent.com/assets/2852068/8359832/2b1324a0-1b69-11e5-8fba-cd0a4486637e.png)

And here's a list of GL calls during the dummy swapbuffer:

![sans titre2](https://cloud.githubusercontent.com/assets/2852068/8359927/b84e7324-1b69-11e5-866c-719c1ed13ebe.png)

Sounds like a useless call to ````FrameBufferList::renderBuffer(u32 _address)``` ;-)

**Comment by Gillou68310** [comment]
```const bool bNeedUpdate = gDP.colorImage.changed != 0 || (bCFB ? true : (*REG.VI_ORIGIN != VI.lastOrigin));```

@gonetz Is it really necessary to update on ```(*REG.VI_ORIGIN != VI.lastOrigin)``` (noob question here)?

The dummy swapbuffer happens when ```gDP.colorImage.changed == 0 && (*REG.VI_ORIGIN != VI.lastOrigin)```

**Comment by gonetz** [comment]
>Is it really necessary to update on (*REG.VI_ORIGIN != VI.lastOrigin)

Yes. Look:
- *REG.VI_ORIGIN != VI.lastOrigin means that game switches to another frame buffer. The case for double/triple buffering. We definitely must switch buffers too.
-  bCFB means that frame buffer is filled by CPU. Double buffering may not be used in that case, that is CPU may update the same buffer. Strange, but true. Thus, I can't rely on  *REG.VI_ORIGIN != VI.lastOrigin condition in that case. Dummy swapbuffer for CFB is a normal.
- gDP.colorImage.changed is less obvious condition. I thought that it is useless, because all games use at least double buffering when not in CFB mode. I had to add it for Quake II - it switches to single buffer mode when underwater. That is *REG.VI_ORIGIN != VI.lastOrigin does not work again and screen does not updated.

I set conditional breakpoint: gDP.colorImage.changed == 0 && (*REG.VI_ORIGIN != VI.lastOrigin)
It triggers constantly in SM64 while Mario head is on screen. The game swaps buffers not right after the buffer is drawn. That is first VI_UpdateScreen() after RSP_ProcessDList() uses old buffer. It would not cause buffers swap without gDP.colorImage.changed != 0. On next VI_UpdateScreen()  gDP.colorImage.changed == 0 (new display list is not ready yet), but *REG.VI_ORIGIN != VI.lastOrigin and buffers swap again. That does not cause any slowdown.

The situation is different in game. The breakpoint triggered the first time only when I closed to the bridge. The question is why dummy swapbuffer may cause slowdown? It is just render one screen-size texture rectangle. Your draw calls graph looks strange after the red line. Before the line number of calls is almost constant. After the line we see cyclic drops to zero followed by peaks, where number of calls is almost doubled. What causes these drops and peaks? I suspect that drops correspond to dummy swapbuffers which take only few commands. But what causes the peaks? Probably number of birds, which are polygonal, not just a sprite.

Please remove gDP.colorImage.changed != 0 condition, which is useless for this game and check performance again.

**Comment by Gillou68310** [comment]
Thanks for the detailed explanations, very instructive!!!

> I suspect that drops correspond to dummy swapbuffers which take only few commands. But what causes the peaks? Probably number of birds, which are polygonal, not just a sprite.

That's correct! Here's a new graph without gDP.colorImage.changed != 0 condition:

![sans titre](https://cloud.githubusercontent.com/assets/2852068/8396049/87498146-1d95-11e5-8c0e-af617f91e313.png)

Birds appear after the red line and the number of draw calls jump from ~110 to ~190

Also no more slowdown with removed condition ;-)

**Comment by gonetz** [comment]
>Also no more slowdown with removed condition ;-)

Interesting, why no more slowdown? Is it so expensive to draw one additional screen-size texture rectangle and swap buffers? Dummy swapbuffer does not cause slowdown with Mario head. Or does it? Could you test performance of Mario head scene with and without the "gDP.colorImage.changed != 0" condition?

**Comment by Gillou68310** [comment]
> Dummy swapbuffer does not cause slowdown with Mario head. Or does it? Could you test performance of Mario head scene with and without the "gDP.colorImage.changed != 0" condition?

Just checked and yes it's also slower in Mario's head scene!

> Is it so expensive to draw one additional screen-size texture rectangle and swap buffers?

Sounds weird indead! Maybe a double buffering issue!

**Comment by gonetz** [comment]
Thanks for testing! The results are informative.
I'd make "gDP.colorImage.changed != 0"  check optional if I knew a game where it cause slowdown in normal conditions, that is with frame limits on. Anyway it's useful to know that I have potential performance eater here.

**Comment by Gillou68310** [comment]
> I'd make "gDP.colorImage.changed != 0" check optional if I knew a game where it cause slowdown in normal conditions, that is with frame limits on

That might probably be the case on low end android device that's why I track it down in the first place ;-)

**Comment by Gillou68310** [comment]
Is quake2 the only game which requires the condition?

**Comment by gonetz** [comment]
>Is quake2 the only game which requires the condition?

I don't know. Quake II is the game, for which I added that condition. Probably it is the only one such game. I don't have time to test all games.

**Comment by Gillou68310** [comment]
Hum the eglswapbuffer beeing slow seems to be a common issue on android damn!

**Comment by Gillou68310** [comment]
Just thinking out loud but what would happen if we force to swap buffers only on last vi update, so no matter if a game is using double or even tripple buffering, swapbuffer will be called only once per frame?

**Comment by gonetz** [comment]
"last vi update" - what is it?
we must do FrameBufferList::renderBuffer and swap buffers when *REG.VI_ORIGIN changed.

Regarding buffer swap. Actually, it is possible to not use buffer swap at all, and render FBO right into front buffer. Original glN64 works exactly like that. Render to front buffer without buffers swap does not work on Linux for some reason though, so I had to use swapbuffers there. Since it works on other platforms as well, I decided to make it common. Later I found that GLES2 does not support glDrawBuffer command, so swap buffer was the only option.

I do't think that eglswapbuffer is a bottleneck, because it does not cause performance problems for other video plugins. mupen64plus-video-gliden64 is close to mupen64plus-video-gln64 in terms of OpenGL usage. It should have similar performance. The main difference is in shaders. GLideN64 fragment shaders are quite large, complex and have code, which is redundant for most games. Shaders simplification probably can boost performance on GLES2 devices.

**Comment by Gillou68310** [comment]
Maybe another driver issue! I will make some measurements just to be sure but it seems like the drivers is waiting for completion of eglswapbuffer when it should be mostly asynchronous.

**Comment by Gillou68310** [comment]
Ok here's my results:
![capture](https://cloud.githubusercontent.com/assets/2852068/8427555/91afb536-1f18-11e5-8d5c-f2569afe406f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2852068/8427556/92ccee16-1f18-11e5-9c53-bdc33048f088.PNG)

Blue line: Number of draw calls
Red line: Time spend in eglSwapBuffer function in milliseconds

You can see that the first five dummy swapbuffers are ok but suddenly it takes almost ~9ms to process the function.
This has been tested on both real GLES hardware and Power SDK emulator.

**Comment by Gillou68310** [comment]
Same graphs at 100% speed:
![capture](https://cloud.githubusercontent.com/assets/2852068/8428071/3af7c54a-1f1c-11e5-8c7b-227dd3bfbc79.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2852068/8428078/48468402-1f1c-11e5-977d-ea417143fdef.PNG)

**Comment by Gillou68310** [comment]
The same problem is present in zelda oot.

> I'd make "gDP.colorImage.changed != 0" check optional if I knew a game where it cause slowdown in normal conditions, that is with frame limits on

Maybe we can make it optional for GLES only? What do you think?

**Comment by gonetz** [comment]
Does it make visible performance gain on real device?

**Comment by Gillou68310** [comment]
Definitely! But don't hesitate to try on your Note3 if you want to see it in action (and have some time of course).

**Comment by Gillou68310** [comment]
I think the worse candidate is goldeneye because the problem is noticeable at 100% speed (actually the game is already slow but the dummy swapbuffer make it even worse)

Here's a savestate if you wanna try:
https://dl.dropboxusercontent.com/u/27654797/GoldenEye%20007%20(U)%20%5B!%5D.st0

**Comment by gonetz** [comment]
I believe you. Ok, I'll make "gDP.colorImage.changed != 0" check Quake 2 specific.

**Comment by Gillou68310** [comment]
Thanks! I hope it won't break anything else ;-)

**Comment by fzurita** [comment]
Instead of reducing accuracy for speed, maybe the right answer would be to have a config parameter to enable/disable this check.

This check could be disabled by default and a warning could be provided to a user that enables it saying that it "will improve accuracy but reduce performance". I believe this is the approach that Dolphin uses.

**Comment by gonetz** [comment]
It's not exactly accuracy VS speed problem. This check is a workaround for the problem, which probably exists for only one game. If the problem is more common, solution can include new config parameter.
