### ISSUE TITLE
Clipping Issue. (Multiple games.)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#634]
GLideN64 has a tendency to clip polygons close the camera. (Kinda reminds me of Jabo's on a bad day. GoldenEye is a useful reference.

![gliden64_goldeneye_000](https://cloud.githubusercontent.com/assets/10704701/8946221/15d6d0ae-35d2-11e5-8877-8911e58660ac.jpg)
)

This is how it should look.

![ngee0000](https://cloud.githubusercontent.com/assets/10704701/8946227/1b88af0e-35d2-11e5-95ee-f9432b1fd8b8.jpg)

edit:

Issue only seems to affected HLE. This is LLE. (Game has flickering depth issues, though. Like a mild version of Turok 2\3 rendering geometry through walls.)

![gliden64_goldeneye_001](https://cloud.githubusercontent.com/assets/10704701/8946509/3eb02780-35d4-11e5-96a9-71ef11fc5c15.jpg)

**Comment by purplemarshmallow** [comment]
>Issue only seems to affected HLE

In HLE the plugin tries to detect if a game uses near plane clipping (current.NoN=false) or not (current.NoN=true). This detection can be wrong.
Please test this build, near plane clipping is disabled by default
https://drive.google.com/file/d/0B7Y6r4SpC_QQOEkwNC1hRVd0RDA/view?usp=sharing

**Comment by AmbientMalice** [comment]
@purplemarshmallow This fixes GoldenEye. Still trying some other games looking for regressions.

(By the way, I can build GLideN64 myself now - just so you know.)

**Comment by theboy181** [comment]
Jelly!!!!

**Comment by purplemarshmallow** [comment]
I think it's best if I disable clipping only if a game needs it
Here's the fix for Goldeneye #662 
Are there other games with clipping problems?

**Comment by gonetz** [comment]
N64 performs clipping in RSP. RDP is just a rasterizer. Graphics plugin emulates only RDP work in LLE mode, thus it gets all polygons already clipped and has no clipping issues. With HLE, it emulates both RSP and RDP. Being OpenGL graphics plugin, GLideN64 uses OpenGL clipping. N64 clipping is more general than OpenGL one. OpenGL always clips polygon if it is out of defined viewport. N64 can set clipping area larger than the viewport, because sometimes it is faster to rasterize more pixels in RDP than perform polygon clipping in RSP. Some games use it. Also, near-plane clipping disabled in many microcodes. Name of such microcode usually contains 'NoN' substring. Custom ucode may not have 'NoN' in its name. GoldenEye uses custom ucode, which probably does not use near-clipping.

**Comment by AmbientMalice** [comment]
This should  be fixed now. Closed.
