### ISSUE TITLE
F-Zero X wrong borders

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#639]
borders around the vehicles are wrong. They should be black in the vehicle selection screen and red ingame. With GLideN64 they are green, with z64gl they are blue, with Jabo's software renderer they are correct.
![gliden64_f-zero_x_000](https://cloud.githubusercontent.com/assets/7283660/8971295/628a719e-364f-11e5-8036-57e4250f2fae.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/8971297/68d7a832-364f-11e5-8b28-9a50048c32ce.jpg)
![f-zero x u snap0000](https://cloud.githubusercontent.com/assets/7283660/8971298/6bc09fb8-364f-11e5-9b70-059273fb57e8.jpg)

**Comment by theboy181** [comment]
What are they with angrylions?

**Comment by purplemarshmallow** [comment]
They are black and red ingame, same as with Jabo's software renderer

**Comment by olivieryuyu** [comment]
extract from the Q&A of the manual:

 For the quality in the FZEROX setting screen, other than the environment map, are you also moving the light?

A11 The light is stationary and reflected. The method of having both the texture of the machine and the texture of the reflection coexist in the setting screen is, first to draw the machine, and then overwrite a translucent version of the same model with the reflection added as a decal. Incidentally, there is a black edge around the machine in the setting screen, but this serves to make the scale of the model slightly larger, and the black was rendered with the Z OFF. In other words, 3 overlaid models are rendered.

The model data are all identical with those in the game menu winning run. (Since LOD is not used in the game screen, a simplified version of the model at a distance is used...)

**Comment by alpharulesirulee** [comment]
try mupen64k or mupen64++

**Comment by olivieryuyu** [comment]
this is fixed, can it be closed?

**Comment by purplemarshmallow** [comment]
@gonetz can you reopen?
the borders should be red ingame
With GLideN64 they are black/blue
(press R or Z twice to attack, it will display the border)

![gliden64_f-zero_x_001](https://cloud.githubusercontent.com/assets/7283660/15403356/e9053c04-1df8-11e6-85fe-00e49a00ef44.jpg)
![cfze0001](https://cloud.githubusercontent.com/assets/7283660/15403355/e9050dc4-1df8-11e6-87d4-0996be0cd27a.jpg)

**Comment by gonetz** [comment]
Ok

**Comment by olivieryuyu** [comment]
Can it be closed?

**Comment by gonetz** [comment]
Yes, it is fixed.
