### ISSUE TITLE
Zelda OOT rotating "N" is miscolored (HLE)

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#661]
Top HLE (wrong)
Bottom LLE (correct)
explanation from angrylion: https://github.com/gonetz/glidehqplusglitch64/issues/227
![gliden64_the_legend_of_zelda_009](https://cloud.githubusercontent.com/assets/7283660/9283287/e428ed36-42d2-11e5-84d9-9b306377fee8.jpg)
![gliden64_the_legend_of_zelda_011](https://cloud.githubusercontent.com/assets/7283660/9283293/e6e1e438-42d2-11e5-91da-ddf9af12685c.jpg)

**Comment by purplemarshmallow** [comment]
angrylion: 
>First, the color combiner is actually fed with 9-bit values, which it 
sign-extends. After the computation 9 LSBs of the result are clamped to a 8-bit 
value, which goes to the blender. Zelda uses a "combined color" input in the 
2nd combiner cycle. Zelda relies on the fact that the combined color SHOULD NOT 
be clamped to 8 bits after the 1st cycle. Instead, it should go to the 2 cycle 
as a 9-bit value.

**Comment by gonetz** [comment]
GLideN64 combiner works the same for HLE and LLE. I guess, that LLE looks more correct because of lighting calculation. Vertex color is calculated by graphics plugin in HLE mode and RSP plugin in case of LLE.

**Comment by phly95** [comment]
I would love for this to be fixed too. It'll be awesome to have a fast but super accurate n64 experience like what we have with dolphin.

**Comment by gonetz** [comment]
Fixed in 2b29b6c09a.

HLE:
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/8983092/19756802/571f1510-9c49-11e6-944a-b3024f312141.png)

LLE:
![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/8983092/19756807/61e9594c-9c49-11e6-822b-8b7d6bf05b81.png)

**Comment by olivieryuyu** [comment]
does that fix the lights as well in game? :)

**Comment by gonetz** [comment]
Zelda OOT has no problems with lights iirc. Zelda MM has.
This fix is for so-called linear texture coordinates transformation. Texture coordinates for reflective textures generated on fly depending on angle between light direction and normal to surface. It is similar to vertex color calculation for lighting, but not the same. Thus, N logo is fixed in Zelda MM also, but lighting is not.

**Comment by angrylion7** [comment]
Just to clarify my original report. Here are screenshots taken with my plugin before and after the "no clamping of combined color before the 2nd stage" fix. The "before" image matches GlideN64 LLE very well and is incorrect. Please take a look at the great, thick strips of solid white in this real hardware capture on youtube. The moving texture "behind" the "NINTENDO" inscription is also affected: there are big patches of solid white with a pink-ish outline with the fixed version of my plugin and on real hardware, while the older version of my plugin and GlideN64 LLE show smooth transition to light blue and backwards to darker blue. Of course, this might be possible or impossible to do with OpenGL, I have no idea, I just wanted to clarify.

Video:
http://www.youtube.com/watch?v=67Z5VKTwAls

Before:
![12_0_rc4](https://cloud.githubusercontent.com/assets/16341594/19888529/2f078198-a040-11e6-9e57-904f628496c9.jpg)

After:
![12_0_rc5](https://cloud.githubusercontent.com/assets/16341594/19888535/3b5321be-a040-11e6-8438-ea286f979ae5.jpg)

After no. 2 (included this in the original report):
https://storage.googleapis.com/google-code-attachments/glidehqplusglitch64/issue-227/comment-0/Legend%20of%20Zelda%20OOT%20mine.png

**Comment by gonetz** [comment]
Hi, Sergey! Yes, I know about that difference,  but I don't understand what causes it. My combiner does not clamp color output between cycles. Result of the first cycle goes unclamped to the second stage. Result  of the second stage clamped and passed to blender. The N logo uses only texture and constant colors. I fixed texture coordinates generation and now HLE and LLE look the same. May be color clamp works incorrect. I noticed, that if color value is negative, it is clamped to zero, but if it is below -0.5, it becomes 1. It is implemented now.  I guess, if color is greater than 1.5 it should be turn to 0, but this is not implemented.

**Comment by angrylion7** [comment]
If we concentrate on the blue facet of the rotating "N" and on those pixels that are light blue in GlideN64 but should be much closer to solid white...
Here the 2nd cycle RGB combiner equation is (prim - env) * previous + env, primitive color red is 0xaa, and environment color red is 0. So the final result in the red channel is expected to be much greater than 0xaa to show something close to solid white. The "combined color" is a "C" term (multiplier) in the combiner equation. In my color_combiner_equation() function I sign-extend the "C" term such that bit 8 decides the sign, which differs from the handling of the other three terms. In the older version of my plugin I clamped the "combined color" to 8 bits beforehand, so it was between 0 and 255. If the "combined color" lies in that interval, there's no way that the final red product will be greater than 0xaa. Since only bit 8 of the "combined color" matters, it means that to fix these pixels the "combined color" must have had its bit 8 set for these pixels after my fix. The results of the combiner are clamped in this special_9bit_clamptable[] array in my plugin, which transforms any negative results to either 0 or 0xff, and the latter value is what we need. Since GlideN64 shows light blue (red staying somewhere around 0xaa), and you say you implemented this clamping, it means that clamping to either 0 or 0xff doesn't actually happen for these pixels in GlideN64. Maybe the "combined color" which goes to the 2nd cycle is non-negative in GlideN64, or you don't sign-extend it to make it negative the way I do.

**Comment by gonetz** [comment]
Combiner implemented in vertex shader and uses floats. All input colors (muxes) are in range [0, 1].
It differs from fixed point arithmetic you use, but in most cases produces the same result.
Of course, there is no control that color has 8 bits (plus sign bit), and in this case it seems to be important.

I saw special_9bit_clamptable[] array in your code. Its analog for floats is
```
float clamp(float c) {
if (c < -0.51) c = 1.0 else if (c < 0.0) = 0.0;
return c;
}
```
Lets look at the first cycle. The equation is (t0 - prim) * env.a + t0.
prim.red = 0xaa or 0.66, env.a = 0x80 or 0.5.
If t0 is < 0.223 or 0x38 the result is negative. Minimal possible result for red is -(prim.red * env.a) = -0.3346, when t0 = 0;
As you said, combiner equation for the second cycle is (prim - env) * previous + env.
prim.red = 0.66 env.red = 0.
If prim.red * previous.red< -0.51,  clamping will turn red component to 1.0. Otherwise it will be zero or positive for previous.red > 0.
Thus, previous.red must be < -0.765 As I explained, minimal possible value for it is -0.3346.
I guess that  "sign-extend" fixed point magic does necessary transformation.

**Comment by angrylion7** [comment]
Ah, you're right. So the "combined color" cannot be low enough, but it can easily exceed 1.0, right? Which then makes it negative under my sign-extension for a "C" term, so, for example, 1.03125 (0x108) becomes -0.96875 (0xff08 if it's a two-byte variable).

**Comment by Frank-74** [comment]
Love this sort of conversation.  You're both right?

You'd make a great team.

**Comment by standard-two-simplex** [comment]
@gonetz The formula you wrote `(t0 - prim) * env.a + t0` isn't an interpolation. I think it should be something like `(t0 - prim) * env.a + prim` which equals to `t0*env.a + prim*(1-env.a)`. In this last case, if all input data is in a range `[0,1]`, then the result is also in that range.

Would you mind pointing to the code in your repository doing blending calculation and the code transforming this data from N64 integers to floats?

**Comment by gonetz** [comment]
1.03125 (0x108) becomes -0.96875 (0xff08) That just great! I did not think about such transformation.  Yes, 1.03*0.66=.0.67, not even close to 1. From the other side, -0.96875*0.66=-0.645 and it will be clamped to 1!
I need formula, which "sign extends" floats.

**Comment by gonetz** [comment]
@standard-two-simplex N64 combiner formula is (A - B) * C + D, where all parameters are color inputs. Programmers can use any combination, does not matter is it interpolation or not. (t0- prim) * env.a + t0 is valid equation, which is user on first cycle of two cycle combiner. It is programmed by Nintendo that way, obviously to get that particular result.

The vertices load and transformations performed in gSPVertex and functions called from it.

**Comment by gonetz** [comment]
> I need formula, which "sign extends" floats.

I guess it is should work as 

```
float sign_extend(float c) {
  if (c > 1.0)
    c = -2.0 + c;
  return c;
}

```

`color = color + vec4(-2.0) * (1.0 - step(color, vec4(1.0)));`

does the trick. 

`color = color + vec4(-2.0) * step(1.0, color));`
is simpler, but it will turn 1.0 to -1.0, which is not right.

![gliden64_the_legend_of_zelda_005](https://cloud.githubusercontent.com/assets/8983092/19916449/9eb0dc36-a0ec-11e6-93c0-07c2c7d2a8b8.jpg)

@angrylion7 - thanks again!

**Comment by standard-two-simplex** [comment]
But how does the N64 do the multiplication? Does it do as simple integers?

0x108 * 0xAA = 0xAF50 which results in 0x150 when wrapped to 9 bits. 0x150 = 1.3125 in fixed point or -0.6875 which is different to the multiplication in floating points. 

In fact, to pass from integers to floating points, you divide by 255 so when multiplying two floating points you divide twice by 255 and ignore the wrapping.

Am I wrong?

**Comment by gonetz** [comment]
Cite angrylion's sources:
```
INT32 color_combiner_equation(INT32 a, INT32 b, INT32 c, INT32 d)
{
	a = KURT_AKELEY_SIGN9(a);
	b = KURT_AKELEY_SIGN9(b);
	c = SIGN9(c);
	d = KURT_AKELEY_SIGN9(d);
	a = (((a - b) * c) + (d << 8) + 0x80);
	a = SIGN17(a) >> 8;
	a = special_9bit_clamptable[a & 0x1ff];
	return a;
}

```

Combiner equation produces the same result with integers and floats when all input color components are in range [0, 0xFF]. When result is out of these bounds, we have discrepancy.

**Comment by standard-two-simplex** [comment]
> This combiner equation on integers produces the same result as mine equation on floats when all input color components are in range [0, 0xFF] for integers or [0, 1] for floats.

Are you sure? I have checked angrylions combiner equation but couldn't find yours. However, notice that multiplying as integers and then passing to floats is not equivalent to passing to floats and then multiplying.

For the combiner equation,
`((a-b)*c+d)/255` is not the same as `(a/255-b/255)*(c/255)+d/255 = ((a-b)*c)/(255*255) + d/255`    

Furthermore, if you multiply the value you got before `1.03125*0.666666 = 0.6874` by `255`  you get `175.3125` approximately which "wraps" to `1.3125` (or `-0.6875 if you prefer)` , the same value as when you compute with integers.

**Comment by gonetz** [comment]
N64 work of combiner equation:
(((a - b) * c) + (d << 8) + 0x80)>>8
Result is sign-extended and clamped to [0, 0xff ]
GL works with float color components in range [0, 1]. All colors transformed from int to [0, 1] floats before sending to GL. Fragment shader computes combiner equation as
(a-b)*c+d 
result is clamped back to [0, 1]. 
When result of integer combiner is in range [0, 0xff ], result of float combiner also will be in range [0, 1]. Sign-extend and clamping will not change it, so results of two versions of the combiner are the same. If result is out of range, sign-extend and clamping will lead to discrepancy. Float version has no sign extension, and clamping works as clamping, wrapping not taken into account.

**Comment by gonetz** [comment]
Just noticed another result of "sign-extension" in shaders.
Paper Mario torches. Before
![gliden64_paper_mario_001](https://cloud.githubusercontent.com/assets/8983092/20010429/a8715bc0-a2da-11e6-9ec6-0e702ad1e7c2.jpg)
Now
![gliden64_paper_mario_000](https://cloud.githubusercontent.com/assets/8983092/20010439/af29e6da-a2da-11e6-9947-50b259aff242.jpg)
angrylion's plugin
![nmqe0002](https://cloud.githubusercontent.com/assets/8983092/20010469/c3b9278c-a2da-11e6-8590-b34ae6a63f18.jpg)

**Comment by AmbientMalice** [comment]
That's wonderful. No doubt accuracy improvements like this have subtly improved accuracy all over the place.

**Comment by angrylion7** [comment]
@gonetz  As of the latest emucr build, these torches do not perfectly match my plugin or this real hardware capture (timecode included in the link):
https://www.youtube.com/watch?v=4ckABMM5Tww&t=3500s
, because holes in the fire constantly form and disappear with GlideN64. Also, I'm quite certain that the RDP doesn't skip sign-extending the "combined alpha". Maybe the problem is something else? Here the "combined color (RGB)" is also used, but as a "D" term. The "D" term is sign-extended in a different fashion.

**Comment by gonetz** [comment]
>I'm quite certain that the RDP doesn't skip sign-extending the "combined alpha".

I had doubt that my fix is correct. 

 > The "D" term is sign-extended in a different fashion.

Could you explain, how? Or point on the place in your code.

**Comment by angrylion7** [comment]
Yeah, special_9bit_exttable[] array here:
https://sourceforge.net/p/angrylions-stuff/code/HEAD/tree/trunk/mylittle-nocomment/n64video.cpp#l2401

So, for example, 0x17f (approximately 1.496) remains the same, while 1.53125 (0x188) becomes -0.46875 (0xff88).

**Comment by gonetz** [comment]
Thanks!

**Comment by gonetz** [comment]
@angrylion7 
> So, for example, 0x17f (approximately 1.496) remains the same, while 1.53125 (0x188) becomes -0.46875 (0xff88). As for negative values, -0.46875 remains the same, while -0.9375 (0xff10) becomes 1.0625 (0x110).

That is, for floats it should look like:
if (color > 1.5)
 color -= 2.0;
else if (color < -0.5)
 color += 2.0

right?

**Comment by gonetz** [comment]
BTW, Paper Mario fire
```
color combine: #1: (TEXEL0-CENTER)*SCALE+ENVIORNMENT, #2: (0-PRIMITIVE)*COMBINED+ENVIORNMENT
alpha combine: #1: (0-0)*0+TEXEL0, #2: (0-0)*0+COMBINED

```
That is only combined alpha is used as D term.

**Comment by angrylion7** [comment]
Ah, sorry, I must have confused some triangles in Ziggy's debugger, which led to my previous post. Glad that you've nailed the problem.

**Comment by gonetz** [comment]
@angrylion7 Please confirm that I correctly understand things with sign-extension and color clamping:

pseudo code:

```
float clamp(float c) 
{
  if (c < -0.5)
    return 1;

  if (c < 0.0)
    return 0;

  if (c > 1)
    return 1:

  return c;
}

float sign_extent_abc(float c) {
   if (c > 1.0)
     return c - 2.0;

   return c;
}

float sign_extent_d(float c) {
   if (c > 1.5)
     return c - 2.0;

   if (c < -0.5)
      return c + 2.0;

   return c;
}

float cmb_c = color_combiner_1cycle();
float cmb_a = alpha_combiner_1cycle();
float res_c, res_a;

if (otherMode.cycleType == 1CYCLE) {

  res_c   = sign_extend_abc(cmb_c );
  res_c = clamp(res_c );

  res_a = sign_extend_abc(cmb_a);
  res_a = clamp(res_a);

} else if (otherMode.cycleType == 2CYCLE) {

   if (combined_color_usage == D_MUX)
      cmb_c = sign_extend_d(cmb_c);
    else
      cmb_c = sign_extend_abc(cmb_c);

   if (combined_alpha_usage == D_MUX)
      cmb_a = sign_extend_d(cmb_a);
    else
      cmb_a = sign_extend_abc(cmb_a);
 
   res_c = color_combiner_2cycle(cmb_c);
   res_c = clamp(res_c);

   res_a = alpha_combiner_2cycle(cmb_a);
   res_a = clamp(res_a);
}

```

**Comment by angrylion7** [comment]
So why was the suppression of "combined alpha" sign-extension beneficial to Paper Mario? It shouldn't matter with the equations you posted. There are other triangles at play here then, right?

As I told you above and as illustrated by the code snippet from my plugin that you posted above, it is the "C" term that is heterodox, while "A", "B" and "D" undergo the same, weirder sign-extension. Notice these quotes from this present discussion: 
>I sign-extend the "C" term such that bit 8 decides the sign, which differs from the handling of the other three terms.

>Gonetz posted the code snippet from the earlier version of my plugin, which conceptually matches the current version

>The "D" term is sign-extended in a different fashion.  (referring to the only type of sign-extension you implemented in GlideN64 at the time of my writing)

So probably rename the 2nd function to sign_extend_c(), the 3rd function to sign_extend_abd() and make changes below in accordance with that, checking for C_MUX rather than D_MUX.

Other than that, your functions should work for the majority of cases, but you don't cover the same intervals I do, right? For instance, it's easy to see that the final result can be less than -1.0, so you should probably begin your clamp() function with 
`if (c < -1.0) return c + 2.0;`
The final result can also be greater than 1.5, so the clamp() function should end with something like
`if (c > 1.5) return 0; if (c > 1.0) return 1;`
Since "A", "B" and "D" can be greater than 1.0 after their sign-extension, the final result can also be greater than 2.0, which I also handle properly, unless I'm not mistaken somehow. I think in my plugin the final result can be up to 3.5, if the "combined color" is sign-extended to somewhere around 1.49 under "ABD" extension:
(1.49 - (-0.5 from "k4" or YUV)) * (1.0 from anywhere) + 1.49.

In my plugin the "D" term can be negative in the 1st cycle (YUV red and green texels and also combined color from the previous pixel),  and, like all the inputs, it undergoes sign-extension also before the 1st cycle,  which therefore means that if I was somehow magically teleported to the floating-point world,  I would have to cover -2.0... -1.0 in both sign-extension variants, which you don't do.

This I don't understand:
```
res_c   = sign_extend_abc(cmb_c );
res_c = clamp(res_c );
```

Do you want to sign-extend after the one-cycle combiner but before clamping? My plugin doesn't work that way. Maybe a typo?

**Comment by gonetz** [comment]
@angrylion7 
> So why was the suppression of "combined alpha" sign-extension beneficial to Paper Mario?

I removed color clamping to [0, 1] before blending after I added "N64 style" clamping. As you correctly noticed, my clamping equation  does not cover all possible cases. Since blending uses combined alpha, result was wrong. Clamping removal also caused holes in flames after I removed "combined alpha" sign-extension.

> As I told you above and as illustrated by the code snippet from my plugin that you posted above, it is the "C" term that is heterodox, while "A", "B" and "D" undergo the same, weirder sign-extension. 

Missed that, thanks.

> Other than that, your functions should work for the majority of cases, but you don't cover the same intervals I do, right? ... I was somehow magically teleported to the floating-point world, I would have to cover -2.0... -1.0 in both sign-extension variants, which you don't do.

True.

> Do you want to sign-extend after the one-cycle combiner but before clamping? My plugin doesn't work that way. Maybe a typo?

It's not typo, it's mistake :) I thought that result is always sign-extended after the first cycle.

You made things much clearer for me, many thanks! I not always can understand what your code does just by reading the code; debugger needed to see what happened with processed values. It was very kind from your side to pay visit to our floating-point world :)

**Comment by gonetz** [comment]
@angrylion7 
Corrected pseudo-code

```
float clamp(float c) 
{
  if (c < -1.0) return c + 2.0;

  if (c < -0.5) return 1;

  if (c < 0.0) return 0;

  if (c > 1.5) return 0;

  if (c > 1.0) return 1;

  return c;
}

float sign_extent_c(float c) {
   if (c > 1.0)
     return c - 2.0;

   return c;
}

float sign_extent_abd(float c) {
   if (c > 1.5)
     return c - 2.0;

   if (c < -0.5)
      return c + 2.0;

   return c;
}

float cmb_c = color_combiner_1cycle();
float cmb_a = alpha_combiner_1cycle();
float res_c, res_a;

if (otherMode.cycleType == 1CYCLE) {

  res_c = clamp(cmb_c);

  res_a = clamp(cmb_a);

} else if (otherMode.cycleType == 2CYCLE) {

   if (combined_color_usage == C_MUX)
      cmb_c = sign_extend_c(cmb_c);
    else
      cmb_c = sign_extend_abd(cmb_c);

   if (combined_alpha_usage == C_MUX)
      cmb_a = sign_extend_c(cmb_a);
    else
      cmb_a = sign_extend_abd(cmb_a);

   res_c = color_combiner_2cycle(cmb_c);
   res_c = clamp(res_c);

   res_a = alpha_combiner_2cycle(cmb_a);
   res_a = clamp(res_a);
}

```

**Comment by angrylion7** [comment]
@gonetz Very well, but if for some reason you would like to ensure some autistic-level robustness in your code, I would humbly advise to also treat the 2.0...3.0 interval in the clamp() function, however unlikely such a combiner equation might be. As I said, in my plugin the maximum final result can probably be close to 3.5, but, even if with GlideN64 it's not possible to have either a negative "k4", or a negative "YUV" as a "B" term, the final result can still be up to 3.0, if the "combined color" is ABD-extended to approximately 1.49:
(1.49 - 0) * 1.0 + 1.49.
So  I would edit the 2nd logical half of the clamp() function like this, I just omitted this in my previous post, considering it too analogous and also insignificant to be worth an explicit mention:
`if (c > 2.0) return c - 2.0; if (c > 1.5) return 0; if (c > 1.0) return 1.0;`

**Comment by gonetz** [comment]
@angrylion7 Thanks!

**Comment by gonetz** [comment]
@fzurita 

```
float clamp(float c) 
{
  if (c < -1.0) return c + 2.0;

  if (c < -0.5) return 1;

  if (c < 0.0) return 0;

  if (c > 2.0) return c - 2.0; 

  if (c > 1.5) return 0;

  if (c > 1.0) return 1;

  return c;
}

```

How to express that with step instead of if?

**Comment by fzurita** [comment]
Hmm, that looks interesting, I'll have to think about that one.

**Comment by gonetz** [comment]
My variant

```
lowp vec4 Clamp(in lowp vec4 col)
{			
  lowp vec4 one = vec4(1.0);
  lowp vec4 two = vec4(2.0);
  lowp vec4 stepM1 = one - step(vec4(-1.0), col);
  lowp vec4 stepMDot51 = step(col, vec4(-0.51)) * (one - stepM1);
  lowp vec4 stepZero = (one - step(vec4(0.0), col)) * (one - stepMDot51);
  lowp vec4 step2 = one - step(col, two);
  lowp vec4 step1dot49 = step(vec4(1.49), col) * (one - step2);
  lowp vec4 step1 = (one - step(col, vec4(1.0))) * (one - step1dot49);
  return (col + two)*stepM1 + stepMDot51 + col*(one - stepZero) + step1 + col*(one - step1dot49) + (col - two)*step2;
}																		\n"

```

But I works wrong. Either idea is wrong, or I made a mistake somewhere.

**Comment by gonetz** [comment]
I found one mistake. Partial implementation:

```
lowp vec4 Clamp(in lowp vec4 col)
{
  lowp vec4 one = vec4(1.0);
  lowp vec4 two = vec4(2.0);
  lowp vec4 stepM1 = one - step(vec4(-1.0), col);
  lowp vec4 stepMDot51 = step(col, vec4(-0.51)) * (one - stepM1);
  lowp vec4 stepZero = (one - step(vec4(0.0), col)) * (one - stepMDot51);
  lowp vec4 step2 = one - step(col, two);
  lowp vec4 step1dot49 = step(vec4(1.49), col) * (one - step2);
  lowp vec4 step1 = (one - step(col, vec4(1.0))) * (one - step1dot49);
  lowp vec4 inrange = step(vec4(0.0), col) * step(col, vec4(1.0));
//  return col*inrange + (col + two)*stepM1 + stepMDot51 + (one - stepZero) + step1 + (one - step1dot49) + (col - two)*step2;
  return col*inrange + (col + two)*stepM1 + stepMDot51;	
  }																		\n"

```

**Comment by fzurita** [comment]
Here is my version:

```
float output = c;
output += step(c, -1.0)*2;
output = step(c, -0.5) + output*step(-0.5, c);
output = step(0.0, c) + output*step(c, 0.0);
output -= step(2.0, c);
output = step(c, 1.5) + output*step(1.5, c);
output = step(1.0, c) + output*step(c, 1.0);
```

**Comment by gonetz** [comment]
Your version looks promising. There is a problem:
step(c, -1.0) will return 1 for c == -1.0.
The condition is c < -1.0

**Comment by fzurita** [comment]
Right, so you could use -1.01, or whatever the next increment in fixed point is.

**Comment by gonetz** [comment]
Bad idea. I use inversion: 1.0 - step(-1.0, c)

You variant has issues too. Everything is white.

**Comment by fzurita** [comment]
Hmmm, not good, something must be missed, did you catch the error I made?

**Comment by gonetz** [comment]
Not yet.

**Comment by fzurita** [comment]
I did make one in the 5th line, missed a factor of 2.

**Comment by gonetz** [comment]
I put my changes to a branch: 556bf3286a7

**Comment by gonetz** [comment]
> I did make one in the 5th line, missed a factor of 2.

Fixed. Still white.

**Comment by gonetz** [comment]
I got my version working:
```
lowp vec4 one = vec4(1.0);
lowp vec4 two = vec4(2.0);
lowp vec4 stepM1 = one - step(vec4(-1.0), col);
lowp vec4 stepMDot51 = step(col, vec4(-0.51)) * (one - stepM1);
lowp vec4 stepZero = (one - step(vec4(0.0), col)) * (one - stepMDot51);	
lowp vec4 step2 = one - step(col, two);
lowp vec4 step1dot49 = step(vec4(1.49), col) * (one - step2);
lowp vec4 step1 = (one - step(col, vec4(1.0))) * (one - step1dot49);
lowp vec4 inrange = step(vec4(0.0), col) * step(col, vec4(1.0));
vec4 res = col*inrange + (col + two)*stepM1 + stepMDot51 + step1 + (col - two)*step2;
return res * (one - stepZero) * (one - step1dot49);

```
It is clumsy in compare with yours though.

**Comment by fzurita** [comment]
I found my mistake, correction coming.

**Comment by gonetz** [comment]
Ok, I'll check it tomorrow. Thanks in advance. Good night.

**Comment by fzurita** [comment]
```
float output = c;
output += step(c, -1.0)*2;
output = step(c, -0.5) + output*step(-0.5, c);
output = output*step(0.0, c);
output -= step(2.0, c)*2;
output = step(c, 1.5) + output*step(1.5, c);
output = step(1.0, c) + output*step(c, 1.0);
```

**Comment by fzurita** [comment]
Good night

**Comment by gonetz** [comment]
Better, but still incorrect. I pushed your changes to the fix_clamp branch. 
fragment_shader_clamp in Shaders_ogl3x.h
My variant here too, as working reference.

1.27 AM. Can't sleep :(

**Comment by fzurita** [comment]
Hmm, great, I'll have to see if there are other flaws. What are you using to test for reference?

**Comment by gonetz** [comment]
Zelda OOT

**Comment by fzurita** [comment]
I found more errors, getting warmer though:
```
" vec4 res = col; \n"
" res += step(res, vec4(-1.01))*2.0; \n"
" res = step(res, vec4(-0.51)) + res*step(vec4(-0.51), res);	\n"
" res = res*step(vec4(-0.01), res); \n"
" res -= step(vec4(2.01), res)*2.0;				 \n"
" res = res*step(res, vec4(1.51)); \n"
" return step(vec4(1.01), res) + res*step(res, vec4(1.01));	\n"

**Comment by fzurita** [comment]
I tested this and I don't see any obvious graphical errors in the output.

**Comment by standard-two-simplex** [comment]
> ```
float clamp(float c) 
{
  if (c < -1.0) return c + 2.0;
  if (c < -0.5) return 1;
  if (c < 0.0) return 0;
  if (c > 2.0) return c - 2.0; 
  if (c > 1.5) return 0;
  if (c > 1.0) return 1;
  return c;
}
```

Sorry for the delay. I just saw it and wanted to pinpoint one thing.

This algorithm seems like a regular clamp provided that the number is interpreted in the proper way.
If you interpret numbers with bites 7 or 8 different to one as positives (0 , 1.5) and numbers with bites 7 and 8 as negatives (-0.5 , 0) then it becomes a regular clamp. You only need to take care about the operation getting out of this range before applying it.

 I saw that in Angrylions code bit 18 is ignored, so I guess you need to emulate overflow (I'm gonna call this to wrap), which I think is being done with +2.0 and -2.0. Then the code could look something like this.

```
float wrap ( float c) {
    if (c < -0.5) c += 2.0;
    if (c > 1.5) c -= 2.0;
    return c;
}
 ```
or for vectors
```
float wrap (vec3 c) {
    return c + 2*(1-step(c , 0.5)) + (-2)*step(c,1.5);
}
```
I think that then you would need to call this `wrap` function and the regular glsl `clamp(c,0,1)` function to achieve the same thing. I changed the (c<1) to (c<0.5) because values between (-1, -0.5) would be transformed to (1, 1.5) after summing 2 and thus clamped correctly.

Tell me if I made a mistake.

**Comment by gonetz** [comment]
Thanks!
I currently use my version. I think that compare with 1.01 is not right and can to lead to hard to find issues.
May be I'll rewrite your version later with inversions, since your version uses less calculations.

**Comment by fzurita** [comment]
That solution looks a lot simpler than what I proposed. I mistook the forest for the trees.

May this be a little simpler?
```
float wrap (vec3 c) {
    return c + 2*(step(0.5, c )) + (-2)*step(c,1.5);
}
```

**Comment by gonetz** [comment]
@standard-two-simplex I'll try it right now, thanks! I don't see mistakes in your calculations.

**Comment by gonetz** [comment]
@standard-two-simplex 
```
lowp vec4 res = col + 2.0*(step(-vec4(0.5), col)) - 2.0*step(col, vec4(1.5));
// lowp vec4 res = col + 2.0 * (vec4(1.0) - step(col, vec4(-0.5))) -2.0*step(col, vec4(1.5)); // is the same
return clamp(res, 0.0, 1.0);

```
Result is somehow incorrect:
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/8983092/20246183/0542dc42-a9e4-11e6-82b6-041a84e9ea7c.jpg)

**Comment by gonetz** [comment]
```
 lowp vec4 res = col + 2.0 * step(col, vec4(-0.5)) - 2.0*step(vec4(1.5), col);
 return clamp(res, 0.0, 1.0);

```
seems to work

**Comment by standard-two-simplex** [comment]
I can't spot the mistake.

I think the only cases when the result might be different is when you try to clamp a value outside of the range (-2.5,3.5). For example, following the first algorithm, 3.8 would return 1.8 while the second algorithm would return 1.

Are such inputs possible? I assumed that the values come from the equation `(a-b)*c+d` and that `-0.5<=a,b,d<1.5` and `-1<=c<1`. Then you would have, `-2.5 < (a-b)*c+d < 3.5`. Can you use a value out of those ranges for a,b,c or d? And if so, what should the expected behavior be?

**Comment by gonetz** [comment]
Yes, all known problems fixed. Thanks!

**Comment by standard-two-simplex** [comment]
Just saw you last post. True, I was stepping the wrong way xD.

**Comment by gonetz** [comment]
> I can't spot the mistake.

You wrote step wrongly.

**Comment by gonetz** [comment]
:)

**Comment by purplemarshmallow** [comment]
so I mixed up 2 different issues :/
both fixed now!

**Comment by gonetz** [comment]
Yes, minor bugs often are hardest to fix.
