### ISSUE TITLE
Extreme-G XG2 lighting issue on the intro ring

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#680]
The problem starts when the noise/dither effect sets in

Before the noise/dither effect sets in
![gliden64_extreme_g_2_000](https://cloud.githubusercontent.com/assets/13789606/9426779/3b6de7ac-4956-11e5-9156-206e40df0017.png)
Wrong (broken lighting when the noise/dither effect sets in)
![gliden64_extreme_g_2_001](https://cloud.githubusercontent.com/assets/13789606/9426793/e4e080a6-4956-11e5-864c-d673dce89064.png)
Correct (angrylion's RDP)
![ng2p0001](https://cloud.githubusercontent.com/assets/13789606/9426794/ec157890-4956-11e5-9ac2-d4ec86a11ab5.png)

**Comment by gonetz** [comment]
I can't see the difference between the second and third screen shots.

**Comment by AmbientMalice** [comment]
Maybe these ugly red lines will help.
![e4e080a6-4956-11e5-864c-d673dce89064](https://cloud.githubusercontent.com/assets/10704701/10570070/5f28b7be-7672-11e5-86e9-84b8149eb8cc.png)
GLideN64's noise is a tad prone to banding, but the original N64 is so low resolution is can be hard to tell whether the behavior is accurate. (The World is Not Enough has significant banding on white ceilings in 16 bit colour mode.)

**Comment by Cetacea3691** [comment]
I think there are two or three issues here.
1. GLideN64 isn't emulating chromatic noise.
2. The noise pattern seems to be inverted?
Because this issue is quite difficult to explain please use this preconfigured [Project64 build](https://drive.google.com/file/d/0Bygxj1zIGEscTEZCd09IMzlNRFE/view?usp=sharing) and boot Extreme-G XG2.
p.s. You have to use Project64's ROM browser otherwise @cxd4's rdp_conf and rsp_conf detection will fail and the configuration will be lost.

**Comment by olivieryuyu** [comment]
fixed?

**Comment by gonetz** [comment]
Yes, I think it is fixed now. With @gizmo98 fixes in dithering code I see no color banding on the intro ring.
