### ISSUE TITLE
convert CPU reads/writes into callbacks

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#684]
I got this advice from degasus, a dolphin developer
>you should look for a way to detect when the CPU is trying to access the memory range. Those read & writes can be transformed in callbacks which to all of this ugly copying work "live". 

Copying to and from RDRAM is very ugly indeed. CPU based effects should be emulated this way. Emulator and gfx developers need to work together on this one.

**Comment by gonetz** [comment]
1964 team added an extension to Zilmar's specs:

/******************************************************************
Function: FrameBufferRead
Purpose:  This function is called to notify the dll that the
frame buffer memory is beening read at the given address.
DLL should copy content from its render buffer to the frame buffer
in N64 RDRAM
DLL is responsible to maintain its own frame buffer memory addr list
DLL should copy 4KB block content back to RDRAM frame buffer.
Emulator should not call this function again if other memory
is read within the same 4KB range
input:    addr          rdram address
val                     val
size            1 = wxUint8, 2 = wxUint16, 4 = wxUint32
output:   none
*******************************************************************/
EXPORT void CALL FBRead(wxUint32 addr)

/******************************************************************
Function: FrameBufferWriteList
Purpose:  This function is called to notify the dll that the
frame buffer has been modified by CPU at the given address.
input:    FrameBufferModifyEntry *plist
size = size of the plist, max = 1024
output:   none
*******************************************************************/
EXPORT void CALL FBWList(FrameBufferModifyEntry *plist, wxUint32 size)

/******************************************************************
Function: FrameBufferWrite
Purpose:  This function is called to notify the dll that the
frame buffer has been modified by CPU at the given address.
input:    addr          rdram address
val                     val
size            1 = wxUint8, 2 = wxUint16, 4 = wxUint32
output:   none
*******************************************************************/
EXPORT void CALL FBWrite(wxUint32 addr, wxUint32 size)

/************************************************************************
Function: FBGetFrameBufferInfo
Purpose:  This function is called by the emulator core to retrieve frame
buffer information from the video plugin in order to be able
to notify the video plugin about CPU frame buffer read/write
operations

size:
= 1           byte
= 2           word (16 bit) <-- this is N64 default depth buffer format
= 4           dword (32 bit)

when frame buffer information is not available yet, set all values
in the FrameBufferInfo structure to 0

input:    FrameBufferInfo pinfo[6]
pinfo is pointed to a FrameBufferInfo structure which to be
filled in by this function
output:   Values are return in the FrameBufferInfo structure
Plugin can return up to 6 frame buffer info
************************************************************************/
EXPORT void CALL FBGetFrameBufferInfo(void *p)

I implemented these extensions in Glide64, but 1964 just crashed with them.
Hacktarux added support for them in Mupen64 and it worked in some cases.

It's not hard to support the extensions on plugin side, but it will not work without support from emulator side.

**Comment by purplemarshmallow** [comment]
I think these extensions are not really useful because they just notify the plugin. Instead the emulator should detect reads and writes to the framebuffer area and apply these reads/writes to the framebuffer on the video card. Dolphin can do this.
I discussed about this here:
https://github.com/project64/project64/issues/574#issuecomment-135225024

**Comment by gonetz** [comment]
These extensions notify the plugin that the emulator detected reads / writes to the framebuffer area. 
That is emulator asks plugin to fill that area with data or copy that data to video buffer. Why emulator should do it itself?

It will be useful to find, how Dolphin treat this problem in reality. If Zilmar really ready to help, it will be great. 

Regarding depth buffer emulation: software depth buffer rendering seems to be better solution for most games which need it. Yes, it will require to re-implement hellot of code from Glide64, which I tried to avoid at all costs. From the other side, software clipping will solve various clipping issues caused by incompatibility of OpenGL and N64 viewport functionality.

**Comment by purplemarshmallow** [comment]
dolphin works like this: 
If the CPU modifies the framebuffer this operation is converted into a GPU operation and frame buffer on the GPU is modified instead. Dolphin calls this "efb poke"

Regarding depth buffer emulation I now think emulating it on the GPU is the better solution but depth buffer access from the CPU needs to be implemented. Copying the depth buffer once per frame is a bad solution. Dolphin also emulates the depth buffer on the GPU.

**Comment by gonetz** [comment]
>>If the CPU modifies the framebuffer this operation is converted into a GPU operation and frame buffer on the GPU is modified instead. Dolphin calls this "efb poke"

Interesting, how technically is it possible? Especially when GPU frame buffer  is much larger than the one in RDRAM.

**Comment by purplemarshmallow** [comment]
Here's an explanation from a dolphin dev:
>The gamecube also has the framebuffer mapped in the virtual address space of the ppc. We call this feature "efb access", we queue all writing access and apply them asynchronly on our framebuffer in VRAM. But readback is slower. On OGL, we try to cache them to speedup CPU based postprocessing, but every readback after a common rendering call needs a GPU round trip time, which is usually about one milli second. 

I don't know how the dolphin developers solved the problem with framebuffer size, maybe a dolphin developer can answer this question

**Comment by olivieryuyu** [comment]
i also believe it would be good to check Dolphin concepts.

**Comment by gonetz** [comment]
IMO:

1 cite: "If the CPU modifies the framebuffer this operation is converted into a GPU operation and frame buffer on the GPU is modified instead. Dolphin calls this "efb poke" "

I see no point for such technique. It would be enough if emulator will notify graphics plugin that color buffer is modified. The plugin will load the color buffer as texture and blend it with current frame buffer. That is the way, how "Render frame buffer as texture" works, but the help from emulator side will allow plugin not to do it every frame.

2. Notification, that CPU is going to read from frame buffer may help with frame and depth buffer emulation greatly. Especially for depth buffer emulation. Currently plugin reads data from graphics card for every pixel in RDRAM depth buffer. CPU usually needs only few pixels to probe and decide should the object (corona) be drawn. If emulator will ask plugin to read hundred pixels instead of 640x480 area, it will be great speed up. Also it will fix issue with data synchronization, which we have in HLE/LLE mode. Reads from graphics card will be performed right when they needed. But emulator must wait until that data is read.

**Comment by purplemarshmallow** [comment]
what if the CPU modifies an auxiliary buffer? Can this be emulated using 1964's extensions?
what about CPU based depth buffer clear? #161 Can it be emulated without using hacks?

**Comment by gonetz** [comment]
>what if the CPU modifies an auxiliary buffer? Can this be emulated using 1964's extensions?

Yes. Plugin provides emulator with a list of allocated frame buffers, see  FBGetFrameBufferInfo. Plugin can include auxiliary and depth buffers to that list as well.

> what about CPU based depth buffer clear? #161 Can it be emulated without using hacks?
Hmm, may be. Emulator will notify plugin about writes to depth buffer, plugin may copy these values to video card. It also may help for RE2, which uses pre-rendered depth buffer for static objects.

**Comment by purplemarshmallow** [comment]
And what does the plugin do if it gets the notification from the emulator that auxiliary buffers are modified? It would be necessary to copy auxiliary buffers into RDRAM and then load them again. Sounds problematic

**Comment by gonetz** [comment]
Yes, it sounds problematic. We may try to understand the purpose of such modification. 
If CPU only writes something to the buffer, we can copy that value to video card. Probably it can be ignored. I don't remember many examples of auxiliary buffers modification. I remember the case when CPU set alpha for all pixels to 1, that is makes the buffer totally opaque. That's why I use 0xFFFEFFFE mask when check buffer's pixels for validity.

**Comment by purplemarshmallow** [comment]
>Probably it can be ignored

This is a bad idea. An emulator should focus on accuracy. Zelda OOT reads pixels in the framebuffer. I think the game checks if the framebuffer is drawn. This causes the famous subscreen delay.

**Comment by gonetz** [comment]
I just run Zelda OOT with Glide64 and Mupen64 under debugger. FBRead was called when I open subscreen, FBWrite did not.
I don't understand, why CPU may need to modify auxiliary buffer with Link's model. I don't see important difference between Link's model in software and hardware plugins.

**Comment by purplemarshmallow** [comment]
I noticed this when I worked on validity checking problems in OOT. The CPU writes different values to the auxiliary buffer with Link’s model depending on what data I wrote there. So there must be writes and reads. It’s hard to say why this happens, maybe it’s just a filter but maybe the CPU also checks if the buffer is drawn correctly.

**Comment by oddMLan** [comment]
https://dolphin-emu.org/blog/2017/11/19/hybridxfb/

Probably we can get some ideas from this article in regards of frame buffer copies
Even the dolphin team seems to think modifications done by the CPU, especially when partial, are tricky stuff
For instance, do we right now unconditionally copy the color buffer to the N64 RAM? If so, can an option to skip the copy to RAM be made to save resources? But if the N64 wanted to modify it, postprocessing would break or games would crash...

**Comment by loganmc10** [comment]
> do we right now unconditionally copy the color buffer to the N64 RAM? If so, can an option to skip the copy to RAM be made to save resources?

I would say it depends on the GFX plugin, but yes, GLideN64 copies the color buffer to RDRAM every frame. If "async" copies are enabled, it actually copies the previous frames color buffer into RDRAM, if "sync" copies are enabled, it copies the current buffer. Copying data from the GPU can be quite demanding, which is why "async" copies were created as an option.

This is the problem that the FBInfo extension tries to solve. Right now the buffer is copied every frame because GLideN64 isn't sure if the emulator is going to need that data or not. FBInfo is an extension where the emulator can notify the GFX plugin "I need data from the color buffer", and this way, the GFX plugin only needs to copy data when it's actually needed, not every frame.

**Comment by gonetz** [comment]
@oddMLan Very interesting article, thanks! I had very hazy notion about GC/Wii graphics subsystem. I thought that it renders frame in separate video memory (true) and that CPU can't directly modify that frame (false, it can after copy to main memory). It was fun to know that Dolphin can run well most of games without proper VI emulation and without CPU-to-buffer writes emulation. N64 graphics plugins were on similar level 14 years ago - almost no VI emulation and "read always" option as CPU read/write emulation, but number of well running games was much less. Overall impression: frame buffer emulation on Dolphin is simple thing in compare with difficulties, which  developers of N64 hardware graphics plugins have to solve. Don't get me wrong, Dolphin devs solving very complex problems, and they use creative ways to solve them. However N64 frame buffer emulation problems are more varied and complex due to N64 hardware architecture and hardware capabilities, which hard to map into PC GPU. 

Regarding ideas to adopt: purplemarshmallow tried to apply one idea mentioned in the article, but without much success, see #791. I still believe that the idea is useful, but can't find time to play with it.

Regarding particular issues with CPU read/write to frame buffer. IMO, properly implemented FBInfo is the best we can get. FBWrite solves problem with showing small details, which CPU renders to buffer. It works much better than "copy buffer from RDRAM". FBRead solves problem with slow sync reads. We need to polish that feature and it will be our silver bullet for most of 'CPU-frame buffer' issues.
