### ISSUE TITLE
GLideN64 possibly broken since Aug 26, 2015 for PJ64 2.2

### ISSUE THREAD

**Issue by Cetacea3691** [gonetz/GLideN64#696]
Is GLideN64 possibly broken since Aug 26, 2015 for PJ64 2.2 on Windows 7?
It just crashes when booting a ROM or opening the configuration window.

**Comment by purplemarshmallow** [comment]
Do you build it yourself? After https://github.com/gonetz/GLideN64/commit/2604b57bf1283f2383f51a8d295e9cf539489c6b you need to rebuild GLideNUI

**Comment by Cetacea3691** [comment]
I used a build from EmuCR since I would need to compile the latest qt source just to be able to compile GLideNUI with VS2015.
Maybe if I have some more time I'll give it a try :) .

**Comment by purplemarshmallow** [comment]
I know you need the Qt plugin for Visual Studio to build GLideNUI. You also need a static Qt build. It should also be possible to make a dynamically linked build so you don't have to build the Qt source but I haven't managed to make a dynamically linked build yet.

**Comment by SigmaVirus** [comment]
I too can confirm that GLideN64 is broken since Aug 26, 2015 for PJ64 2.2
It's broken in a sense that you can't save configurations made in GLideN64 and Project64 crashes afterwards.

I haven't built GLideN64 myself but have used EmuCR builds and the last known working version/revision for me was the one labeled GLideN64 Git (2015/08/24) with the change log:

* Merge branch 'master' of https://github.com/gonetz/GLideN64
* Enable hack_VIUpdateOnCIChange for Perfect Dark.
Fixed: Perfect Dark flickering lights #609

I know EmuCR isn't the best place to get builds but they're the only one building this at the moment and it have worked great so far.

**Comment by baptiste0602** [comment]
EmuCR builds not working because they probably use the "old" GLideNUI.lib.

**Comment by SigmaVirus** [comment]
@baptiste0602 

That would explain a lot, I guess we'll just have to see if EmuCR builds it with the "new" GLideN64UI.lib then.

I have recently updated to Windows 10 and thought it had something to do with that but then I found this issue here and now I know it got nothing to do with Windows 10 at all.

Off-topic:

As for Nintendo 64 emulation in general on Windows 10 especially with Project64 2.2.0.3 it have not been a smooth sailing.

At the moment I have currently reverted to my old Project64 1.7.0.50 rev23 build as it does not appear to BSOD.
I know about setting Project64 2.2.0.3 compatibility to Windows XP SP 3 and it works perfectly but I'll wait till it gets a proper fix.

Aside from that Windows 10 works great with everything else thankfully.

**Comment by Yui12** [comment]
I'm still on windows 7 and it crashes. Since I can't depend on emucr myself to make a proper build, can someone tell me how to build this plugin from the source on Windows 7? I never have complied source code before, but I'm willing to try if someone can tell me. I always ask, but one answers. Strange since many people say "oh build it yourself if you don't like it" yet are not nice enough to tell you how at the very least, and no this has nothing to do with what I'm talking about here.

**Comment by purplemarshmallow** [comment]
you can read instructions here: https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows). Building GLideN64 is complicated because there are many dependencies. If you never complied source code before I recommend you download the official version here: https://github.com/gonetz/GLideN64/releases

**Comment by Yui12** [comment]
Alright. The official version is not as good so I don't bother and it has slowdowns on my PC with framebuffer on, so nevermind. Thanks anyway.

**Comment by AmbientMalice** [comment]
Since it isn't likely the UI will be updated again in the near future, maybe @gonetz could upload a new GLideNUI, and possibly elaborate on how to correctly build it?

**Comment by Cetacea3691** [comment]
GLideNUI + file update only for VS2015.
https://drive.google.com/file/d/0Bygxj1zIGEsccGk2dHRJb3RkVVU/view?usp=sharing

**Comment by Cetacea3691** [comment]
I've compiled GLideN64 from the source code and it works like expected (no new bugs etc.).
@purplemarshmallow thank you for the hint with the static Qt build you saved me at least 30min :D

**Comment by Yui12** [comment]
Thanks a lot. I really appreciate this! It works great!

**Comment by SigmaVirus** [comment]
@Cetacea3691 Thank you, you're a saint!

**Comment by AmbientMalice** [comment]
@Cetacea3691 Since VS2015 GLideNUI doesn't seem to work with VS2013, do you think you could post the steps for compiling, or even better, add them to the wiki?

**Comment by Cetacea3691** [comment]
I will try to write a complete beginner friendly building guide for GLideN64 on Windows and Microsoft Visual Studio (2012-2015).
So stay tuned ;).

**Comment by Yui12** [comment]
Thanks. Appreciate it. There is no rush though so take your time.

**Comment by SigmaVirus** [comment]
Anyone that have the latest build for uploading? I've been playing Majora's Mask lately and would die for a build with the latest fixes for it, EmuCR builds are still broken.

**Comment by AmbientMalice** [comment]
Here, @SigmaVirus This is the latest "master" build. It doesn't have the experimental framebuffer fixes, but those aren't needed for Majora's Mask. Also, for some weird reason, anti-aliasing seems to be broken. https://mega.nz/#!c5xxzDRI!zlBNe20wZXaqyODiIK37odSBO7TmCKJSrq3Tvbf2kfU

I kinda feel bad just giving you the plugin since PJ64 2.2 is such a mess. Here's a custom PJ64 build that is reasonably up to date, if you're interested. If the sound goes out of sync, switch to the Jabo plugin. https://mega.nz/#!1pJUBTyI!pkZtOfV-HNy5P2MjOn47d0k8XbMvX70KhQUDhcE_1-I Now this PJ64 includes GLideN64, but it's outdated by a week or so. So replace the dll with the one provided above. In the event you want to stick with your current version of Project 64, make sure you use administrative permissions. If you need help with resolutions, the widescreen hack, etc, just ask.

**Comment by SigmaVirus** [comment]
You're an angel and a saint, thank you very much for this!

Don't feel bad at all, I've switched back to both Project64 1.7.0.50 rev23 and Windows 8.1 while I'm waiting for Project64 2.x to be fixed in the future and for Windows 10 to mature as I've had other problems with it.

Been using 2.x on Windows 8.1 as well and while it does not BSOD like it does on Windows 10, I've had my shares of nastiness with 2.x in the past but I can tell you this much, it's starting to go in the right direction so hopefully one day Project64 will shine.

At the moment 1.7 have less issues on my end and I use GLideN64, Azimer Audio XAudio2 and NRage and it works really well. 

Then again I only own 11 games to begin with (DOOM 64, GoldenEye 007, Mario Kart 64, Paper Mario, Perfect Dark, Super Smash Bros., Super Mario 64, Star Wars Shadows of the Empire, Zelda Ocarina of Time, Zelda Majora's Mask and Yoshi's Story) and they really don't have critical issues so to speak and are more or less beatable.

Anyway thank you yet again!

**Comment by gonetz** [comment]
@AmbientMalice I have updated Build From Source (Windows) instruction with How to build GLideNUI info a week ago:
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

Have you tried to follow it? I'm not sure that the instruction is 100% correct, so some feedback would be useful.

**Comment by purplemarshmallow** [comment]
>Regarding Anti-Aliasing that's not a problem at all as I don't use any kind of enhancements when I use emulators as I'm trying to come as close to the original image as possible.

On a real N64 most games use Anti-Aliasing

**Comment by SigmaVirus** [comment]
OK, thanks I didn't know that actually.

For GLideN64 I pretty much use default settings (640x480) and usually just make one change and that is to use 3-point bilinear instead, not pixel perfect by any means but it looks authentic enough for me.

I haven't had my N64 plugged in for years, I've been playing my games on emulators for so long that I have forgotten how they really looks.

I'm a game collector and the only way for me to enjoy my games is to play them in emulators, that way they're in pristine condition but I can still enjoy them.
Eat the cake and still have it so to speak.

I will however look this up with Anti-Aliasing when it works again, do you know how much you have to apply?

**Comment by purplemarshmallow** [comment]
GLideN64 is designed to render at a high resolution I recommend you set the fullscreen resolution to your desktop resolution. Maybe this should be default? GLideN64 can produce clear hi-res graphics but it does not emulate certain filters used on original hardware so it does not look very autentic. Also the Anti-Aliasing method works differently from the method which is used on original hardware.

I tracked the commit down which broke Anti-Aliasing I hope it's not hard to fix it again.

I think there was a feature planned which should allow rendering at native resolution but it's not implemented

**Comment by Yui12** [comment]
I just emailed EmuCR about it in hopes of noticing the problem.

**Comment by SigmaVirus** [comment]
@purplemarshmallow 

When I started with GLideN64 earlier this year, I did set the fullscreen resolution to my desktop resolution which is 1920x1080 but honestly I didn't like it at all.

I changed the fullscreen resolution to 640x480 just for fun and liked it right away, there's just something about that image that appeals me.

Thanks for the information though, it's always fun to learn new stuff.

**Comment by Yui12** [comment]
The most recent git from (2015/09/30) seems to work with Project 64 on my end. I hadn't fully tested it but there is no crashing no longer on my end. We'll see if it stays that way. If it does, I should thank the webmaster for fixing it quickly.

**Comment by DonelBueno** [comment]
It does work for me too. I've tested it in a lot of games.

One issue I noticed though is that it doesn't load HD Textures if there isn't a cache file for them already made.

**Comment by Yui12** [comment]
Strange. I don't know if it's because of the build or just a bug though. I would have not noticed since I don't use Texture packs.

**Comment by SigmaVirus** [comment]
@Yui12 
OK, so EmuCR builds are working again?

**Comment by Yui12** [comment]
The most recent one at least.

http://down.emucr.com/v3/4906401323286528

**Comment by SigmaVirus** [comment]
Thanks!

EmuCR seems to have corrected this now, it works.

I guess this issue can be closed now since it's no longer relevant.

**Comment by Yui12** [comment]
The current releases now don't crash no longer so yeah, time to close this thread.
