### ISSUE TITLE
Odd Graphical Issues in Super Mario 64 ROM Hacks

### ISSUE THREAD

**Issue by oOSuperMarioOo** [gonetz/GLideN64#758]
If I run Super Mario 64 using GlideN64, it runs without any graphical issues; however, if I run a ROM hack of Super Mario 64, many graphical issues will occur, such as having most of the graphics be black (https://www.youtube.com/watch?v=4lJ3ZQGSOLo). This graphical bug in Super Mario 64 ROM hacks doesn't occur if I use Rice.

**Comment by thecoreyburton** [comment]
This is the same issue as: #431 #525 #535.

Here's some advice I've learned and posted in the other threads that might help you: Both rice and Glide64 have many "hacks" in place in order to play games faster (or in order to make features work where they otherwise wouldn't, when they were written). GlideN64 is written to be more faithful to the original console and more accurate, whilst still having options for higher resolutions and enhancements.

Try play the hack with angrylions pixel-accurate video plugin. It was designed to be as faithful to the console as possible. If the textures are still black then it's being emulated correctly and GLideN64 is not at fault. Most rom hacks likely took advantage of the way less-accurate plugins emulate the video side of things and would show up with black textures on the actual console.

I'd be interested in having a work-around, such as an option to enable a fix for hacks if they're not in the database of roms but this is an unlikely situation, especially at the moment as accuracy is the focal point and there's still a long way to go there in regards to a number of things, including frame buffer emulation.

**Comment by oOSuperMarioOo** [comment]
Oh... I didn't realize that not one, but three issues regarding Super Mario 64 ROM hacks are already added to GitHub.

Also, I don't know anything about the AngryLion plugin, nor do I know that it's even in Mupen64Plus AE 3.0 at all.

**Comment by olivieryuyu** [comment]
@gonetz 

can it be closed?
