### ISSUE TITLE
GLideN64 takes a long time to exit

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#785]
When texture cache is enabled in Android, it takes a very long time for the plugin to exit. In the order of 10 to 20 seconds or more depending on the game.

During this time a black screen is shown with the number of textures from the texture cache that have been saved to disk.

Is it possible to to save the texture cache in a low priority background thread when it's being generated while the game is running?

**Comment by gonetz** [comment]
In theory yes, it is possible. However, there are nuances to take into account. When to start the save? Texture cache must not be changed after the process started.

Also, I will not do it due to lack of time.

**Comment by oscarbidabehere** [comment]
@gonetz I noticed the plugin saves the whole cache to disk if a new texture is cached instead of only saving the new cached texture to disk. Is it possible for the plugin to only save new cached textures? this is: cachedTextures - loadedTextures.
Maybe it's more clear with an example:
-If you load SM64 with "6xBRZ texture enhancement"  and "save texture cache to disk" without any cache file and you close the game at the title screen it will dump like 60 textures.
-If you open the game and progress to the start of the game (outside the castle) it will dump like 110 textures
-If you enter the castle 140 textures
So I think you are always dumping the whole cache to disk instead of only saving incrementally the new cached textures. So if you have a very complete cache but each time you play you encounter 1 or 2 new textures it will take 10 to 20 seconds to dump the whole cache instead of taking a couple of hundred of milliseconds to save 1 or 2 textures.

Love to hear what you think, thanks for your hard work!

**Comment by gonetz** [comment]
@oscarbidabehere I'm working on texture cache for HD textures, which will not load all content of the cache into memory, but load textures from HDD by demand. It is necessary because some HD packs are very large and 32bit emulators can't load them. This new cache can be used for enhanced textures as well. Textures load will be slower, but cache initialization and save will be much faster.
Current implementation indeed keeps all texture data in memory and saves it to disk on program exit.

**Comment by fzurita** [comment]
Solved by HTS
