### ISSUE TITLE
NBA Hangtime crash ingame

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#795]
The emulator eats gigabytes of RAM. Then eventually it crashes. Most likely has to do something with all the failed assertions in this game #107

**Comment by oddMLan** [comment]
Yep, there's a memory leak somewhere. Memory usage is constantly increasing.
But the game does not crash for me, it only slows down to a crawl. How long until it crashes? I have 8GB RAM so it might take a while to exhaust all the available RAM, which I assume it's what causes the crash.

**Comment by gonetz** [comment]
It is not memory leak. Texture cache does not work properly, new textures constantly allocated.

**Comment by gonetz** [comment]
Update: new textures constantly allocated because the game programmed that way. It seems that it has some large background image and game viewport constantly moves along it. Each frame it moves slightly, resulting in new set of slightly different textures. Texture cache helpless here.

I've added texture cache size limit to avoid game crash. Plugin clears whole texture cache when texture cache size limit reached.

BTW, texture cache in Glide64 also get overloaded almost instantly. Glide64 also clears cache when it overflowed. Since cache size is limited to 4k textures, cache clear works fast. GLideN64 cache size limit is much larger, so its clear can take time.

**Comment by purplemarshmallow** [comment]
not crashing anymore

**Comment by loganmc10** [comment]
I still have some people that have issues with slowdowns related to this.

For starters, shouldn't the 500MB cache size limit have stopped this? @purplemarshmallow @oddMLan mentioned GB's of memory.

Also, 128000 might be too high, @orbea had slowdowns and a crash playing Beetle Adventure Racing that was fixed by changing the number to 32000.

Finally, wiping the cache causes a "hiccup", since the cache needs to be rebuilt for the next frame obviously. Wouldn't it be better to just delete the oldest texture to make room for the new one like I did when I submitted a pull request for this issue on the Raspberry Pi? (https://github.com/gonetz/GLideN64/pull/1017/files)
