### ISSUE TITLE
Zelda OoT Widescreen Disappearing Assets Issue

### ISSUE THREAD

**Issue by SwinglesMan** [gonetz/GLideN64#814]
Objects disappear when going through doors momentarily or when things are almost offscreen. May exist in multiple games. Perhaps increase the range of more things to be drawn offscreen? Shrugs.

**Comment by gonetz** [comment]
Actually, game should not render objects, which are out of original viewport. It is waste of resources. I think the game renders some objects offscreen to avoid the problem with sudden object's apearing/disappearing. The plugin can't control how many offscreen objects will be drawn. We are lucky to see almost everything in widescreen mode in Zeldas. Other games show less offscreen objects. Increase the range will make it worse.

**Comment by SwinglesMan** [comment]
Issue is solved by adding these 2 gameshark codes when in adjust mode......:

http://forum.pj64-emu.com/showthread.php?t=5389
http://forum.pj64-emu.com/showthread.php?t=5431

So, how about now?

**Comment by gonetz** [comment]
I don't understand the question. What do you suggest?

**Comment by SwinglesMan** [comment]
You said increasing the range makes it worse. This code proves it doesn't. This code fixes exactly what the OP is asking and also fixes things appear/disappearing while half way offscreen/onscreen. So, the question was, how about now? Since this displays no issues whatsoever even in performance, how about integrating something like this in the plugin so we can use it without cheats on?

**Comment by theboy181** [comment]
The cheats modify the ROM and would not be a universal fix for the plugin. You can ask the person on PJ who released the codes to explain his methods for findin them then you can find more for other games

**Comment by SwinglesMan** [comment]
Except for the part where the epsxe pete's gpu plugin can do the same thing without cheats and pcsx2 team do their widescreen fixes in a similar fashion. And for gonetz to have done a widescreen fix of his own through the plugin, means it can be improved on even more just like the cheat code. What gonetz mode can do was once what the cheat codes did. So it can be modified to fit what the cheat code is doing now.

**Comment by theboy181** [comment]
Nintendo had to do major culling in order to get decent framerates on the N64. I doubt that the PS2 suffered from underpowered HW so most of there game developers wouldn't of spent loads of time making optimizations on the PS2. 

If you do a little investigating you will find that N64 developers used many tricks to squeeze as much out the HW with tricks like speed multipliers and conditional framerates too. MK64 is a good example a game that developers used unconventional methods.

**Comment by SwinglesMan** [comment]
we are on a pc. we are not on an n64. I also already covered performance and that there wasn't any performance loss :P

**Comment by theboy181** [comment]
ur retarded.

**Comment by SwinglesMan** [comment]
well garsh darnit bob. you sure did win the internetz there, hee yuck.... :/

**Comment by gonetz** [comment]
@SwinglesMan , you got wrong my explanation. You don't want to understand theboy181 points. It seems that you does not have basic understanding of how things work. So, I'll start from the basics.

The N64 console consists of two main micro chips: Central Processor Unit ((MIPS R4300i) and multimedia co-processor RCP. CPU process the game's program code and prepares display lists for RCP. The display lists contain information about objects to be rendered. You must understand that all multimedia data, all sounds you hear and all graphics you see are defined by program code processing. RCP translates high-level representation of these data to concrete sound samples and graphics primitives. It has no control on program code and can't add or remove objects to/from display lists.

Now, to emulation. CPU is emulated by N64 emulator. RCP is emulated by N64 plugins (RSP, sound, graphics). Graphics plugin emulates part of RCP; it processes commands in the graphics display list and renders primitives. It can't show objects, which are not in the display list.

Your cheat code proved only the basic fact: visible objects controlled by the program code. You alter the program code with cheats and got more objects to draw.

The widescreen hack does not alter the program code. It just increases the viewing range and shows objects, which  otherwise would be cut by viewport. You must understand, that these objects already present in the display list. I explained, that "game should not render objects, which are out of original viewport. It is waste of resources." Games usually programmed that way to cut offscreen objects from the display list. When I said "Increase the range will make it worse" I meant that objects, which are far from default viewport are cut and we will get more disappearing objects with wider range.

If you may change program behavior with cheats and get more objects in graphics display list - you are lucky. However, it is related to CPU work and has nothing with graphics plugin.

**Comment by SwinglesMan** [comment]
So how does your explanation negate why the gpu plugin shouldn't read the cheat values from the rdb in order to complete your widescreen in your plugin?

**Comment by gonetz** [comment]
Killing question. Why I wrote the explanations? Why I explained how things work?

gpu plugin shouldn't read the cheat values from the rdb because it can't do anything with these cheats. Cheats alter game's program code. Gfx plugin does not work with program code.

I can't make this explanation more simple.

**Comment by SwinglesMan** [comment]
"Why I wrote the explanations? Why I explained how things work?"
That is not what I even asked.


If it can't do anything with them then why can jabo's plugin read them?

Physx is for graphics and yet you can tell it to work from the cpu OR gpu...
Just because something works from the cpu, it is still graphics related because it is based on what you can see.

You don't have to do it. I don't care. I'm just asking the question. You also don't have to turn in to theboy by getting butthurt. No one is attacking you so calm down.

**Comment by oddMLan** [comment]
Jesus, you are dense.

**Comment by SwinglesMan** [comment]
@oddMlan: You are so intelligent. You know redundant internet weeaboo catch phrases. Good for you. So are you gonna tell me why Jabo's plugin reads from the rdb certain cheat values or are you just going to keep having temper tantrums? It's a simple question and it's the last question I want to know.

**Comment by theboy181** [comment]
Love your avatar odd man. I bet it's the same guy that sold weed to singleman4eva. :)

**Comment by purplemarshmallow** [comment]
>So are you gonna tell me why Jabo's plugin reads from the rdb certain cheat values 

I can tell you. Project64 has indeed cheat codes in the rdb. They come from a time where nobody really cared about proper emulation. People just made imperfect hacks to make games playable. The cheat codes are meant to patch major flaws in the gfx plugins. Developers did not care about reproducing the behaviour of a real N64 on the PC and were not interested in investigating issues properly.

Fact is that all these cheat codes are imperfect solutions and problems remain. So the PJ64 developers made the decision to enable these cheat codes for Jabo's plugin only. It is no longer developed and closed source so these problems can never be fixed. So Jabo's plugin itself does not read cheats instead the PJ64 core checks if Jabo's plugin is used and enables certain cheats.

GLideN64 does not want to rely on cheat codes. Here we want to find better solutions. That's the reason why no cheats are enabled if you use GLideN64 with PJ64.

A good example is Pokemon Snap. The camera freeze fix codes in the rdb do not solve the real problem. The camera detection in this game still does not work even with the cheat code enabled. GLideN64 can emulate this feature properly. Camera detection works and no cheats are needed.

**Comment by SwinglesMan** [comment]
Okay, thank you for the information.
