### ISSUE TITLE
640x480 framebuffer bug Perfect Dark (U)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#844]
This is not a new issue. Glide64 was affected by it, too. If running with 640x480 resolution, pause menu backgrounds go haywire. Bear in mind Perfect Dark (U) has a 640x222 framebuffer or thereabouts in high resolution mode instead of the more common 480x360. The PAL and Japanese versions run at a different resolution, also.

Image:
![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/12633881/bec2521e-c5c0-11e5-8ba1-8d9a8d100940.jpg)

Low Resolution Pause Menu:
![gliden64_perfect_dark_002](https://cloud.githubusercontent.com/assets/10704701/12633889/cee48ab8-c5c0-11e5-8f1e-ee779c4ac704.jpg)

High Resolution Pause Menu:
![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/10704701/12633913/0cb32822-c5c1-11e5-8fd4-92f830f5d7f8.jpg)

**Comment by Blue-Ike** [comment]
Don't forget if you go under "Video Menu" in Perfect Dark there is an option to tick and untick "Hi-Res" in the game. For me, when I have it ticked on Hi-res it causes the text on the menus and weapon pick ups not to show. 
![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/16857573/12644791/7e25d064-c593-11e5-946e-2fd70dd828f8.jpg)
![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/16857573/12644792/811a344a-c593-11e5-8472-724e199fd635.jpg)
![gliden64_perfect_dark_002](https://cloud.githubusercontent.com/assets/16857573/12644796/832e7bf6-c593-11e5-9167-083f9910f8f9.jpg) Unfortunately, the text seems to show when I play on windowed mode instead of full screen. Both resolutions I have on 640x480.

**Comment by AmbientMalice** [comment]
This doesn't seem to occur with native resolution modes. I wouldn't call that "fixed", though.

**Comment by gonetz** [comment]
Fixed
