### ISSUE TITLE
[Regression] (native res branch) Jet Force Gemini shadows missing

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#864]
I haven't had time to check which commit introduced it, but Jet Force Gemini doesn't seem to be rendering shadows anymore.

**Comment by purplemarshmallow** [comment]
It only seems to happen in the native res branch.

Some time ago I tried to fix the shadows in Jet Force Gemini. I wanted to see how they look like if they are rendered in native res so I set the scale of the shadows to 1. I got no shadows.

I think this bug was always there and the native res rendering feature uncovered it

**Comment by purplemarshmallow** [comment]
Seems fixed now. But native res does not seem to improve the shadows. Edges are still sharp.

**Comment by AmbientMalice** [comment]
There's something wrong with the shadows when aux FB is disabled.
![gliden64_jet_force_gemini_001](https://cloud.githubusercontent.com/assets/10704701/13444784/08fe2e5e-e054-11e5-8c87-ed0125802aab.jpg)

**Comment by gonetz** [comment]
Try reset to defaults. Shadows work for me.

**Comment by AmbientMalice** [comment]
They work with "emulator help" enabled. In normal mode, they look like that.

**Comment by AmbientMalice** [comment]
I think it's an async issue.
