### ISSUE TITLE
Bugs in zelda OOT, Starfox and mario 64

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#910]
Thx for the fantastic plugin!

I experience a few errors in the mentioned games.

Zelda OOT: From around late December, when pressing start the emulator often crashes. Before December builds work. Using other plugins also work.

Star fox 64: The same garbage that appears in Super Mario 64 also is present in star fox 64. Furthermore, it is sometimes permanently visible around the edges of the game-screen. By this I mean the area that is outside of the actual image. The over-scan area.

Mario 64. I experience a small stutter from time to time. A frame-drop here and there I think. Also there is audio stutter/slowdown whenever I save in this game. Might not be glideN64 though.

**Comment by SigmaVirus** [comment]
I haven't had too much problems with GLideN64 but that Zelda issue have happened on quite a few occasions on newer revisions actually which I can't duplicate on a revision dated 2015-09-28.

I have tested pressing start on Glide64 Final and this have never happened before.

I don't play Ocarina of Time much these days since I 100% it last year but it's always good to test all sorts of things nevertheless.

Star Fox I don't own but Mario 64 seems to work great here on my end, Mario 64 rarely if ever fails no matter what setups you throw at it.

I'm on Project64 2.2.0.9999 dated some time at beginning of this month and both Interpreter and Recompiler works great with Mario 64.

Got a pretty beefy setup though so frame-drops and stuttering rarely happens anyway.

**Comment by budtz** [comment]
I should add i have 2.2.0.9999 build from this month.
My pc is a quadcore haswell, 8gb ram and a 760gtx

I should also add that the framedrops i get in mario are with the emulator running at 100,0%. No slowdown - only when I save games or copy or erase.

**Comment by SigmaVirus** [comment]
I've been investigating and I think your Mario 64 issue might be related to Project64 itself and these issues:
https://github.com/project64/project64/issues/1026 and https://github.com/project64/project64/issues/897

**Comment by budtz** [comment]
Thx that might be it for the slowdown when saving! I wonder if it can explain the light stuttering i get as well. It seems something like a frame is dropped every 2 minutes or so. So its not much. Other games dont do it though

**Comment by retrobenny** [comment]
I too have been a victim of the OOT crash yet via Android,but the 3.0 variant runs it fine.
Also messing with debug versions of both OOTMQ and MM with OOTMQ debug freezing unless the subscreen delay fix code is used.
The debug text now works correctly,which is awesome,hope someone can find out what is causing the issue with 3.1 and iron it out.

**Comment by budtz** [comment]
I replaced the RSP plugin with something called RSP git and the the zelda crash bug seemed to go away
